/**
 * OC-P11 integrated approval ceremony black box (ADR-007, req 7).
 *
 * Corrected architecture (C1–C6): the conversation crosses REAL
 * generated bytes throughout — the plugin gate with the EXACT
 * two-argument SDK shape, the NATIVE tool module executed for real
 * (inline bodies, host-held session, ask() human boundary), the REAL
 * built CLI, a REAL Core project, and the real filesystem. Fixtures
 * cover only the model (tool arguments), the human (ask allow/deny),
 * the OS keychain (key helper), and the entry token file.
 *
 * - Gaspar creates SPEC/ADR/security drafts through native tools;
 * - the PO sees the exact revision and confirms natively;
 * - confirmation records a signed Core approval;
 * - model-only approval, replay, stale revision, cancellation, and
 *   forged confirmation all deny;
 * - the conversation continues without restart or external commands;
 * - Harness, Module, and Work Package follow the same governed path;
 * - no product code is writable before implementation dispatch.
 */
import { describe, it, expect, beforeEach, afterEach } from "vitest";
import {
  chmodSync,
  existsSync,
  mkdtempSync,
  readFileSync,
  realpathSync,
  rmSync,
  symlinkSync,
  writeFileSync,
  mkdirSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createHash, randomBytes } from "node:crypto";
import { pathToFileURL, fileURLToPath } from "node:url";
import {
  approvalChallenge,
  buildEnrollmentChallenge,
  buildEnrollmentPayload,
  buildSessionAuthorizationPayload,
  canonicalizeJson,
  canonicalize,
  fingerprintPublicKey,
  generateApprovalKeyPair,
} from "@chrono/domain";
import { signApprovalPayload as domainSign } from "@chrono/domain";
import { ChronoCore } from "@chrono/core";
import { buildOpencodePlugin } from "./opencode-plugin.js";
import { buildOpenCodeAgentDefinition } from "./opencode-agent.js";
import { buildPlanningToolsFile } from "./opencode-planning-tools.js";
import { PO_KEY_ACCOUNT, PO_KEY_SERVICE } from "./keychain.js";

const REPO_ROOT = fileURLToPath(new URL("../../..", import.meta.url));
const FIXED_TIME = "2026-09-14T00:00:00.000Z";

function validPayload(sessionId = "SES-0001"): string {
  return JSON.stringify({
    ok: true,
    sessionId,
    projection: {
      projectState: "ANALYZING",
      nextAction: { key: "resume-discovery", summary: "Resume discovery" },
      requiredDecisions: [],
    },
    skill: { installed: true },
  });
}

function fakeTty(): () => void {
  const stdinDesc = Object.getOwnPropertyDescriptor(process.stdin, "isTTY");
  const stdoutDesc = Object.getOwnPropertyDescriptor(process.stdout, "isTTY");
  Object.defineProperty(process.stdin, "isTTY", { value: true, configurable: true });
  Object.defineProperty(process.stdout, "isTTY", { value: true, configurable: true });
  return () => {
    if (stdinDesc !== undefined) Object.defineProperty(process.stdin, "isTTY", stdinDesc);
    else delete (process.stdin as { isTTY?: boolean }).isTTY;
    if (stdoutDesc !== undefined) Object.defineProperty(process.stdout, "isTTY", stdoutDesc);
    else delete (process.stdout as { isTTY?: boolean }).isTTY;
  };
}

describe("OC-P11 integrated approval ceremony", () => {
  let tempDir: string;
  let root: string;
  let pluginPath: string;
  let core: ChronoCore;
  let signingKey = "";
  let gasparToken = "";
  let gasparSession: { id: string; token: string } = { id: "", token: "" };
  let restoreTty: () => void;
  let savedEnv: Record<string, string | undefined>;
  const sessionKey = "ceremony-1";
  let tools: Record<string, any>;
  let askMode: "allow" | "deny" = "allow";
  const askCalls: Array<{ permission: string; patterns: string[] }> = [];

  function tokenString(session: { id: string; token: string }): string {
    return `${session.id}/${session.token}`;
  }

  function hostTokenPath(): string {
    return join(tmpdir(), `chrono-gaspar-host-${createHash("sha256").update(`${root}|${sessionKey}`, "utf8").digest("hex").slice(0, 16)}.token`);
  }

  function toolContext(overrides: Record<string, unknown> = {}): Record<string, unknown> {
    return {
      sessionID: sessionKey,
      messageID: "m1",
      agent: "gaspar",
      directory: root,
      worktree: root,
      abort: new AbortController().signal,
      metadata: () => undefined,
      ask: async (input: { permission: string; patterns: string[] }) => {
        askCalls.push({ permission: input.permission, patterns: input.patterns });
        if (askMode === "deny") {
          throw new Error("human declined");
        }
      },
      ...overrides,
    };
  }

  async function hooksFor(directory: string) {
    const module = (await import(pathToFileURL(pluginPath).href)) as {
      ChronoGatePlugin: (ctx: unknown) => Promise<{
        "chat.message": (input: unknown) => Promise<unknown>;
        "tool.execute.before": (input: unknown, output: unknown) => Promise<unknown>;
        "tool.execute.after": (input: unknown, output: unknown) => Promise<unknown>;
      }>;
    };
    const hooks = await module.ChronoGatePlugin({ directory });
    return { message: hooks["chat.message"], before: hooks["tool.execute.before"], after: hooks["tool.execute.after"] };
  }

  function evidenceText(): string {
    try {
      return readFileSync(join(root, ".chrono", "runtime-activation.jsonl"), "utf8");
    } catch {
      return "";
    }
  }

  function questionArgs(line: string): unknown {
    return { question: "CHRONO product decision", header: "Approval", options: [{ label: line, description: "Record signed PO approval" }, { label: "Deny", description: "Do nothing" }] };
  }

  beforeEach(async () => {
    tempDir = mkdtempSync(join(tmpdir(), "chrono-ceremony-"));
    root = realpathSync(tempDir);
    mkdirSync(join(root, ".chrono", "hooks"), { recursive: true });
    writeFileSync(join(root, ".chrono", "chrono.db"), "", "utf8");
    pluginPath = join(root, "chrono-gate.js");
    writeFileSync(pluginPath, buildOpencodePlugin(), "utf8");
    writeFileSync(join(root, ".chrono", "hooks", "chrono-entry-session.sh"), `#!/bin/sh\necho '${validPayload()}'\n`, "utf8");
    chmodSync(join(root, ".chrono", "hooks", "chrono-entry-session.sh"), 0o755);
    // Exact generated native tool bytes, resolvable + executable here.
    const fixtureModules = join(root, "node_modules");
    mkdirSync(join(fixtureModules, "@opencode-ai"), { recursive: true });
    symlinkSync(join(REPO_ROOT, "node_modules", "@opencode-ai", "plugin"), join(fixtureModules, "@opencode-ai", "plugin"), "dir");
    symlinkSync(join(REPO_ROOT, "node_modules", "zod"), join(fixtureModules, "zod"), "dir");
    mkdirSync(join(root, ".opencode", "tools"), { recursive: true });
    writeFileSync(join(root, ".opencode", "tools", "chrono.ts"), buildPlanningToolsFile(), "utf8");
    writeFileSync(join(root, ".opencode", "package.json"), JSON.stringify({ dependencies: { "@opencode-ai/plugin": "1.18.30" } }, null, 2), "utf8");
    tools = (await import(pathToFileURL(join(root, ".opencode", "tools", "chrono.ts")).href)) as Record<string, unknown>;
    savedEnv = { ...process.env };
    for (const key of ["CHRONO_BIN", "CHRONO_KEY_HELPER", "CHRONO_ENTRY_ADAPTER", "CHRONO_ENTRY_TIMEOUT_MS", "CHRONO_GATE_MODULE", "CHRONO_GATE_WP", "CHRONO_SESSION_TOKEN", "CHRONO_GATE_AS", "CHRONO_GATE_ROLE", "CHRONO_REQUESTER_TOKEN"]) {
      delete process.env[key];
    }
    const shim = join(root, "chrono-shim.sh");
    writeFileSync(shim, `#!/bin/sh\nexec node ${join(REPO_ROOT, "packages", "cli", "dist", "bin.js")} "$@"\n`, "utf8");
    chmodSync(shim, 0o755);
    process.env["CHRONO_BIN"] = shim;
    core = new ChronoCore({ projectPath: root, runtime: "opencode" });
    expect(core.init().ok).toBe(true);
    const pair = generateApprovalKeyPair();
    restoreTty = fakeTty();
    const nonce = randomBytes(16).toString("hex");
    const fingerprint = fingerprintPublicKey(pair.publicKeyPem);
    const confirmation = buildEnrollmentChallenge("default", fingerprint, nonce);
    const timestamp = new Date().toISOString();
    const signature = domainSign(
      buildEnrollmentPayload({ projectId: "default", fingerprint, timestamp, nonce, authority: "PO", rationale: "test", confirmation }),
      pair.privateKeyPem
    );
    expect(core.enrollPo({ publicKeyPem: pair.publicKeyPem, nonce, timestamp, rationale: "test", confirmation, signature }).ok).toBe(true);
    signingKey = pair.privateKeyPem;
    const keyFile = join(root, "po-key.pem");
    writeFileSync(keyFile, signingKey, { mode: 0o600 });
    const helper = join(root, "key-helper.sh");
    writeFileSync(helper, `#!/bin/sh\ncat "${keyFile}"\n`, "utf8");
    chmodSync(helper, 0o755);
    process.env["CHRONO_KEY_HELPER"] = helper;
    const sessionNonce = randomBytes(16).toString("hex");
    const sessionTimestamp = "2026-09-11T00:00:00.000Z";
    const sessionSig = domainSign(
      buildSessionAuthorizationPayload({
        sessionRole: "gaspar", adapter: "test-adapter", runtime: "opencode",
        scopeModule: null, scopeWp: null, ttlSeconds: 3600, nonce: sessionNonce,
        authority: "PO", rationale: "test", timestamp: sessionTimestamp,
      }),
      signingKey
    );
    const opened = core.openSession(
      { role: "gaspar", adapter: "test-adapter", runtime: "opencode", ttlSeconds: 3600 },
      { poAuthorization: { nonce: sessionNonce, authority: "PO", rationale: "test", timestamp: sessionTimestamp, signature: sessionSig } }
    );
    expect(opened.ok).toBe(true);
    gasparSession = { id: opened.value!.id, token: opened.value!.token };
    gasparToken = tokenString(gasparSession);
    writeFileSync(hostTokenPath(), gasparToken, { mode: 0o600 });
    askMode = "allow";
    askCalls.length = 0;
  });

  afterEach(() => {
    for (const key of Object.keys(savedEnv)) {
      if (savedEnv[key] === undefined) delete process.env[key];
      else process.env[key] = savedEnv[key];
    }
    for (const key of ["CHRONO_BIN", "CHRONO_KEY_HELPER"]) {
      if (!(key in savedEnv)) delete process.env[key];
    }
    try {
      rmSync(hostTokenPath(), { force: true });
    } catch {
      // best-effort
    }
    restoreTty();
    core.close();
    rmSync(tempDir, { recursive: true, force: true });
  });

  it("tool canonicalizer signs exactly what the Core verifies", () => {
    const payload = {
      action: "planning-approval",
      scope_artifact_id: "REQ-0001",
      scope_revision: `sha256:${"a".repeat(64)}`,
      authority: "PO",
      rationale: "accept",
      timestamp: FIXED_TIME,
      security_implications: "none",
    };
    // The generated tool module signs with the same canonical bytes.
    expect(canonicalizeJson(payload)).toBe(canonicalize(payload));
    expect(approvalChallenge("TICKET-0007")).toBe("approve-TICKET-0007");
  });

  it("keychain identifiers match the CLI keystore (no drift)", () => {
    expect(PO_KEY_SERVICE).toBe("chrono-po-signing-key");
    expect(PO_KEY_ACCOUNT).toBe("po");
  });

  it("agent definition instructs native tools, never shell planning", async () => {
    const gaspar = buildOpenCodeAgentDefinition("gaspar");
    for (const snippet of ["chrono_artifact_propose", "chrono_approval_request", "question", "chrono_artifact_status", "chrono_approval_confirm"]) {
      expect(gaspar).toContain(snippet);
    }
    expect(gaspar).toContain("Never run shell approval commands");
    expect(gaspar).toContain("`chrono approval-record`");
    expect(gaspar).toContain("never paste `--session-token`");
    expect(gaspar).toContain("execution grants are reserved");
    // No --body-file instruction remains: bodies travel inline.
    expect(gaspar).not.toContain("--body-file");
  });

  it("full conversational flow: native tools, question, signed approval, plan, no restart", async () => {
    const hooks = await hooksFor(root);
    await hooks.message({ sessionID: sessionKey });
    // Gaspar creates SPEC/ADR/security drafts through NATIVE tools.
    const call = async (name: string, args: Record<string, unknown>): Promise<string> => {
      const fn = tools[name] as { execute: (a: unknown, c: unknown) => Promise<string> };
      return fn.execute(args, toolContext());
    };
    const spec = JSON.parse(await call("artifact_propose", { kind: "spec", id: "SP-0001", title: "Tasks", body: "Task contract." })) as {
      id: string;
      revision: string;
    };
    await call("artifact_propose", { kind: "adr", id: "ADR-0001", title: "SQLite", body: "SQLite decision." });
    await call("artifact_propose", { kind: "security-profile", id: "SEC-0001", title: "Threats", body: "Boundaries and controls." });
    expect(existsSync(join(root, ".chrono", "specs", "SP-0001.md"))).toBe(true);
    // Ticket plus native question carrying the exact canonical line.
    const requested = JSON.parse(await call("approval_request", {
      action: "planning-approval", scope: "SP-0001", revision: spec.revision,
      rationale: "accept", securityImplications: "none",
    })) as { ticketId: string; challenge: string };
    expect(requested.challenge).toBe(approvalChallenge(requested.ticketId));
    await hooks.after(
      { tool: "question", sessionID: sessionKey, callID: "call-1", args: questionArgs(`CHRONO approval ${requested.challenge} :: planning-approval SP-0001 @${spec.revision} :: accept`) },
      { title: "answer", output: `Approve ${requested.challenge} — yes, ship it`, metadata: {} }
    );
    // The question hook only audits; the confirm tool records.
    expect(evidenceText()).toContain("approval-question-observed");
    expect(core.hasValidApproval("SP-0001", spec.revision, "planning-approval")).toBe(false);
    const receipt = JSON.parse(await call("approval_confirm", { ticket: requested.ticketId })) as { ok: boolean; approvalId: string };
    expect(receipt.ok).toBe(true);
    // The native ask boundary saw the exact ticket scope exactly once.
    expect(askCalls).toHaveLength(1);
    expect(askCalls[0]).toMatchObject({ permission: "chrono.approval", patterns: [requested.ticketId] });
    expect(core.hasValidApproval("SP-0001", spec.revision, "planning-approval")).toBe(true);
    const recorded = core.listApprovals().find((a) => a.scopeArtifactId === "SP-0001");
    expect(recorded?.signature.length).toBeGreaterThan(10);
    expect(evidenceText()).not.toContain(signingKey.slice(0, 20));
    expect(evidenceText()).not.toContain(gasparToken);
    await expect(hooks.message({ sessionID: sessionKey })).resolves.toBeUndefined();
    // Same governed path continues: Module and Work Package plans.
    const mod = JSON.parse(await call("artifact_propose", {
      kind: "module", id: "MOD-0001", title: "M", body: "Plan.", references: ["SP-0001"],
    })) as { ok: boolean };
    expect(mod.ok).toBe(true);
    const wp = JSON.parse(await call("artifact_propose", {
      kind: "workpackage", id: "WP-0001", title: "W", body: "Plan.", references: ["MOD-0001"],
    })) as { ok: boolean };
    expect(wp.ok).toBe(true);
  });

  it("model-only approval, replay, stale, cancellation, and forgery all deny", async () => {
    const hooks = await hooksFor(root);
    await hooks.message({ sessionID: sessionKey });
    const call = async (name: string, args: Record<string, unknown>): Promise<string> => {
      const fn = tools[name] as { execute: (a: unknown, c: unknown) => Promise<string> };
      return fn.execute(args, toolContext());
    };
    const spec = JSON.parse(await call("artifact_propose", { kind: "spec", id: "SP-0001", title: "Tasks", body: "Task contract." })) as {
      revision: string;
    };
    // Chat-only "approval": no tool event fires, so nothing records.
    await expect(hooks.message({ sessionID: sessionKey })).resolves.toBeUndefined();
    expect(core.hasValidApproval("SP-0001", spec.revision, "planning-approval")).toBe(false);
    // Real ticket, then cancellation at the native boundary.
    const first = JSON.parse(await call("approval_request", {
      action: "planning-approval", scope: "SP-0001", revision: spec.revision, rationale: "accept", securityImplications: "none",
    })) as { ticketId: string; challenge: string };
    askMode = "deny";
    await expect(call("approval_confirm", { ticket: first.ticketId })).rejects.toThrow(/declined or cancelled/);
    askMode = "allow";
    expect(core.hasValidApproval("SP-0001", spec.revision, "planning-approval")).toBe(false);
    // Forged confirmation for an unknown ticket.
    await expect(call("approval_confirm", { ticket: "TICKET-9999" })).rejects.toThrow();
    // Malformed ticket id denies before any Core contact.
    await expect(call("approval_confirm", { ticket: "nope" })).rejects.toThrow(/malformed/);
    // Genuine approval, then replay of the same ticket denies.
    const receipt = JSON.parse(await call("approval_confirm", { ticket: first.ticketId })) as { ok: boolean };
    expect(receipt.ok).toBe(true);
    const countAfterFirst = core.listApprovals().length;
    await expect(call("approval_confirm", { ticket: first.ticketId })).rejects.toThrow();
    expect(core.listApprovals()).toHaveLength(countAfterFirst);
    // Stale: revise after requesting, then confirm the old ticket.
    const req2 = JSON.parse(await call("artifact_propose", { kind: "requirement", id: "REQ-0001", title: "R", body: "One." })) as {
      revision: string;
    };
    const ticket = JSON.parse(await call("approval_request", {
      action: "planning-approval", scope: "REQ-0001", revision: req2.revision, rationale: "accept", securityImplications: "none",
    })) as { ticketId: string };
    const revised = JSON.parse(await call("artifact_revise", { id: "REQ-0001", title: "R2", body: "Changed." })) as { revision: string };
    await expect(call("approval_confirm", { ticket: ticket.ticketId })).rejects.toThrow();
    expect(core.hasValidApproval("REQ-0001", revised.revision, "planning-approval")).toBe(false);
  });

  it("auto mode fails the ceremony closed with audit evidence", async () => {
    const call = async (name: string, args: Record<string, unknown>): Promise<string> => {
      const fn = tools[name] as { execute: (a: unknown, c: unknown) => Promise<string> };
      return fn.execute(args, toolContext());
    };
    const spec = JSON.parse(await call("artifact_propose", { kind: "spec", id: "SP-0001", title: "Tasks", body: "Task contract." })) as {
      revision: string;
    };
    const requested = JSON.parse(await call("approval_request", {
      action: "planning-approval", scope: "SP-0001", revision: spec.revision, rationale: "accept", securityImplications: "none",
    })) as { ticketId: string };
    process.argv.push("--auto");
    try {
      await expect(call("approval_confirm", { ticket: requested.ticketId })).rejects.toThrow(/auto-approve/);
    } finally {
      process.argv.pop();
    }
    expect(core.hasValidApproval("SP-0001", spec.revision, "planning-approval")).toBe(false);
  });

  it("missing ask boundary fails loudly, never silently", async () => {
    const fn = tools["approval_confirm"] as { execute: (a: unknown, c: unknown) => Promise<string> };
    const ctx = toolContext() as Record<string, unknown>;
    delete ctx["ask"];
    const spec = JSON.parse(
      await (tools["artifact_propose"] as { execute: (a: unknown, c: unknown) => Promise<string> }).execute(
        { kind: "spec", id: "SP-0001", title: "S", body: "Body." },
        toolContext()
      )
    ) as { revision: string };
    const requested = JSON.parse(
      await (tools["approval_request"] as { execute: (a: unknown, c: unknown) => Promise<string> }).execute(
        { action: "planning-approval", scope: "SP-0001", revision: spec.revision, rationale: "r", securityImplications: "s" },
        toolContext()
      )
    ) as { ticketId: string };
    await expect(fn.execute({ ticket: requested.ticketId }, ctx)).rejects.toThrow(/ask boundary is unavailable/);
    expect(core.hasValidApproval("SP-0001", spec.revision, "planning-approval")).toBe(false);
  });

  it("no product code is writable before implementation dispatch", async () => {
    const hooks = await hooksFor(root);
    await hooks.message({ sessionID: sessionKey });
    const gate = async (tool: string, args: unknown): Promise<void> => {
      await hooks.before({ tool, sessionID: sessionKey, callID: `call-${tool}` }, { args });
    };
    // The native surface exposes planning tools only: no write/edit/bash.
    expect(Object.keys(tools).join(" ")).not.toMatch(/write|edit|bash|shell/);
    await expect(gate("write", { filePath: "src/app.ts", content: "x" })).rejects.toThrow();
    await expect(gate("edit", { filePath: "src/app.ts", oldText: "a", newText: "b" })).rejects.toThrow();
    await expect(gate("bash", { command: "npm run build" })).rejects.toThrow();
    expect(existsSync(join(root, "src/app.ts"))).toBe(false);
  });
});
