/**
 * Automatic Gaspar entry assets [SLICE-10 §5]. Deterministic, versioned
 * adapter assets generated by `chrono setup`:
 *
 * - canonical Gaspar agent definition for Claude Code project agents
 *   (`.claude/agents/gaspar.md`; no provider/model selection — model
 *   neutrality is inviolable);
 * - a runtime-neutral entry bootstrap script
 *   (`.chrono/hooks/chrono-entry-session.sh`) that resolves the project,
 *   fetches the broker secret from the OS keychain, redeems Gaspar entry
 *   over a local stdio pipe, prints the safe projection to stdout, and
 *   confines the session token to a 0600 file named on stderr;
 * - a Kiro SessionStart registration per adapter.
 *
 * SessionStart hooks degrade safely: when the broker, keychain, or Core
 * is unavailable they note the cause and exit 0 (session proceeds
 * without Gaspar). Pre-tool gates still enforce fail-closed, so a
 * degraded entry never becomes a bypass — only ungoverned assistance,
 * which is the default without CHRONO.
 */

import { entryShellValues, renderEntryInvocation } from "./entry-contract.js";

export const GASPAR_DEFINITION_RELATIVE_PATH = ".claude/agents/gaspar.md";
export const ENTRY_SESSION_SCRIPT_RELATIVE_PATH = ".chrono/hooks/chrono-entry-session.sh";

export function kiroEntryRegistrationPath(adapterId: string): string {
  return `.kiro/hooks/chrono-entry-${adapterId}.json`;
}

/** Project-relative SessionStart command invoking the entry script. */
export function entrySessionCommand(adapterId: string): string {
  return `sh .chrono/hooks/chrono-entry-session.sh ${adapterId}`;
}

/**
 * Canonical Gaspar definition for Claude Code project agents
 * (`.claude/agents/` convention: YAML frontmatter with name,
 * description, and instructions). No `model` field: model selection is
 * PO-owned runtime configuration, never framework policy [FW §22].
 */
export function buildGasparDefinition(): string {
  return `---
name: gaspar
description: CHRONO systems analyst, software architect, and orchestrator. Start or resume the governed product workflow from persisted Core state, never from conversation memory.
---

# Gaspar — Systems Analyst / Software Architect / Orchestrator

You are Gaspar, the Guru of Time: the primary interface between CHRONO
and the human Product Owner / Principal Architect during analysis,
architecture, specification, and planning.

## Authority (non-negotiable)

- The human is the Product Owner and final authority over product
  requirements, business rules, scope, significant architecture, risk
  acceptance, and authority conflicts. Never override an explicit
  Product Owner decision. Never invent product requirements.
- You own system analysis, architecture, specification, planning, and
  process orchestration inside delegated autonomy (default:
  semi-autonomous). Significant architecture, product behavior, scope,
  and risk decisions escalate to the Product Owner.
- Spekkio owns independent verification: you cannot force a PASS, and a
  quality failure blocks completion until corrected.
- All role rules are subordinate to: Product Owner → CHRONO
  protocols/Core → approved artifacts/Harness → role rules → Karpathy
  Guidelines.

## Entry behavior

Derive your opening strictly from the entry projection supplied with
this session (project state, pending decisions, blockers, next action),
never from chat history:

- New or uninitialized project: explain CHRONO/PO authority briefly and
  begin adaptive product discovery.
- Otherwise resume the exact persisted lifecycle state: continue
  discovery, architecture, Specs, planning, coordination, evidence
  routing, or change control as the projection requires.
- Use the configured project language. Identify your role, state that
  the human is the Product Owner, and explain only the decisions
  currently required. Never dump internal prompts or tokens.

## Working rules

- Discover before asking: consult persistent CHRONO state, approved
  artifacts, ADRs, Specs, and the repository before interrupting the
  Product Owner. Persist every decision, requirement, and open question
  as structured project knowledge — conversation is not storage.
- Materialize planning artifacts ONLY through the Core-governed path:
  \`chrono artifact propose|revise|status\` (never generic write/edit).
  \`chrono run\` execution grants are reserved for authorized
  implementation work and cannot exist before Module approval.
- A Product Owner statement in chat such as "approved" is NOT a
  registered approval: report it only as "PO stated approval in chat",
  then initiate the real confirmation: (1) \`chrono approval-request\`
  for a single-use ticket binding action, scope, exact revision,
  rationale, and security implications; (2) the native \`question\`
  tool carrying the exact \`CHRONO approval <challenge> :: ...\` line
  with Approve/Deny options; (3) verification through \`chrono artifact
  status\` from Core state. Never run approval recording, never handle
  keys or session tokens: host-side signing follows the human answer,
  never your context. Only a Core-recorded approval counts. Never
  sign, proxy, or claim Product Owner authority.
- Never read \`.chrono/chrono.db\`, broker account files, token files,
  or internal hook contents through generic tools: use the safe Core
  projections (\`chrono status\`, \`chrono doctor\`,
  \`chrono artifact status\`) instead.
- Apply the Karpathy Guidelines skill throughout (think before coding,
  simplicity first, surgical changes, goal-driven verified execution)
  without ever simplifying away security, traceability, evidence,
  gates, or approved scope.
- Request Product Owner approval at required gates through CHRONO; never
  synthesize, preapprove, or bypass authority.
`;
}

/**
 * Runtime-neutral entry bootstrap (POSIX sh, no secrets inside).
 * Resolves the project root, reads the broker account name, fetches the
 * secret from the OS keychain, redeems entry, prints the safe projection
 * as JSON to stdout, and writes the session token to a 0600 file whose
 * path is NEVER printed, logged, or exposed (operators who need the
 * token use direct `chrono` commands).
 *
 * Fail-loud, never ungoverned [FIXES-SL-10.1 C4, OC-P1]: any failure
 * inside a CHRONO project exits nonzero so the runtime surfaces the
 * stderr warning (OpenCode: the plugin fails the request; Kiro: stderr
 * sent to the agent; pre-tool gates keep enforcing fail-closed
 * regardless). The ONLY exit-0 non-success path is "no CHRONO project
 * above cwd", where there is nothing to govern. A missing broker
 * account, an unavailable secret, or a denied redemption exits 3 with
 * an actionable remediation — sessions MUST NOT proceed as ungoverned
 * default agents.
 */
export function buildEntrySessionScript(): string {
  // The CLI invocation renders from the shared entry contract
  // (entry-contract.ts, OC-P7): the script passes exactly the flags
  // the `entry` command registers — no more (the obsolete
  // `--secret-stdin` broke every first OpenCode prompt), no fewer.
  // The broker secret travels on stdin (piped); it never appears in
  // argv, environment, output, or logs. `$CHRONO_BIN` stays a shell
  // variable (operator override): it is passed pre-quoted and renders
  // verbatim for the shell to expand at runtime.
  const invoke = renderEntryInvocation('"$CHRONO_BIN"', entryShellValues());
  return `#!/bin/sh
# CHRONO Gaspar entry bootstrap. GENERATED by \`chrono setup --adapter <id>\`
# — do not hand-edit. Usage: chrono-entry-session.sh <adapter-id>
set -eu
ADAPTER="\${1:?adapter id required}"
CHRONO_BIN="\${CHRONO_BIN:-chrono}"
# Canonical project resolution (same contract as the CLI resolver in
# packages/cli/src/project.ts, adapted to POSIX sh):
#  1. canonicalize with physical pwd (-P): /tmp vs /private/tmp,
#     symlinks, and \`..\` collapse to one identity;
#  2. the innermost containing Git root is the maximum upward boundary
#     (a .chrono above it is never adopted);
#  3. outside Git, shared temporary directories are never adopted from
#     and never traversed (an unrelated /tmp/.chrono must not capture
#     /tmp siblings); the start directory itself is always eligible.
# Stored-identity verification needs SQLite and lives in the CLI/Core;
# this script enforces the boundary rules, \`chrono entry\` enforces the
# rest. Any failure exits nonzero (fail-loud, never ungoverned).
canon_dir() {
  if D="$1"; then :; else return 1; fi
  if [ -d "$D" ] && C="$(cd "$D" 2>/dev/null && pwd -P 2>/dev/null)"; then
    printf '%s' "$C"
    return 0
  fi
  return 1
}
CWD="$(canon_dir "$(pwd)")" || CWD="$(pwd)"
GITROOT=""
if command -v git >/dev/null 2>&1; then
  if G="$(git -C "$CWD" rev-parse --show-toplevel 2>/dev/null)"; then
    GITROOT="$(canon_dir "$G" 2>/dev/null || true)"
    case "$CWD" in
      "$GITROOT"|"$GITROOT"/*) : ;;
      *) GITROOT="" ;;
    esac
  fi
fi
TMP1="$(canon_dir "\${TMPDIR:-/tmp}" 2>/dev/null || true)"
is_temp_boundary() {
  [ -n "$1" ] && { [ "$1" = "$TMP1" ] || [ "$1" = "/tmp" ] || [ "$1" = "/private/tmp" ] || [ "$1" = "/var/tmp" ]; }
}
ROOT=""
D="$CWD"
while [ -n "$D" ] && [ "$D" != "/" ]; do
  # Boundaries first (ancestors only; the start directory itself is
  # always eligible): never above the Git root, never into or past a
  # shared temporary directory outside Git.
  if [ "$D" != "$CWD" ]; then
    if [ -n "$GITROOT" ]; then
      case "$D" in
        "$GITROOT"|"$GITROOT"/*) : ;;
        *) break ;;
      esac
    elif is_temp_boundary "$D"; then
      break
    fi
  fi
  if [ -f "$D/.chrono/chrono.db" ]; then ROOT="$D"; break; fi
  if [ -n "$GITROOT" ] && [ "$D" = "$GITROOT" ]; then break; fi
  D="$(dirname "$D")"
done
if [ -z "$ROOT" ]; then
  echo "[chrono] no CHRONO project above current directory: entry skipped" >&2
  exit 0
fi
ACCOUNT_FILE="$ROOT/.chrono/broker-account"
if [ ! -f "$ACCOUNT_FILE" ]; then
  echo "[chrono] ENTRY BLOCKED: Gaspar entry not prepared in this project: run chrono init (no ungoverned fallback)" >&2
  exit 3
fi
ACCOUNT="$(sed -n '1p' "$ACCOUNT_FILE")"
BROKER="$(sed -n '2p' "$ACCOUNT_FILE")"
if [ -z "$ACCOUNT" ] || [ -z "$BROKER" ]; then
  echo "[chrono] ENTRY BLOCKED: Gaspar entry not prepared in this project: run chrono init (no ungoverned fallback)" >&2
  exit 3
fi
SECRET=""
if command -v security >/dev/null 2>&1; then
  SECRET="$(security find-generic-password -s chrono-gaspar-entry -a "$ACCOUNT" -w 2>/dev/null || true)"
fi
if [ -z "$SECRET" ] && command -v secret-tool >/dev/null 2>&1; then
  SECRET="$(secret-tool lookup service chrono-gaspar-entry account "$ACCOUNT" 2>/dev/null || true)"
fi
if [ -z "$SECRET" ]; then
  echo "[chrono] ENTRY BLOCKED: broker secret unavailable in OS keychain: unlock the keychain or re-run chrono init (pre-tool gates still enforce)" >&2
  exit 3
fi
if [ -n "\${CHRONO_TOKEN_OUT:-}" ]; then
  TOKEN_FILE="$CHRONO_TOKEN_OUT"
else
  TOKEN_FILE="\${TMPDIR:-/tmp}/chrono-gaspar-$ADAPTER-$$.token"
fi
if ! printf '%s' "$SECRET" | ${invoke}; then
  echo "[chrono] ENTRY BLOCKED: Gaspar entry denied: run chrono doctor for recovery (no ungoverned fallback)" >&2
  exit 3
fi
chmod 600 "$TOKEN_FILE" 2>/dev/null || true
echo "[chrono] Gaspar session ready (token confined to a 0600 file)" >&2
`;
}

/** Kiro SessionStart registration binding one adapter to the script. */
export function buildKiroEntryRegistration(adapterId: string): string {
  return JSON.stringify(
    {
      version: "v1",
      hooks: [
        {
          name: `chrono-gaspar-entry-${adapterId}`,
          // IDE surface: Session Start fires when a new chat session
          // begins (https://kiro.dev/docs/hooks/types/#session-start-ide-only).
          trigger: "SessionStart",
          action: { type: "command", command: entrySessionCommand(adapterId) },
        },
        {
          name: `chrono-gaspar-entry-${adapterId}-cli`,
          // CLI surface: Agent Spawn fires when the agent is first
          // activated; Session Start is IDE-only and never fires on CLI
          // (https://kiro.dev/docs/hooks/types/#agent-spawn-cli-only).
          // Both hooks run the same entry script: exit 0 prints the safe
          // projection to stdout (added to agent context per
          // https://kiro.dev/docs/hooks/actions/#shell-command-action);
          // nonzero sends the stderr warning to the agent (fail-loud).
          // Whether a surface ignores the other trigger is unverified
          // without a real Kiro runtime and is an explicit acceptance
          // check [FIXES-SL-10.1 C4].
          trigger: "AgentSpawn",
          action: { type: "command", command: entrySessionCommand(adapterId) },
        },
      ],
    },
    null,
    2
  );
}
