/**
 * Automatic Gaspar entry assets [SLICE-10 §5]. Deterministic, versioned
 * adapter assets generated by `chrono setup`:
 *
 * - canonical Gaspar agent definition for Claude Code project agents
 *   (`.claude/agents/gaspar.md`; no provider/model selection — model
 *   neutrality is inviolable);
 * - a runtime-neutral entry bootstrap script
 *   (`.chrono/hooks/chrono-entry-session.sh`) that resolves the project,
 *   fetches the broker secret from the OS keychain, redeems Gaspar entry
 *   over a local stdio pipe, prints the safe projection to stdout, and
 *   confines the session token to a 0600 file named on stderr;
 * - a Kiro SessionStart registration per adapter.
 *
 * SessionStart hooks degrade safely: when the broker, keychain, or Core
 * is unavailable they note the cause and exit 0 (session proceeds
 * without Gaspar). Pre-tool gates still enforce fail-closed, so a
 * degraded entry never becomes a bypass — only ungoverned assistance,
 * which is the default without CHRONO.
 */

export const GASPAR_DEFINITION_RELATIVE_PATH = ".claude/agents/gaspar.md";
export const ENTRY_SESSION_SCRIPT_RELATIVE_PATH = ".chrono/hooks/chrono-entry-session.sh";

export function kiroEntryRegistrationPath(adapterId: string): string {
  return `.kiro/hooks/chrono-entry-${adapterId}.json`;
}

/** Project-relative SessionStart command invoking the entry script. */
export function entrySessionCommand(adapterId: string): string {
  return `sh .chrono/hooks/chrono-entry-session.sh ${adapterId}`;
}

/**
 * Canonical Gaspar definition for Claude Code project agents
 * (`.claude/agents/` convention: YAML frontmatter with name,
 * description, and instructions). No `model` field: model selection is
 * PO-owned runtime configuration, never framework policy [FW §22].
 */
export function buildGasparDefinition(): string {
  return `---
name: gaspar
description: CHRONO systems analyst, software architect, and orchestrator. Start or resume the governed product workflow from persisted Core state, never from conversation memory.
---

# Gaspar — Systems Analyst / Software Architect / Orchestrator

You are Gaspar, the Guru of Time: the primary interface between CHRONO
and the human Product Owner / Principal Architect during analysis,
architecture, specification, and planning.

## Authority (non-negotiable)

- The human is the Product Owner and final authority over product
  requirements, business rules, scope, significant architecture, risk
  acceptance, and authority conflicts. Never override an explicit
  Product Owner decision. Never invent product requirements.
- You own system analysis, architecture, specification, planning, and
  process orchestration inside delegated autonomy (default:
  semi-autonomous). Significant architecture, product behavior, scope,
  and risk decisions escalate to the Product Owner.
- Spekkio owns independent verification: you cannot force a PASS, and a
  quality failure blocks completion until corrected.
- All role rules are subordinate to: Product Owner → CHRONO
  protocols/Core → approved artifacts/Harness → role rules → Karpathy
  Guidelines.

## Entry behavior

Derive your opening strictly from the entry projection supplied with
this session (project state, pending decisions, blockers, next action),
never from chat history:

- New or uninitialized project: explain CHRONO/PO authority briefly and
  begin adaptive product discovery.
- Otherwise resume the exact persisted lifecycle state: continue
  discovery, architecture, Specs, planning, coordination, evidence
  routing, or change control as the projection requires.
- Use the configured project language. Identify your role, state that
  the human is the Product Owner, and explain only the decisions
  currently required. Never dump internal prompts or tokens.

## Working rules

- Discover before asking: consult persistent CHRONO state, approved
  artifacts, ADRs, Specs, and the repository before interrupting the
  Product Owner. Persist every decision, requirement, and open question
  as structured project knowledge — conversation is not storage.
- Apply the Karpathy Guidelines skill throughout (think before coding,
  simplicity first, surgical changes, goal-driven verified execution)
  without ever simplifying away security, traceability, evidence,
  gates, or approved scope.
- Request Product Owner approval at required gates through CHRONO; never
  synthesize, preapprove, or bypass authority.
`;
}

/**
 * Runtime-neutral entry bootstrap (POSIX sh, no secrets inside).
 * Resolves the project root, reads the broker account name, fetches the
 * secret from the OS keychain, redeems entry, prints the safe projection
 * as JSON to stdout, and writes the session token to a 0600 file whose
 * path is NEVER printed, logged, or exposed (operators who need the
 * token use direct `chrono` commands).
 *
 * Fail-loud, never ungoverned [FIXES-SL-10.1 C4, OC-P1]: any failure
 * inside a CHRONO project exits nonzero so the runtime surfaces the
 * stderr warning (OpenCode: the plugin fails the request; Kiro: stderr
 * sent to the agent; pre-tool gates keep enforcing fail-closed
 * regardless). The ONLY exit-0 non-success path is "no CHRONO project
 * above cwd", where there is nothing to govern. A missing broker
 * account, an unavailable secret, or a denied redemption exits 3 with
 * an actionable remediation — sessions MUST NOT proceed as ungoverned
 * default agents.
 */
export function buildEntrySessionScript(): string {
  return `#!/bin/sh
# CHRONO Gaspar entry bootstrap. GENERATED by \`chrono setup --adapter <id>\`
# — do not hand-edit. Usage: chrono-entry-session.sh <adapter-id>
set -eu
ADAPTER="\${1:?adapter id required}"
CHRONO_BIN="\${CHRONO_BIN:-chrono}"
ROOT=""
D="$(pwd)"
while [ "$D" != "/" ]; do
  if [ -f "$D/.chrono/chrono.db" ]; then ROOT="$D"; break; fi
  D="$(dirname "$D")"
done
if [ -z "$ROOT" ]; then
  echo "[chrono] no CHRONO project above current directory: entry skipped" >&2
  exit 0
fi
ACCOUNT_FILE="$ROOT/.chrono/broker-account"
if [ ! -f "$ACCOUNT_FILE" ]; then
  echo "[chrono] ENTRY BLOCKED: Gaspar entry not prepared in this project: run chrono init (no ungoverned fallback)" >&2
  exit 3
fi
ACCOUNT="$(sed -n '1p' "$ACCOUNT_FILE")"
BROKER="$(sed -n '2p' "$ACCOUNT_FILE")"
if [ -z "$ACCOUNT" ] || [ -z "$BROKER" ]; then
  echo "[chrono] ENTRY BLOCKED: Gaspar entry not prepared in this project: run chrono init (no ungoverned fallback)" >&2
  exit 3
fi
SECRET=""
if command -v security >/dev/null 2>&1; then
  SECRET="$(security find-generic-password -s chrono-gaspar-entry -a "$ACCOUNT" -w 2>/dev/null || true)"
fi
if [ -z "$SECRET" ] && command -v secret-tool >/dev/null 2>&1; then
  SECRET="$(secret-tool lookup service chrono-gaspar-entry account "$ACCOUNT" 2>/dev/null || true)"
fi
if [ -z "$SECRET" ]; then
  echo "[chrono] ENTRY BLOCKED: broker secret unavailable in OS keychain: unlock the keychain or re-run chrono init (pre-tool gates still enforce)" >&2
  exit 3
fi
TOKEN_FILE="\${TMPDIR:-/tmp}/chrono-gaspar-$ADAPTER-$$.token"
if ! printf '%s' "$SECRET" | "$CHRONO_BIN" entry --adapter "$ADAPTER" --broker "$BROKER" --secret-stdin --token-out "$TOKEN_FILE" --path "$ROOT" --json; then
  echo "[chrono] ENTRY BLOCKED: Gaspar entry denied: run chrono doctor for recovery (no ungoverned fallback)" >&2
  exit 3
fi
chmod 600 "$TOKEN_FILE" 2>/dev/null || true
echo "[chrono] Gaspar session ready (token confined to a 0600 file)" >&2
`;
}

/** Kiro SessionStart registration binding one adapter to the script. */
export function buildKiroEntryRegistration(adapterId: string): string {
  return JSON.stringify(
    {
      version: "v1",
      hooks: [
        {
          name: `chrono-gaspar-entry-${adapterId}`,
          // IDE surface: Session Start fires when a new chat session
          // begins (https://kiro.dev/docs/hooks/types/#session-start-ide-only).
          trigger: "SessionStart",
          action: { type: "command", command: entrySessionCommand(adapterId) },
        },
        {
          name: `chrono-gaspar-entry-${adapterId}-cli`,
          // CLI surface: Agent Spawn fires when the agent is first
          // activated; Session Start is IDE-only and never fires on CLI
          // (https://kiro.dev/docs/hooks/types/#agent-spawn-cli-only).
          // Both hooks run the same entry script: exit 0 prints the safe
          // projection to stdout (added to agent context per
          // https://kiro.dev/docs/hooks/actions/#shell-command-action);
          // nonzero sends the stderr warning to the agent (fail-loud).
          // Whether a surface ignores the other trigger is unverified
          // without a real Kiro runtime and is an explicit acceptance
          // check [FIXES-SL-10.1 C4].
          trigger: "AgentSpawn",
          action: { type: "command", command: entrySessionCommand(adapterId) },
        },
      ],
    },
    null,
    2
  );
}
