/**
 * Kiro pre-tool enforcement hook, generated deterministically
 * (Slice 9 §9.5, [RUNTIME §5]). `chrono setup` writes these exact bytes
 * to `<project>/.chrono/hooks/chrono-kiro-gate.js`; the content never
 * embeds machine-specific paths, so identical inputs always produce
 * identical bytes.
 *
 * Native contract: the Kiro adapter registers this script as a blocking
 * `PreToolUse` interceptor. It receives a JSON payload on stdin
 * (`{ tool_name, ... }`). Exit 0 allows the tool; any nonzero exit
 * blocks it with the stderr reason sent to the agent (this script uses
 * exit 2 for denials). Any other failure blocks (fail-closed).
 * Shell-command action semantics: https://kiro.dev/docs/hooks/actions/#shell-command-action.
 *
 * Slice 9 §9.5: every Kiro tool capable of filesystem, process, network,
 * package, Git, credential, deployment, destructive, or
 * production-impacting effects is gated through `chrono gate execution`.
 * Read-only tools pass without dispatch scope. Unknown tools — including
 * future built-ins, `mcp_*`, and custom tools — are denied until
 * classified in a reviewed Core policy release (deny-by-default).
 * The Core remains the authority; this hook only shapes the intake.
 */

export const KIRO_HOOK_RELATIVE_PATH = ".chrono/hooks/chrono-kiro-gate.js";
export const KIRO_HOOK_REGISTRATION_RELATIVE_PATH = ".kiro/hooks/chrono-gate.json";

/**
 * Kiro canonical CLI tool names, grounded in the vendor reference
 * (https://kiro.dev/docs/reference/built-in-tools/, fetched 2026-09-11;
 * trigger/action semantics at https://kiro.dev/docs/hooks/,
 * https://kiro.dev/docs/hooks/types/, https://kiro.dev/docs/hooks/actions/).
 * Matching is case-insensitive (the script lowercases before lookup).
 * Anything not listed here — future built-ins, `mcp_*`, custom tools,
 * undocumented names — is denied until classified in a reviewed Core
 * policy release (deny-by-default). In particular `ls`, `todowrite`,
 * `task`, `edit`, `deploy`, and `package` are NOT documented Kiro CLI
 * tools and MUST NOT be allow-listed as read-only; `webfetch` and
 * `websearch` are NOT real tool names (the documented names are
 * `web_fetch` / `web_search`) and are denied as unknown.
 */
const KIRO_READ_TOOLS = [
  "glob",
  "grep",
  "read",
  "fs_read",
  "fsread",
  "code",
  "introspect",
  "tool_search",
];
const KIRO_MUTATE_TOOLS = [
  "write",
  "fs_write",
  "fswrite",
  "shell",
  "execute_bash",
  "execute_cmd",
  "aws",
  "use_aws",
  "web_search",
  "web_fetch",
  "delegate",
  "subagent",
  "use_subagent",
  "goal",
  "knowledge",
  "session",
  "report",
  "todo",
  "todo-list",
  "deploy",
  "edit",
  "multiedit",
  "package",
  "task",
];

/**
 * CHRONO-owned Kiro hook registration. Kiro loads every
 * `.kiro/hooks/*.json` file automatically; this file registers the gate
 * script for `PreToolUse` with an always-match matcher so the script
 * itself performs Core-owned classification (deny-by-default). The
 * command is project-relative: Kiro executes hook commands with the
 * project root as the working directory.
 */
export function buildKiroHookRegistration(): string {
  return JSON.stringify(
    {
      version: "v1",
      hooks: [
        {
          name: "chrono-gate",
          trigger: "PreToolUse",
          matcher: ".*",
          action: { type: "command", command: "node .chrono/hooks/chrono-kiro-gate.js" },
        },
      ],
    },
    null,
    2
  );
}

export function buildKiroHook(): string {
  return `#!/usr/bin/env node
/**
 * CHRONO pre-tool enforcement for Kiro. GENERATED by
 * \`chrono setup --adapter <id>\` — do not hand-edit.
 *
 * Input: PreToolUse JSON on stdin ({ tool_name, ... }).
 * Exit 0 allows; exit 2 blocks with the stderr reason.
 *
 * Enforcement contract (explicit environment, never invented identity):
 * - Outside a CHRONO project (no .chrono/chrono.db under cwd): allow (0).
 * - Inside a CHRONO project: read-only tools allow without scope;
 *   mutable tools require CHRONO_GATE_MODULE (+ optional CHRONO_GATE_WP),
 *   CHRONO_GATE_AS, CHRONO_GATE_ROLE, CHRONO_SESSION_TOKEN and a live
 *   \`chrono gate execution\` AUTHORIZED verdict; unknown tools deny.
 */
import { execFileSync } from "node:child_process";
import { existsSync } from "node:fs";
import { join } from "node:path";

const READ_TOOLS = new Set(${JSON.stringify(KIRO_READ_TOOLS)});
const MUTATE_TOOLS = new Set(${JSON.stringify(KIRO_MUTATE_TOOLS)});
function readEnv(name) {
  const value = process.env[name];
  return value === undefined || value === "" ? null : value;
}

function deny(reason) {
  process.stderr.write("[chrono] " + reason + "\\n");
  process.exit(2);
}

function readStdin() {
  return new Promise((resolve) => {
    let data = "";
    process.stdin.setEncoding("utf8");
    process.stdin.on("data", (chunk) => {
      data += chunk;
    });
    process.stdin.on("end", () => resolve(data));
    if (process.stdin.isTTY) {
      resolve("");
    }
  });
}

async function main() {
  const root = process.cwd();
  if (!existsSync(join(root, ".chrono", "chrono.db"))) {
    process.exit(0);
  }
  const raw = await readStdin();
  let tool = "";
  try {
    const parsed = raw.trim().length > 0 ? JSON.parse(raw) : {};
    // Kiro matches tool names case-insensitively across versions
    // (2.x Write|Edit, 3.x write|read); normalize before lookup.
    // Unknown tools stay unknown and are denied below.
    tool = typeof parsed.tool_name === "string" ? parsed.tool_name.toLowerCase() : "";
  } catch {
    deny("TOOL_DENIED: PreToolUse payload is not parseable JSON.");
  }
  if (READ_TOOLS.has(tool)) {
    process.exit(0);
  }
  if (!MUTATE_TOOLS.has(tool)) {
    deny("TOOL_DENIED: tool '" + tool + "' is not classified by CHRONO tool policy v1: deny-by-default until reviewed.");
  }
  const module = readEnv("CHRONO_GATE_MODULE");
  if (module === null) {
    deny("CHRONO project without dispatch context: export CHRONO_GATE_MODULE (and CHRONO_GATE_WP when scoped) or dispatch via 'chrono run'.");
  }
  const token = readEnv("CHRONO_SESSION_TOKEN");
  if (token === null) {
    deny("Dispatch context without a session: export CHRONO_SESSION_TOKEN from an authorized session.");
  }
  const as = readEnv("CHRONO_GATE_AS");
  const role = readEnv("CHRONO_GATE_ROLE");
  if (as === null || role === null) {
    deny("Export CHRONO_GATE_AS and CHRONO_GATE_ROLE for the dispatch.");
  }
  const chronoBin = readEnv("CHRONO_BIN") ?? "chrono";
  const args = [
    "gate", "execution", "--module", module,
    "--as", as, "--role", role,
    "--session-token", token,
    "--requester-token", readEnv("CHRONO_REQUESTER_TOKEN") ?? token,
    "--path", root, "--json",
  ];
  const wp = readEnv("CHRONO_GATE_WP");
  if (wp !== null) {
    args.push("--wp", wp);
  }
  let out;
  try {
    out = execFileSync(chronoBin, args, { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
  } catch (e) {
    const stdout = e && e.stdout ? String(e.stdout) : "";
    if (stdout.trim().length > 0) {
      out = stdout;
    } else {
      deny("gate unreachable: " + (e instanceof Error ? e.message : String(e)));
    }
  }
  let verdict;
  try {
    verdict = JSON.parse(out);
  } catch {
    deny("gate returned non-JSON output.");
  }
  if (verdict && verdict.result === "AUTHORIZED") {
    process.exit(0);
  }
  const code = verdict && typeof verdict.code === "string" ? verdict.code : "DENIED";
  const reason = verdict && typeof verdict.reason === "string" ? verdict.reason : "denied";
  deny(code + ": " + reason);
}

await main();
`;
}
