/**
 * Kiro pre-tool enforcement hook, generated deterministically
 * (Slice 9 §9.5, [RUNTIME §5]). `chrono setup` writes these exact bytes
 * to `<project>/.chrono/hooks/chrono-kiro-gate.js`; the content never
 * embeds machine-specific paths, so identical inputs always produce
 * identical bytes.
 *
 * Native contract: the Kiro adapter registers this script as a blocking
 * `PreToolUse` interceptor. It receives a JSON payload on stdin
 * (`{ tool_name, ... }`). Exit 0 allows the tool; any nonzero exit
 * blocks it with the stderr reason sent to the agent (this script uses
 * exit 2 for denials). Any other failure blocks (fail-closed).
 * Shell-command action semantics: https://kiro.dev/docs/hooks/actions/#shell-command-action.
 *
 * Slice 9 §9.5: every Kiro tool capable of filesystem, process, network,
 * package, Git, credential, deployment, destructive, or
 * production-impacting effects is gated through `chrono gate execution`.
 * Read-only tools pass without dispatch scope. Unknown tools — including
 * future built-ins, `mcp_*`, and custom tools — are denied until
 * classified in a reviewed Core policy release (deny-by-default).
 * The Core remains the authority; this hook only shapes the intake.
 */

export const KIRO_HOOK_RELATIVE_PATH = ".chrono/hooks/chrono-kiro-gate.js";
export const KIRO_HOOK_REGISTRATION_RELATIVE_PATH = ".kiro/hooks/chrono-gate.json";

/**
 * Kiro canonical CLI tool names, grounded in the vendor reference
 * (https://kiro.dev/docs/reference/built-in-tools/, fetched 2026-09-11;
 * trigger/action semantics at https://kiro.dev/docs/hooks/,
 * https://kiro.dev/docs/hooks/types/, https://kiro.dev/docs/hooks/actions/).
 * Matching is case-insensitive (the script lowercases before lookup).
 * Anything not listed here — future built-ins, `mcp_*`, custom tools,
 * undocumented names — is denied until classified in a reviewed Core
 * policy release (deny-by-default). In particular `ls`, `todowrite`,
 * `task`, `edit`, `deploy`, and `package` are NOT documented Kiro CLI
 * tools and MUST NOT be allow-listed as read-only; `webfetch` and
 * `websearch` are NOT real tool names (the documented names are
 * `web_fetch` / `web_search`) and are denied as unknown.
 */
const KIRO_READ_TOOLS = [
  "glob",
  "grep",
  "read",
  "fs_read",
  "fsread",
  "code",
  "introspect",
  "tool_search",
];
const KIRO_MUTATE_TOOLS = [
  "write",
  "fs_write",
  "fswrite",
  "shell",
  "execute_bash",
  "execute_cmd",
  "aws",
  "use_aws",
  "web_search",
  "web_fetch",
  "delegate",
  "subagent",
  "use_subagent",
  "goal",
  "knowledge",
  "session",
  "report",
  "todo",
  "todo-list",
  "deploy",
  "edit",
  "multiedit",
  "package",
  "task",
];

/**
 * CHRONO-owned Kiro hook registration. Kiro loads every
 * `.kiro/hooks/*.json` file automatically; this file registers the gate
 * script for `PreToolUse` with an always-match matcher so the script
 * itself performs Core-owned classification (deny-by-default). The
 * command is project-relative: Kiro executes hook commands with the
 * project root as the working directory.
 */
export function buildKiroHookRegistration(): string {
  return JSON.stringify(
    {
      version: "v1",
      hooks: [
        {
          name: "chrono-gate",
          trigger: "PreToolUse",
          matcher: ".*",
          action: { type: "command", command: "node .chrono/hooks/chrono-kiro-gate.js" },
        },
      ],
    },
    null,
    2
  );
}

export function buildKiroHook(): string {
  return `#!/usr/bin/env node
/**
 * CHRONO pre-tool enforcement for Kiro. GENERATED by
 * \`chrono setup --adapter <id>\` — do not hand-edit.
 *
 * Input: PreToolUse JSON on stdin ({ tool_name, ... }).
 * Exit 0 allows; exit 2 blocks with the stderr reason.
 *
 * Enforcement contract (explicit environment, never invented identity):
 * - Outside a CHRONO project (no .chrono/chrono.db under cwd): allow (0).
 * - Inside a CHRONO project: read-only tools allow without scope, except
 *   reads referencing internal/security state (denied: use projections);
 *   shell invocations that are EXACTLY a governed planning operation
 *   (chrono artifact propose|revise|status, chrono doctor/status/validate)
 *   allow with no dispatch scope — the planning CLI enforces the
 *   Gaspar/PO session itself (OC-P11);
 *   every other mutable tool requires CHRONO_GATE_MODULE (+ optional
 *   CHRONO_GATE_WP), CHRONO_GATE_AS, CHRONO_GATE_ROLE,
 *   CHRONO_SESSION_TOKEN and a live
 *   \`chrono gate execution\` AUTHORIZED verdict; unknown tools deny.
 */
import { execFileSync } from "node:child_process";
import { existsSync, realpathSync } from "node:fs";
import { dirname, join, sep } from "node:path";

const READ_TOOLS = new Set(${JSON.stringify(KIRO_READ_TOOLS)});
const MUTATE_TOOLS = new Set(${JSON.stringify(KIRO_MUTATE_TOOLS)});

// Canonical project resolution (same contract as the CLI resolver in
// packages/cli/src/project.ts): canonicalize once; the innermost Git
// root is the maximum upward boundary; outside Git, shared temporary
// directories are never adopted from and never traversed. Cached per
// process (bounded) because this script runs per tool call.
// Stored-identity verification needs SQLite and lives in the CLI/Core;
// this script enforces the boundary rules. Deliberately uncached: a
// project initialized after load must be enforced immediately.
function canonicalDir(path) {
  try {
    return realpathSync(path);
  } catch {
    return null;
  }
}
function tempBoundaryDirs() {
  const out = [];
  const seen = new Set();
  const candidates = [
    process.env["TMPDIR"] ?? null,
    process.env["TMP"] ?? null,
    process.env["TEMP"] ?? null,
    "/tmp",
    "/private/tmp",
    "/var/tmp",
  ];
  for (const candidate of candidates) {
    if (candidate === null || candidate.length === 0) {
      continue;
    }
    try {
      const canonical = realpathSync(candidate);
      if (!seen.has(canonical)) {
        seen.add(canonical);
        out.push(canonical);
      }
    } catch {
      // Absent temp dir: nothing to guard.
    }
  }
  return out;
}
function gitRootOf(canonicalStart) {
  try {
    const raw = execFileSync("git", ["-C", canonicalStart, "rev-parse", "--show-toplevel"], {
      encoding: "utf8",
      timeout: 15000,
      stdio: ["ignore", "pipe", "pipe"],
    });
    return realpathSync(String(raw).trim());
  } catch {
    return null;
  }
}
function findChronoRootUncached(canonicalStart) {
  const gitRoot = gitRootOf(canonicalStart);
  const withinOrEqual = (dir, boundary) => dir === boundary || dir.startsWith(boundary + sep);
  const tempBoundaries = gitRoot === null ? tempBoundaryDirs() : [];
  let current = canonicalStart;
  for (let depth = 0; depth < 64; depth++) {
    if (gitRoot !== null && !withinOrEqual(current, gitRoot)) {
      return null;
    }
    if (gitRoot === null && current !== canonicalStart && tempBoundaries.includes(current)) {
      return null;
    }
    try {
      if (existsSync(join(current, ".chrono", "chrono.db"))) {
        return current;
      }
    } catch {
      return null;
    }
    if (gitRoot !== null && current === gitRoot) {
      return null;
    }
    const parent = dirname(current);
    if (parent === current) {
      return null;
    }
    current = parent;
  }
  return null;
}
function resolveChronoRoot(startDir) {
  const canonicalStart = canonicalDir(startDir || process.cwd());
  if (canonicalStart === null) {
    return null;
  }
  return findChronoRootUncached(canonicalStart);
}
function readEnv(name) {
  const value = process.env[name];
  return value === undefined || value === "" ? null : value;
}

function deny(reason) {
  process.stderr.write("[chrono] " + reason + "\\n");
  process.exit(2);
}

function readStdin() {
  return new Promise((resolve) => {
    let data = "";
    process.stdin.setEncoding("utf8");
    process.stdin.on("data", (chunk) => {
      data += chunk;
    });
    process.stdin.on("end", () => resolve(data));
    if (process.stdin.isTTY) {
      resolve("");
    }
  });
}

async function main() {
  const root = resolveChronoRoot(process.cwd());
  if (root === null) {
    process.exit(0);
  }
  const raw = await readStdin();
  let tool = "";
  try {
    const parsed = raw.trim().length > 0 ? JSON.parse(raw) : {};
    // Kiro matches tool names case-insensitively across versions
    // (2.x Write|Edit, 3.x write|read); normalize before lookup.
    // Unknown tools stay unknown and are denied below.
    tool = typeof parsed.tool_name === "string" ? parsed.tool_name.toLowerCase() : "";
  } catch {
    deny("TOOL_DENIED: PreToolUse payload is not parseable JSON.");
  }
  let payloadText = "";
  try {
    const parsed = JSON.parse(raw);
    payloadText = JSON.stringify(parsed.tool_input ?? "");
  } catch {
    payloadText = "";
  }
  // OC-P11 req 16: generic reads never serve internal/security state.
  const FORBIDDEN = [".chrono/chrono.db", ".chrono/broker-account", ".chrono/hooks/", "chrono-gaspar-", ".token", "CHRONO_SESSION_TOKEN"];
  if (READ_TOOLS.has(tool)) {
    if (FORBIDDEN.some((needle) => payloadText.includes(needle))) {
      deny("SECRET_DETECTED: this read references CHRONO internal or security state: use chrono doctor or chrono artifact status projections instead.");
    }
    process.exit(0);
  }
  if (!MUTATE_TOOLS.has(tool)) {
    deny("TOOL_DENIED: tool '" + tool + "' is not classified by CHRONO tool policy v2: deny-by-default until reviewed.");
  }
  // OC-P11 planning path: a shell invocation that is EXACTLY a governed
  // planning operation (no chaining/substitution) needs no dispatch
  // scope; the planning CLI enforces the Gaspar/PO session itself.
  if (tool === "shell" || tool === "execute_bash" || tool === "execute_cmd") {
    const PLANNING = ["chrono artifact propose", "chrono artifact revise", "chrono artifact status", "chrono discovery record", "chrono plan status", "chrono status", "chrono validate", "chrono doctor"];
    let command = null;
    try {
      const parsed = JSON.parse(raw);
      const input = parsed.tool_input;
      if (typeof input === "string") {
        command = input;
      } else if (input !== null && typeof input === "object") {
        for (const key of ["command", "cmd", "input", "script"]) {
          if (typeof input[key] === "string" && input[key].trim().length > 0) {
            command = input[key];
            break;
          }
        }
      }
    } catch {
      command = null;
    }
    if (typeof command === "string") {
      const normalized = command.trim().replace(/\\s+/g, " ");
      if (!/[;|&$\\\`]/.test(normalized)) {
        const candidate = normalized.replace(/^([\\w\\-./\\\\:]+\\/)?chrono(\\.exe|\\.cmd|\\.bat)? /, "chrono ");
        if (PLANNING.some((prefix) => candidate === prefix || candidate.startsWith(prefix + " "))) {
          process.exit(0);
        }
      }
    }
  }
  const module = readEnv("CHRONO_GATE_MODULE");
  if (module === null) {
    deny("CHRONO project without dispatch context: export CHRONO_GATE_MODULE (and CHRONO_GATE_WP when scoped) or dispatch via 'chrono run'.");
  }
  const token = readEnv("CHRONO_SESSION_TOKEN");
  if (token === null) {
    deny("Dispatch context without a session: export CHRONO_SESSION_TOKEN from an authorized session.");
  }
  const as = readEnv("CHRONO_GATE_AS");
  const role = readEnv("CHRONO_GATE_ROLE");
  if (as === null || role === null) {
    deny("Export CHRONO_GATE_AS and CHRONO_GATE_ROLE for the dispatch.");
  }
  const chronoBin = readEnv("CHRONO_BIN") ?? "chrono";
  const args = [
    "gate", "execution", "--module", module,
    "--as", as, "--role", role,
    "--session-token", token,
    "--requester-token", readEnv("CHRONO_REQUESTER_TOKEN") ?? token,
    "--path", root, "--json",
  ];
  const wp = readEnv("CHRONO_GATE_WP");
  if (wp !== null) {
    args.push("--wp", wp);
  }
  let out;
  try {
    out = execFileSync(chronoBin, args, { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
  } catch (e) {
    const stdout = e && e.stdout ? String(e.stdout) : "";
    if (stdout.trim().length > 0) {
      out = stdout;
    } else {
      deny("gate unreachable: " + (e instanceof Error ? e.message : String(e)));
    }
  }
  let verdict;
  try {
    verdict = JSON.parse(out);
  } catch {
    deny("gate returned non-JSON output.");
  }
  if (verdict && verdict.result === "AUTHORIZED") {
    process.exit(0);
  }
  const code = verdict && typeof verdict.code === "string" ? verdict.code : "DENIED";
  const reason = verdict && typeof verdict.reason === "string" ? verdict.reason : "denied";
  deny(code + ": " + reason);
}

await main();
`;
}
