/**
 * Vertical lifecycle black-box (CORE_FIX §6): one deterministic test
 * crossing the complete runtime lifecycle through the REAL packed
 * artifacts — freshly packed tarballs installed without workspace
 * links, the real generated OpenCode plugin bytes, agent definitions,
 * and native tools, exact 1.18.30 hook/event/tool shapes, real Core
 * with SQLite migrations and state.
 *
 * Initialization (project init through the packed binary; PO key,
 * architecture, planning, approvals, attestations, adapter through
 * public Core methods with real signatures) precedes the vertical.
 * Everything after initialization — dispatch, delegation, claim,
 * mutation gating, evidence, reviews, FAIL, correction, PASS,
 * completion, next-scope selection, restart, profiles, escalation,
 * negatives — runs through the installed binary and generated bytes
 * in fresh processes. Deterministic model/child responses are
 * fixtures (OpenCode session keys, delegation choices); no Core
 * decision is faked and no database row is touched directly.
 *
 * Full run only under CHRONO_BLACKBOX=1 (`npm run test:blackbox`):
 * pack/install alone takes minutes. Without the flag this file
 * asserts the gate is off and proves nothing.
 */
import { describe, it, expect, beforeAll, afterAll } from "vitest";
import {
  chmodSync,
  existsSync,
  mkdtempSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  realpathSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname, delimiter } from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { createHash, randomBytes } from "node:crypto";
import {
  buildApprovalPayload,
  buildEnrollmentChallenge,
  buildEnrollmentPayload,
  buildPolicyPayload,
  buildSessionAuthorizationPayload,
  computeRevisionHash,
  convertSkillSource,
  fingerprintPublicKey,
  generateApprovalKeyPair,
  managedAssetInventory,
  signApprovalPayload,
  skillGeneratedHashes,
  skillVendorPath,
  RTK_UPSTREAM,
  SKILL_RELEASE,
  SKILL_RUNTIME_PATHS,
  SKILL_UPSTREAM,
} from "@chrono/domain";
import { ChronoCore } from "@chrono/core";
import { FIXTURE_SKILL_MD } from "../test/test-skill-fixture.js";

const BLACKBOX = process.env["CHRONO_BLACKBOX"] === "1";
const REPO_ROOT = fileURLToPath(new URL("../../..", import.meta.url));

if (!BLACKBOX) {
  describe("Lifecycle vertical black-box (CORE_FIX §6)", () => {
    it("runs on demand via npm run test:blackbox (CHRONO_BLACKBOX=1)", () => {
      expect(BLACKBOX).toBe(false);
    });
  });
} else {
  const BOX_TIMEOUT = 600000;

  interface BlackBox {
    readonly dir: string;
    readonly chronoBin: string;
    readonly fakeBin: string;
    readonly project: string;
    readonly tmp: string;
  }

  let box: BlackBox | null = null;

  function sh(
    cmd: string,
    args: string[],
    options: { cwd?: string; env?: NodeJS.ProcessEnv; timeout?: number }
  ): { exit: number; stdout: string; stderr: string } {
    try {
      const stdout = execFileSync(cmd, args, {
        encoding: "utf8",
        cwd: options.cwd,
        env: options.env,
        timeout: options.timeout ?? 120000,
        stdio: ["ignore", "pipe", "pipe"],
        windowsHide: true,
      });
      return { exit: 0, stdout, stderr: "" };
    } catch (e) {
      const err = e as { status?: unknown; stdout?: unknown; stderr?: unknown };
      return {
        exit: typeof err.status === "number" ? err.status : 1,
        stdout: typeof err.stdout === "string" ? err.stdout : "",
        stderr: typeof err.stderr === "string" ? err.stderr : "",
      };
    }
  }

  function writeExe(path: string, content: string): void {
    writeFileSync(path, content, "utf8");
    chmodSync(path, 0o755);
  }

  /** Child env: fake fixtures first on PATH, disposable keystore + npm cache, no pilot leakage. */
  function childEnv(b: BlackBox, extra?: NodeJS.ProcessEnv): NodeJS.ProcessEnv {
    return {
      ...process.env,
      PATH: `${b.fakeBin}${delimiter}${process.env["PATH"] ?? ""}`,
      TMPDIR: b.tmp,
      npm_config_cache: join(b.tmp, "npm-cache"),
      ...(extra ?? {}),
    };
  }

  /** Run the installed binary, parse JSON stdout, fail loudly with context. */
  function chrono(b: BlackBox, args: string[], extraEnv?: NodeJS.ProcessEnv): Record<string, unknown> {
    const ran = sh(b.chronoBin, [...args, "--path", b.project, "--json"], {
      cwd: b.project,
      env: childEnv(b, extraEnv),
    });
    if (ran.exit !== 0) {
      throw new Error(`chrono ${args.join(" ")} exited ${ran.exit}: ${ran.stdout.slice(0, 2000)} ${ran.stderr.slice(0, 500)}`);
    }
    try {
      return JSON.parse(ran.stdout) as Record<string, unknown>;
    } catch {
      throw new Error(`chrono ${args.join(" ")} returned non-JSON: ${ran.stdout.slice(0, 1000)}`);
    }
  }

  /** Expect denial: nonzero exit with a JSON error carrying one of the codes. */
  function chronoDenies(b: BlackBox, args: string[], codes: string[], extraEnv?: NodeJS.ProcessEnv): string {
    const ran = sh(b.chronoBin, [...args, "--path", b.project, "--json"], {
      cwd: b.project,
      env: childEnv(b, extraEnv),
    });
    expect(ran.exit).not.toBe(0);
    const body = JSON.parse(ran.stdout) as { error?: { code?: string; message?: string } };
    const code = body.error?.code ?? "(no code)";
    expect(codes).toContain(code);
    return `${code}: ${body.error?.message ?? ""}`;
  }

  function tokenFor(b: BlackBox, sessionKey: string): string {
    // Byte-parity with the CLI host-token derivation: canonical root
    // (symlinks resolved: /tmp vs /private/tmp), sha16, box TMPDIR.
    const canonical = realpathSync(b.project);
    const hash = createHash("sha256").update(`${canonical}|${sessionKey}`, "utf8").digest("hex").slice(0, 16);
    return readFileSync(join(b.tmp, `chrono-gaspar-host-${hash}.token`), "utf8").trim();
  }

  describe("Lifecycle vertical black-box (CORE_FIX §6)", () => {
    beforeAll(() => {
      const dir = mkdtempSync(join(tmpdir(), "chrono-lifecycle-box-"));
      const tarballs = join(dir, "tarballs");
      const install = join(dir, "install");
      const fakeBin = join(dir, "fakebin");
      const project = join(dir, "project");
      const tmp = join(dir, "tmp");
      mkdirSync(tarballs, { recursive: true });
      mkdirSync(install, { recursive: true });
      mkdirSync(fakeBin, { recursive: true });
      mkdirSync(project, { recursive: true });
      mkdirSync(tmp, { recursive: true });
      mkdirSync(join(tmp, "npm-cache"), { recursive: true });
      // Isolated pack + install of the four workspace tarballs: the
      // binary under test shares no files with the workspace.
      execFileSync(
        "npm",
        ["pack", "--workspace=@chrono/domain", "--workspace=@chrono/persistence", "--workspace=@chrono/core", "--workspace=@chrono/cli", `--pack-destination=${tarballs}`],
        { cwd: REPO_ROOT, timeout: 300000, stdio: ["ignore", "pipe", "pipe"] }
      );
      writeFileSync(join(install, "package.json"), JSON.stringify({ name: "chrono-lifecycle-box", version: "1.0.0" }), "utf8");
      const packed = readdirSync(tarballs)
        .filter((name) => name.endsWith(".tgz"))
        .map((name) => join(tarballs, name));
      if (packed.length !== 4) {
        throw new Error(`black-box prerequisite: expected 4 tarballs, found ${packed.length}`);
      }
      execFileSync("npm", ["install", "--no-audit", "--no-fund", ...packed], {
        cwd: install,
        timeout: 300000,
        stdio: ["ignore", "pipe", "pipe"],
        env: { ...process.env, npm_config_cache: join(tmp, "npm-cache"), npm_config_update_notifier: "false" },
      });
      const chronoBin = join(install, "node_modules", ".bin", "chrono");
      if (!existsSync(chronoBin)) {
        throw new Error("black-box install did not produce .bin/chrono");
      }
      // Disposable keystore boundary: fake `security` backed by a
      // directory under the box tmp. The host keychain is never
      // touched; every read/write/delete crosses real process spawn
      // and file IPC.
      writeExe(
        join(fakeBin, "security"),
        [
          "#!/bin/sh",
          'STORE="${TMPDIR:-/tmp}/chrono-box-keystore"',
          'mkdir -p "$STORE" 2>/dev/null || true',
          'op=""; svc=""; acct=""; secret=""',
          "while [ $# -gt 0 ]; do",
          '  case "$1" in',
          "    find-generic-password|add-generic-password|delete-generic-password) op=\"$1\"; shift;;",
          '    -s) svc="$2"; shift 2;;',
          '    -a) acct="$2"; shift 2;;',
          '    -w) shift; if [ "$op" = "add-generic-password" ]; then secret="$1"; shift; fi;;',
          "    *) shift;;",
          "  esac",
          "done",
          'key="$(printf \'%s\' "$svc" | tr -c \'A-Za-z0-9_.-\' \'_\')__$(printf \'%s\' "$acct" | tr -c \'A-Za-z0-9_.-\' \'_\')"',
          'f="$STORE/$key"',
          'case "$op" in',
          "  find-generic-password)",
          '    if [ -f "$f" ]; then cat "$f"; exit 0;',
          '    else echo "security: SecKeychainSearchCopyNext: could not be found" >&2; exit 44; fi;;',
          "  add-generic-password)",
          '    printf \'%s\' "$secret" > "$f"; chmod 600 "$f"; exit 0;;',
          "  delete-generic-password)",
          '    if [ -f "$f" ]; then rm -f "$f"; exit 0;',
          '    else echo "security: SecKeychainSearchCopyNext: could not be found" >&2; exit 44; fi;;',
          '  *) echo "black-box security: unsupported $op" >&2; exit 1;;',
          "esac",
          "",
        ].join("\n")
      );
      // Fixture RTK: genuine process boundary, deterministic behavior.
      writeExe(
        join(fakeBin, "rtk"),
        [
          "#!/bin/sh",
          'if [ "$1" = "--version" ]; then echo "fixture-rtk 1.0.0-test"; exit 0; fi',
          'if [ "$1" = "gain" ]; then echo "Token Killer savings dashboard (black-box)"; exit 0; fi',
          'echo "fixture-rtk 1.0.0-test: $*"',
          "exit 0",
          "",
        ].join("\n")
      );
      box = { dir, chronoBin, fakeBin, project, tmp };
    }, BOX_TIMEOUT);

    afterAll(() => {
      if (box !== null) {
        rmSync(box.dir, { recursive: true, force: true });
        box = null;
      }
    });

    function requireBox(): BlackBox {
      if (box === null) {
        throw new Error("black-box fixture not initialized");
      }
      return box;
    }

    interface Keys {
      readonly gasparToken: string;
      readonly gasparSession: { id: string; token: string };
      readonly poToken: string;
      readonly signingKey: string;
    }

    /**
     * Initialize one project: packed-binary init (proves the packed
     * artifact reaches the human gate and resumes), then the human
     * steps — PO enrollment, architecture, planning, approvals,
     * attestations, adapter, routing proof — through public Core
     * methods with real signatures. Everything after this function
     * runs through the installed binary in fresh processes.
     *
     * CF-12 migrated mode: stops at the exact pilot shape — MOD-0002
     * DRAFT with current planning-approval and module-approval, WP-0001
     * PLANNED, no transition enacted past registration. Activation
     * itself is proven through the `module-activate` binary below,
     * never by initializing into a convenient APPROVED state.
     */
    function fakeTty(): () => void {
      const stdinDesc = Object.getOwnPropertyDescriptor(process.stdin, "isTTY");
      const stdoutDesc = Object.getOwnPropertyDescriptor(process.stdout, "isTTY");
      Object.defineProperty(process.stdin, "isTTY", { value: true, configurable: true });
      Object.defineProperty(process.stdout, "isTTY", { value: true, configurable: true });
      return () => {
        if (stdinDesc !== undefined) {
          Object.defineProperty(process.stdin, "isTTY", stdinDesc);
        } else {
          delete (process.stdin as { isTTY?: boolean }).isTTY;
        }
        if (stdoutDesc !== undefined) {
          Object.defineProperty(process.stdout, "isTTY", stdoutDesc);
        } else {
          delete (process.stdout as { isTTY?: boolean }).isTTY;
        }
      };
    }

    function setupProject(specPurpose: string, mode: "approved" | "migrated" = "approved"): Keys {
      const b = requireBox();
      for (const entry of readdirSync(b.project)) {
        rmSync(join(b.project, entry), { recursive: true, force: true });
      }
      // Fixture adapter entrypoint: the registered binary the grant binds.
      writeExe(join(b.project, "fixture-runtime.sh"), ["#!/bin/sh", "echo fixture-ok", ""].join("\n"));
      // The human steps below run in-process with real signatures; the
      // TTY fixture stands in for the Product Owner's live terminal
      // (the packed binary provably refuses these without one).
      const restoreTty = fakeTty();
      const init = sh(b.chronoBin, ["init", "--runtime", "opencode", "--yes", "--yes-files", "--yes-keychain", "--path", b.project, "--json"], {
        cwd: b.project,
        env: childEnv(b),
      });
      // Packed init reaches the human gate and stops there: nonzero
      // until READY, with the resumable step named.
      expect(init.exit).toBe(1);
      const initBody = JSON.parse(init.stdout) as { ok: boolean; step: string; resume: string };
      expect(initBody.ok).toBe(false);
      expect(initBody.step).toBe("PO_ENROLLED");
      expect(initBody.resume).toContain("Re-run chrono init");
      const core = new ChronoCore({ projectPath: b.project, runtime: "opencode" });
      try {
        const pair = generateApprovalKeyPair();
        const nonce = randomBytes(16).toString("hex");
        const fingerprint = fingerprintPublicKey(pair.publicKeyPem);
        const confirmation = buildEnrollmentChallenge("default", fingerprint, nonce);
        const timestamp = new Date().toISOString();
        const signature = signApprovalPayload(
          buildEnrollmentPayload({ projectId: "default", fingerprint, timestamp, nonce, authority: "PO", rationale: "box", confirmation }),
          pair.privateKeyPem
        );
        const enrolled = core.enrollPo({ publicKeyPem: pair.publicKeyPem, nonce, timestamp, rationale: "box", confirmation, signature });
        expect(enrolled.ok).toBe(true);
        const signingKey = pair.privateKeyPem;
        const openPrivileged = (role: "gaspar" | "PO"): { id: string; token: string } => {
          const n = randomBytes(16).toString("hex");
          const ts = "2026-09-11T00:00:00.000Z";
          const sig = signApprovalPayload(
            buildSessionAuthorizationPayload({
              sessionRole: role, adapter: "fixture", runtime: "opencode",
              scopeModule: null, scopeWp: null, ttlSeconds: 86400, nonce: n,
              authority: "PO", rationale: "box", timestamp: ts,
            }),
            signingKey
          );
          const res = core.openSession(
            { role, adapter: "fixture", runtime: "opencode", ttlSeconds: 86400 },
            { poAuthorization: { nonce: n, authority: "PO", rationale: "box", timestamp: ts, signature: sig } }
          );
          if (!res.ok) {
            throw new Error(`box setup session failed: ${JSON.stringify(res)}`);
          }
          return { id: res.value!.id, token: res.value!.token };
        };
        const approve = (action: string, scopeId: string, scopeRev: string): void => {
          const sig = signApprovalPayload(
            buildApprovalPayload({
              action, scopeArtifactId: scopeId, scopeRevision: scopeRev,
              authority: "PO", rationale: "box approval", timestamp: "2026-09-14T00:00:00.000Z",
            }),
            signingKey
          );
          const res = core.recordApproval({
            action, scopeArtifactId: scopeId, scopeRevision: scopeRev,
            authority: "PO", rationale: "box approval", timestamp: "2026-09-14T00:00:00.000Z", signature: sig,
          });
          if (!res.ok) {
            throw new Error(`box setup approval failed: ${JSON.stringify(res)}`);
          }
        };
        const gasparSession = openPrivileged("gaspar");
        const gaspar = { actor: "gaspar", session: gasparSession };
        const po = { actor: "PO", session: openPrivileged("PO") };
        const proposed = core.proposeArchitecture({ title: "Box" }, gaspar);
        if (!proposed.ok) {
          throw new Error(`box arch failed: ${JSON.stringify(proposed)}`);
        }
        if (!core.submitArchitectureForReview(gaspar).ok) {
          throw new Error("box arch review failed");
        }
        approve("architecture-security", "ARCH", proposed.value!);
        if (!core.approveArchitecture(gaspar).ok) {
          throw new Error("box arch approve failed");
        }
        const spec = { id: "SP-0001", title: "Box", purpose: specPurpose, inScope: ["a"], acceptanceCriteria: ["ac1"] };
        if (!core.registerSpec("SP-0001", "DRAFT", spec, gaspar).ok) {
          throw new Error("box spec failed");
        }
        if (!core.transitionState("SP-0001", "SpecSubmittedForReview", gaspar).ok) {
          throw new Error("box spec submit failed");
        }
        const specRev = core.getArtifact("SP-0001").revision;
        approve("architecture-security", "SP-0001", specRev);
        if (!core.recordHarness(specRev, `sha256:${"a".repeat(64)}`, "# h", gaspar).ok) {
          throw new Error("box harness failed");
        }
        if (!core.transitionState("SP-0001", "SpecApprovedReady", gaspar).ok) {
          throw new Error("box spec ready failed");
        }
        if (!core.registerModule("MOD-0002", "DRAFT", { id: "MOD-0002", name: "Box", purpose: "Box", specs: ["SP-0001"] }, gaspar).ok) {
          throw new Error("box module failed");
        }
        if (!core.registerWorkPackage("WP-0001", "PLANNED", { id: "WP-0001", name: "One", module: "MOD-0002", dependsOn: [] }, gaspar).ok) {
          throw new Error("box wp1 failed");
        }
        if (mode === "migrated") {
          // Pilot shape: both approvals current on the DRAFT revision,
          // zero transitions enacted. The binary proves activation.
          const draftRev = core.getArtifact("MOD-0002").revision;
          approve("planning-approval", "MOD-0002", draftRev);
          approve("module-approval", "MOD-0002", draftRev);
        } else {
          if (!core.registerWorkPackage("WP-0002", "PLANNED", { id: "WP-0002", name: "Two", module: "MOD-0002", dependsOn: ["WP-0001"] }, gaspar).ok) {
            throw new Error("box wp2 failed");
          }
          if (!core.transitionState("MOD-0002", "ModulePlanned", gaspar).ok) {
            throw new Error("box module planned failed");
          }
          approve("module-approval", "MOD-0002", core.getArtifact("MOD-0002").revision);
          if (!core.transitionState("MOD-0002", "ModuleApproved", gaspar).ok) {
            throw new Error("box module approved failed");
          }
          if (!core.transitionState("WP-0001", "WorkPackageAuthorized", gaspar).ok) {
            throw new Error("box wp1 auth failed");
          }
        }
        // WP-0002 depends on WP-0001: it authorizes later, through the
        // native tool, once the predecessor completes (sequencing
        // proof inside each vertical below).
        if (!core.recordSecurityProfile({ title: "Box", threats: [] }, gaspar).ok) {
          throw new Error("box security profile failed");
        }
        const rtkBin = join(b.fakeBin, "rtk");
        if (!core.recordRtkAttestation(gaspar, {
          binaryPath: rtkBin, binaryIdentity: "rtk-test", version: "1.0.0-test",
          provenance: RTK_UPSTREAM, integrationMode: "test", routingTestPassed: true,
          routingTestLog: "box", gained: true, savingsEvidence: null, ttlSeconds: 86400,
        }).ok) {
          throw new Error("box rtk failed");
        }
        const vendorTarget = join(b.project, skillVendorPath(SKILL_RELEASE.pinnedCommit));
        mkdirSync(dirname(vendorTarget), { recursive: true });
        writeFileSync(vendorTarget, FIXTURE_SKILL_MD, "utf8");
        for (const runtime of ["claude", "opencode", "kiro"] as const) {
          const target = join(b.project, SKILL_RUNTIME_PATHS[runtime]);
          mkdirSync(dirname(target), { recursive: true });
          writeFileSync(target, FIXTURE_SKILL_MD, "utf8");
        }
        if (!core.recordSkillAttestation(gaspar, {
          upstream: SKILL_UPSTREAM, pinnedCommit: SKILL_RELEASE.pinnedCommit,
          sourceHash: SKILL_RELEASE.sourceHash,
          generatedHashes: skillGeneratedHashes(convertSkillSource(FIXTURE_SKILL_MD)),
          converterVersion: SKILL_RELEASE.converterVersion, licenseStatus: "MIT", attribution: "MIT",
          runtimeIdentity: "test", agentIdentity: "test", discoveryResult: "found",
          permissionResult: "granted", activationTestPassed: true, ttlSeconds: 86400,
        }).ok) {
          throw new Error("box skill failed");
        }
        if (!core.registerAdapter({ id: "fixture", name: "Fixture", entrypoint: join(b.project, "fixture-runtime.sh"), conformanceProof: ["fixture --version"] }, po).ok) {
          throw new Error("box adapter failed");
        }
        const registrationHash = core.adapterRegistrationHash("fixture");
        approve("adapter-registration", "fixture", registrationHash);
        // Adapter approval id: latest approval for the registration hash.
        const adapterApproval = core.listApprovals().find((a) => a.scopeArtifactId === "fixture");
        if (adapterApproval === undefined) {
          throw new Error("box adapter approval missing");
        }
        if (!core.approveAdapter("fixture", adapterApproval.id, po).ok) {
          throw new Error("box adapter approve failed");
        }
        const recordedProof = core.recordRoutingProof(gaspar, {
          adapterId: "fixture", binaryPath: rtkBin, version: "1.0.0-test",
          proofCommand: JSON.stringify([rtkBin, "gain"]),
          preRoutingCommand: JSON.stringify(["ls", b.project]),
          commandHash: computeRevisionHash([rtkBin, "gain"]),
          outputHash: computeRevisionHash("fixture gain ok"),
          exitStatus: 0, gainAvailable: true,
          timestamp: new Date().toISOString(), ttlSeconds: 86400,
        });
        if (!recordedProof.ok) {
          throw new Error("box routing proof failed");
        }
        for (const asset of managedAssetInventory("fixture")) {
          const target = join(b.project, asset.path);
          mkdirSync(dirname(target), { recursive: true });
          writeFileSync(target, asset.kind === "marker" ? `fixture-managed ${asset.marker ?? asset.path}\n` : `fixture-managed ${asset.path}\n`, "utf8");
        }
        if (!core.promoteRoutingProof(recordedProof.value!.id, po).ok) {
          throw new Error("box proof promote failed");
        }
        // Host entry tokens (what binary init + entry would confine;
        // the model never sees them). Canonical root: the CLI hashes
        // the realpath, so /tmp vs /private/tmp must agree.
        const canonical = realpathSync(b.project);
        const gasparHash = createHash("sha256").update(`${canonical}|gaspar-box`, "utf8").digest("hex").slice(0, 16);
        writeFileSync(join(b.tmp, `chrono-gaspar-host-${gasparHash}.token`), `${gasparSession.id}/${gasparSession.token}`, { mode: 0o600 });
        const poSession = po.session as { id: string; token: string };
        const poToken = `${poSession.id}/${poSession.token}`;
        return { gasparToken: `${gasparSession.id}/${gasparSession.token}`, gasparSession, poToken, signingKey };
      } finally {
        core.close();
        restoreTty();
      }
    }

    interface Flow {
      readonly keys: Keys;
      workerTokens: Map<string, string>;
    }

    function workerToken(b: BlackBox, workerKey: string): string {
      return tokenFor(b, workerKey);
    }

    /** Full dispatch round-trip through the installed binary: request, delegate, claim, confirm. */
    function dispatchRoundTrip(
      b: BlackBox,
      keys: Keys,
      flow: Flow,
      opts: { wp: string; kind?: string; agent: string; workerKey: string; rationale: string; profile?: string }
    ): string {
      const reqArgs = ["dispatch-request", "--module", "MOD-0002", "--wp", opts.wp, "--rationale", opts.rationale,
        "--as", "gaspar", "--session-token", keys.gasparToken, "--adapter", "fixture", "--opencode-session", "gaspar-box"];
      if (opts.kind !== undefined) {
        reqArgs.push("--kind", opts.kind);
      }
      if (opts.profile !== undefined) {
        reqArgs.push("--proposed-profile", opts.profile);
      }
      const req = chrono(b, reqArgs);
      expect(req["ok"]).toBe(true);
      const dispatchId = req["dispatchId"] as string;
      expect(typeof dispatchId).toBe("string");
      // No credential or grant material in the validation output.
      expect(JSON.stringify(req)).not.toContain(keys.gasparToken);
      expect(JSON.stringify(req)).not.toContain("GRANT-");
      const checked = chrono(b, ["dispatch-task-check", "--session", "gaspar-box", "--agent", opts.agent]);
      expect(checked["ok"]).toBe(true);
      expect(checked["dispatchId"]).toBe(dispatchId);
      const claimed = chrono(b, ["dispatch-claim", "--dispatch", dispatchId, "--agent", opts.agent, "--worker-session", opts.workerKey]);
      expect(claimed["ok"]).toBe(true);
      expect(claimed["dispatchId"]).toBe(dispatchId);
      expect(JSON.stringify(claimed)).not.toContain("token");
      flow.workerTokens.set(opts.workerKey, workerToken(b, opts.workerKey));
      const confirmed = chrono(b, ["dispatch-confirm", "--dispatch", dispatchId, "--as", "gaspar", "--session-token", keys.gasparToken]);
      expect(confirmed["ok"]).toBe(true);
      expect(confirmed["status"]).toBe("ACTIVE");
      return dispatchId;
    }

    function recordEvidence(
      b: BlackBox,
      as: string,
      token: string,
      revision: string,
      check: string
    ): string {
      const res = chrono(b, ["evidence-record", "--revision", revision, "--check", check, "--result", "pass",
        "--as", as, "--session-token", token]);
      expect(res["ok"]).toBe(true);
      return res["id"] as string;
    }

    function wpRevision(b: BlackBox, keys: Keys, wp: string): string {
      const exec = chrono(b, ["execution-status", "--wp", wp, "--as", "gaspar", "--session-token", keys.gasparToken]);
      const pkgs = exec["packages"] as Array<{ workPackageId: string; status: string; revision: string }>;
      const found = pkgs.find((p) => p.workPackageId === wp);
      if (found === undefined) {
        throw new Error(`box: package ${wp} missing from execution status`);
      }
      return found.revision;
    }

    function wpStatus(b: BlackBox, keys: Keys, wp: string): string {
      const exec = chrono(b, ["execution-status", "--wp", wp, "--as", "gaspar", "--session-token", keys.gasparToken]);
      const pkgs = exec["packages"] as Array<{ workPackageId: string; status: string; revision: string }>;
      const found = pkgs.find((p) => p.workPackageId === wp);
      if (found === undefined) {
        throw new Error(`box: package ${wp} missing from execution status`);
      }
      return found.status;
    }

    function nextAction(b: BlackBox, keys: Keys, scope: { module?: string; wp?: string }): Record<string, unknown> {
      const args = ["next-action", "--as", "gaspar", "--session-token", keys.gasparToken];
      if (scope.module !== undefined) {
        args.push("--module", scope.module);
      }
      if (scope.wp !== undefined) {
        args.push("--wp", scope.wp);
      }
      const res = chrono(b, args);
      expect(res["ok"]).toBe(true);
      return res;
    }

    /**
     * PO risk decision fixture: records a real PO-signed approval
     * through public Core methods with genuine signatures. This
     * embodies the human Product Owner step the packed binary
     * provably refuses without a live terminal — never a fake.
     */
    function poApprove(b: BlackBox, keys: Keys, action: string, scopeId: string, scopeRev: string): void {
      const restore = fakeTty();
      const core = new ChronoCore({ projectPath: b.project, runtime: "opencode" });
      try {
        const signature = signApprovalPayload(
          buildApprovalPayload({
            action, scopeArtifactId: scopeId, scopeRevision: scopeRev,
            authority: "PO", rationale: "box risk acceptance", timestamp: "2026-09-14T00:00:00.000Z",
          }),
          keys.signingKey
        );
        const res = core.recordApproval({
          action, scopeArtifactId: scopeId, scopeRevision: scopeRev,
          authority: "PO", rationale: "box risk acceptance", timestamp: "2026-09-14T00:00:00.000Z", signature,
        });
        if (!res.ok) {
          throw new Error(`box PO approval failed: ${JSON.stringify(res)}`);
        }
      } finally {
        core.close();
        restore();
      }
    }

    /**
     * Duplicate PO approval probe: re-recording the identical approval
     * payload denies with DUPLICATE_IDENTITY through the public Core
     * API with a genuine signature (the pilot's duplicate-approval
     * denial, reproduced without touching storage directly).
     */
    function poApproveDenied(b: BlackBox, keys: Keys, action: string, scopeId: string, scopeRev: string): string {
      const restore = fakeTty();
      const core = new ChronoCore({ projectPath: b.project, runtime: "opencode" });
      try {
        const signature = signApprovalPayload(
          buildApprovalPayload({
            action, scopeArtifactId: scopeId, scopeRevision: scopeRev,
            authority: "PO", rationale: "box approval", timestamp: "2026-09-14T00:00:00.000Z",
          }),
          keys.signingKey
        );
        const res = core.recordApproval({
          action, scopeArtifactId: scopeId, scopeRevision: scopeRev,
          authority: "PO", rationale: "box approval", timestamp: "2026-09-14T00:00:00.000Z", signature,
        });
        expect(res.ok).toBe(false);
        if (res.ok || res.error === undefined) {
          throw new Error("box duplicate approval unexpectedly accepted");
        }
        expect(res.error.code).toBe("DUPLICATE_IDENTITY");
        return `${res.error.code}: ${res.error.message}`;
      } finally {
        core.close();
        restore();
      }
    }

    it("standard profile: full vertical with FAIL, correction, PASS, and module completion", () => {
      const b = requireBox();
      // Clean spec content: no risk triggers, so the standard fast
      // path applies (Glenn evidence still recorded; the deterministic
      // rule, not omission, decides).
      const keys = setupProject("Implements the contracted widget behavior.");
      const flow: Flow = { keys, workerTokens: new Map() };
      const policy = chrono(b, ["policy-status"]);
      expect(policy["profile"]).toBe("standard");

      // WP-0001: implementation through first verification.
      // CF-12: the fresh AUTHORIZED package dispatches first — the
      // next action carries the accepted kind, never a guess.
      const firstAction = nextAction(b, keys, { wp: "WP-0001" });
      expect(firstAction["action"]).toBe("request-dispatch");
      expect(firstAction["kind"]).toBe("implementation");
      const impl = dispatchRoundTrip(b, keys, flow, { wp: "WP-0001", agent: "belthazar", workerKey: "box-w-impl-1", rationale: "implement WP-0001" });
      // CF-1: the per-tool gate validates the binding and mints no grant.
      const gate = chrono(b, ["gate", "execution", "--module", "MOD-0002", "--wp", "WP-0001",
        "--as", "belthazar", "--role", "belthazar", "--session-token", flow.workerTokens.get("box-w-impl-1") ?? ""]);
      expect(gate["result"]).toBe("AUTHORIZED");
      expect(gate["dispatchId"]).toBe(impl);
      expect("grantId" in gate).toBe(false);
      const rev1 = wpRevision(b, keys, "WP-0001");
      const implToken = flow.workerTokens.get("box-w-impl-1") ?? "";
      recordEvidence(b, "belthazar", implToken, rev1, "unit-impl");
      // Lucca tests beside implementation on the RUNNING scope (its
      // claim binds without re-enacting the start event).
      const test = dispatchRoundTrip(b, keys, flow, { wp: "WP-0001", kind: "test", agent: "lucca", workerKey: "box-w-test-1", rationale: "test WP-0001" });
      recordEvidence(b, "lucca", flow.workerTokens.get("box-w-test-1") ?? "", rev1, "unit");
      chrono(b, ["dispatch-release", "--dispatch", test, "--as", "lucca", "--session-token", flow.workerTokens.get("box-w-test-1") ?? ""]);
      chrono(b, ["scope-advance", "--module", "MOD-0002", "--wp", "WP-0001", "--event", "ImplementationDone",
        "--as", "belthazar", "--session-token", implToken]);
      expect(wpStatus(b, keys, "WP-0001")).toBe("IMPLEMENTED");
      chrono(b, ["scope-advance", "--module", "MOD-0002", "--wp", "WP-0001", "--event", "VerificationReady",
        "--as", "belthazar", "--session-token", implToken]);
      expect(wpStatus(b, keys, "WP-0001")).toBe("VERIFYING");
      chrono(b, ["dispatch-release", "--dispatch", impl, "--as", "belthazar", "--session-token", implToken]);
      // Glenn security review on its own dispatch.
      const assigned = chrono(b, ["review-assign", "--kind", "security-review", "--module", "MOD-0002", "--wp", "WP-0001",
        "--as", "gaspar", "--session-token", keys.gasparToken]);
      expect(assigned["ok"]).toBe(true);
      const glennReview = assigned["reviewId"] as string;
      const glenn = dispatchRoundTrip(b, keys, flow, { wp: "WP-0001", kind: "security-review", agent: "glenn", workerKey: "box-w-glenn-1", rationale: "review WP-0001" });
      recordEvidence(b, "glenn", flow.workerTokens.get("box-w-glenn-1") ?? "", rev1, "review");
      chrono(b, ["review-complete", "--review", glennReview, "--as", "glenn",
        "--session-token", flow.workerTokens.get("box-w-glenn-1") ?? ""]);
      chrono(b, ["dispatch-release", "--dispatch", glenn, "--as", "glenn", "--session-token", flow.workerTokens.get("box-w-glenn-1") ?? ""]);
      // Spekkio verification: FAIL opens the bounded loop.
      const vassigned = chrono(b, ["review-assign", "--kind", "verification", "--module", "MOD-0002", "--wp", "WP-0001",
        "--as", "gaspar", "--session-token", keys.gasparToken]);
      const spekkioReview = vassigned["reviewId"] as string;
      const spekkio = dispatchRoundTrip(b, keys, flow, { wp: "WP-0001", kind: "verification", agent: "spekkio", workerKey: "box-w-spek-1", rationale: "verify WP-0001" });
      const spekkioToken = flow.workerTokens.get("box-w-spek-1") ?? "";
      const defect = chrono(b, ["defect-record", "--classification", "IMPLEMENTATION_DEFECT", "--severity", "major",
        "--artifact", "WP-0001", "--blocking-scope", "WP-0001", "--as", "spekkio", "--session-token", spekkioToken]);
      expect(defect["ok"]).toBe(true);
      const defectId = defect["id"] as string;
      chrono(b, ["verify-record", "--module", "MOD-0002", "--verdict", "FAILED", "--reviewer", "spekkio",
        "--defects", defectId, "--wp", "WP-0001", "--as", "spekkio", "--session-token", spekkioToken]);
      chrono(b, ["scope-advance", "--module", "MOD-0002", "--wp", "WP-0001", "--event", "SpekkioFailed",
        "--as", "spekkio", "--session-token", spekkioToken]);
      expect(wpStatus(b, keys, "WP-0001")).toBe("FAILED");
      chrono(b, ["review-complete", "--review", spekkioReview, "--as", "spekkio", "--session-token", spekkioToken]);
      chrono(b, ["dispatch-release", "--dispatch", spekkio, "--as", "spekkio", "--session-token", spekkioToken]);
      // The loop owns the scope: next action routes correction first.
      const afterFail = nextAction(b, keys, { wp: "WP-0001" });
      expect(afterFail["action"]).toBe("request-correction");
      expect(String(afterFail["summary"])).toContain("belthazar");
      // Reopening the same loop denies (exactly one open loop per defect).
      chronoDenies(b, ["correction-open", "--defect", defectId, "--as", "gaspar", "--session-token", keys.gasparToken], ["DUPLICATE_IDENTITY"]);
      // Governed correction through the loop.
      const fix = dispatchRoundTrip(b, keys, flow, { wp: "WP-0001", kind: "correction", agent: "belthazar", workerKey: "box-w-fix-1", rationale: "fix the defect" });
      const fixToken = flow.workerTokens.get("box-w-fix-1") ?? "";
      expect(wpStatus(b, keys, "WP-0001")).toBe("RUNNING");
      const looped = nextAction(b, keys, { wp: "WP-0001" });
      expect(looped["action"]).toBe("correct-defect");
      recordEvidence(b, "belthazar", fixToken, rev1, "fix");
      const loopDone = chrono(b, ["correction-complete", "--loop", String(looped["summary"]).match(/'(COR-[0-9]+)'/)?.[1] ?? "",
        "--as", "belthazar", "--session-token", fixToken]);
      expect(loopDone["status"]).toBe("REVERIFY");
      expect(Number(loopDone["invalidatedEvidence"])).toBeGreaterThan(0);
      // Pre-correction proof went stale: Lucca retests the RUNNING fix
      // beside correction, then the fix advances to verification.
      const test2 = dispatchRoundTrip(b, keys, flow, { wp: "WP-0001", kind: "test", agent: "lucca", workerKey: "box-w-test-2", rationale: "retest the fix" });
      recordEvidence(b, "lucca", flow.workerTokens.get("box-w-test-2") ?? "", rev1, "unit");
      chrono(b, ["dispatch-release", "--dispatch", test2, "--as", "lucca", "--session-token", flow.workerTokens.get("box-w-test-2") ?? ""]);
      chrono(b, ["scope-advance", "--module", "MOD-0002", "--wp", "WP-0001", "--event", "ImplementationDone",
        "--as", "belthazar", "--session-token", fixToken]);
      chrono(b, ["scope-advance", "--module", "MOD-0002", "--wp", "WP-0001", "--event", "VerificationReady",
        "--as", "belthazar", "--session-token", fixToken]);
      chrono(b, ["dispatch-release", "--dispatch", fix, "--as", "belthazar", "--session-token", fixToken]);
      const greview2 = chrono(b, ["review-assign", "--kind", "security-review", "--module", "MOD-0002", "--wp", "WP-0001",
        "--as", "gaspar", "--session-token", keys.gasparToken]);
      const glenn2 = dispatchRoundTrip(b, keys, flow, { wp: "WP-0001", kind: "security-review", agent: "glenn", workerKey: "box-w-glenn-2", rationale: "re-review the fix" });
      const glenn2Token = flow.workerTokens.get("box-w-glenn-2") ?? "";
      recordEvidence(b, "glenn", glenn2Token, rev1, "review");
      chrono(b, ["review-complete", "--review", greview2["reviewId"] as string, "--as", "glenn", "--session-token", glenn2Token]);
      chrono(b, ["dispatch-release", "--dispatch", glenn2, "--as", "glenn", "--session-token", glenn2Token]);
      // Re-verification: PASS closes the loop and completes the package.
      const vassigned2 = chrono(b, ["review-assign", "--kind", "verification", "--module", "MOD-0002", "--wp", "WP-0001",
        "--as", "gaspar", "--session-token", keys.gasparToken]);
      const spekkioReview2 = vassigned2["reviewId"] as string;
      const spekkio2 = dispatchRoundTrip(b, keys, flow, { wp: "WP-0001", kind: "verification", agent: "spekkio", workerKey: "box-w-spek-2", rationale: "re-verify WP-0001" });
      const spekkioToken2 = flow.workerTokens.get("box-w-spek-2") ?? "";
      chrono(b, ["verify-record", "--module", "MOD-0002", "--verdict", "PASS", "--reviewer", "spekkio",
        "--wp", "WP-0001", "--as", "spekkio", "--session-token", spekkioToken2]);
      chrono(b, ["review-complete", "--review", spekkioReview2, "--as", "spekkio", "--session-token", spekkioToken2]);
      // The PO accepts closure: the PASS closed the loop on
      // independent re-verification, and the owner's session already
      // retired with its release. Owner-or-PO resolution holds.
      chrono(b, ["defect-resolve", "--defect", defectId, "--as", "PO", "--session-token", keys.poToken]);
      chrono(b, ["scope-advance", "--module", "MOD-0002", "--wp", "WP-0001", "--event", "SpekkioPassed",
        "--as", "spekkio", "--session-token", spekkioToken2]);
      expect(wpStatus(b, keys, "WP-0001")).toBe("COMPLETE");
      chrono(b, ["dispatch-release", "--dispatch", spekkio2, "--as", "spekkio", "--session-token", spekkioToken2]);

      // WP-0002 (depends on WP-0001): authorize through the native
      // tool now that the predecessor is COMPLETE, then happy path.
      // The clean spec fires no risk trigger, so the standard fast path
      // applies: no separate Glenn review, Lucca proof on its own
      // WP-scoped dispatch (cross-scope evidence denies).
      expect(nextAction(b, keys, { module: "MOD-0002" })["targetId"]).toBe("WP-0002");
      const wpauth = chrono(b, ["wp-authorize", "--wp", "WP-0002", "--as", "gaspar", "--session-token", keys.gasparToken]);
      expect(wpauth["ok"]).toBe(true);
      const impl2 = dispatchRoundTrip(b, keys, flow, { wp: "WP-0002", agent: "prometheus", workerKey: "box-w-impl-2", rationale: "implement WP-0002" });
      const rev2 = wpRevision(b, keys, "WP-0002");
      const impl2Token = flow.workerTokens.get("box-w-impl-2") ?? "";
      recordEvidence(b, "prometheus", impl2Token, rev2, "unit-impl");
      const test3 = dispatchRoundTrip(b, keys, flow, { wp: "WP-0002", kind: "test", agent: "lucca", workerKey: "box-w-test-3", rationale: "test WP-0002" });
      recordEvidence(b, "lucca", flow.workerTokens.get("box-w-test-3") ?? "", rev2, "unit");
      chrono(b, ["dispatch-release", "--dispatch", test3, "--as", "lucca", "--session-token", flow.workerTokens.get("box-w-test-3") ?? ""]);
      chrono(b, ["scope-advance", "--module", "MOD-0002", "--wp", "WP-0002", "--event", "ImplementationDone",
        "--as", "prometheus", "--session-token", impl2Token]);
      chrono(b, ["scope-advance", "--module", "MOD-0002", "--wp", "WP-0002", "--event", "VerificationReady",
        "--as", "prometheus", "--session-token", impl2Token]);
      chrono(b, ["dispatch-release", "--dispatch", impl2, "--as", "prometheus", "--session-token", impl2Token]);
      const vassigned3 = chrono(b, ["review-assign", "--kind", "verification", "--module", "MOD-0002", "--wp", "WP-0002",
        "--as", "gaspar", "--session-token", keys.gasparToken]);
      const spekkio3 = dispatchRoundTrip(b, keys, flow, { wp: "WP-0002", kind: "verification", agent: "spekkio", workerKey: "box-w-spek-3", rationale: "verify WP-0002" });
      const spekkioToken3 = flow.workerTokens.get("box-w-spek-3") ?? "";
      chrono(b, ["verify-record", "--module", "MOD-0002", "--verdict", "PASS", "--reviewer", "spekkio",
        "--wp", "WP-0002", "--as", "spekkio", "--session-token", spekkioToken3]);
      chrono(b, ["review-complete", "--review", vassigned3["reviewId"] as string, "--as", "spekkio", "--session-token", spekkioToken3]);
      chrono(b, ["scope-advance", "--module", "MOD-0002", "--wp", "WP-0002", "--event", "SpekkioPassed",
        "--as", "spekkio", "--session-token", spekkioToken3]);
      expect(wpStatus(b, keys, "WP-0002")).toBe("COMPLETE");
      chrono(b, ["dispatch-release", "--dispatch", spekkio3, "--as", "spekkio", "--session-token", spekkioToken3]);

      // Module completion by aggregate, then terminal confirmation.
      // The module-level Implementation Security Acceptance is the PO
      // backstop validate() requires of every COMPLETE module.
      expect(nextAction(b, keys, { module: "MOD-0002" })["action"]).toBe("complete-module");
      const modExec = chrono(b, ["execution-status", "--module", "MOD-0002", "--as", "gaspar", "--session-token", keys.gasparToken]);
      poApprove(b, keys, "implementation-security", "MOD-0002", modExec["moduleRevision"] as string);
      const done = chrono(b, ["complete-module", "--module", "MOD-0002", "--as", "gaspar", "--session-token", keys.gasparToken]);
      expect(done["state"]).toBe("COMPLETE");
      const deep = chrono(b, ["deep-check", "--as", "gaspar", "--session-token", keys.gasparToken]);
      expect(deep["blockerCount"]).toBe(0);
      expect(deep["warningCount"]).toBe(0);
      // Restart boundary: fresh processes re-read terminal state; the
      // crash sweep finds nothing to expire or revoke.
      const rec = chrono(b, ["dispatch-reconcile", "--as", "gaspar", "--session-token", keys.gasparToken]);
      expect(rec["expired"]).toEqual([]);
      expect(rec["revoked"]).toEqual([]);
      const status = chrono(b, ["status"]);
      expect(status["ok"]).toBe(true);
      const valid = chrono(b, ["validate"]);
      expect((valid as { valid?: boolean })["valid"]).toBe(true);
    }, BOX_TIMEOUT);

    it("lean profile: short path, batching, and automatic escalation on risk", () => {
      const b = requireBox();
      const keys = setupProject("Small local maintenance helper.");
      const flow: Flow = { keys, workerTokens: new Map() };
      // Lean calibration is itself a signed PO decision (standard is
      // the default; lowering to lean needs the PO signature over the
      // canonical payload with a fresh timestamp).
      const leanTimestamp = new Date().toISOString();
      const leanSignature = signApprovalPayload(
        buildPolicyPayload({ profile: "lean", rationale: "local prototype", timestamp: leanTimestamp }),
        keys.signingKey
      );
      const set = chrono(b, ["policy-set", "--profile", "lean", "--rationale", "local prototype",
        "--signature", leanSignature, "--timestamp", leanTimestamp,
        "--as", "PO", "--session-token", keys.poToken]);
      expect(set["profile"]).toBe("lean");
      // Lean short path on WP-0001: focused evidence plus the one
      // independent check, no Glenn ceremony.
      const impl = dispatchRoundTrip(b, keys, flow, { wp: "WP-0001", agent: "belthazar", workerKey: "box-l-impl", rationale: "lean implement" });
      const implToken = flow.workerTokens.get("box-l-impl") ?? "";
      const rev = wpRevision(b, keys, "WP-0001");
      recordEvidence(b, "belthazar", implToken, rev, "unit-impl");
      const test = dispatchRoundTrip(b, keys, flow, { wp: "WP-0001", kind: "test", agent: "lucca", workerKey: "box-l-test", rationale: "lean test" });
      recordEvidence(b, "lucca", flow.workerTokens.get("box-l-test") ?? "", rev, "unit");
      chrono(b, ["dispatch-release", "--dispatch", test, "--as", "lucca", "--session-token", flow.workerTokens.get("box-l-test") ?? ""]);
      chrono(b, ["scope-advance", "--module", "MOD-0002", "--wp", "WP-0001", "--event", "ImplementationDone",
        "--as", "belthazar", "--session-token", implToken]);
      chrono(b, ["scope-advance", "--module", "MOD-0002", "--wp", "WP-0001", "--event", "VerificationReady",
        "--as", "belthazar", "--session-token", implToken]);
      chrono(b, ["dispatch-release", "--dispatch", impl, "--as", "belthazar", "--session-token", implToken]);
      const vassigned = chrono(b, ["review-assign", "--kind", "verification", "--module", "MOD-0002", "--wp", "WP-0001",
        "--as", "gaspar", "--session-token", keys.gasparToken]);
      const spek = dispatchRoundTrip(b, keys, flow, { wp: "WP-0001", kind: "verification", agent: "spekkio", workerKey: "box-l-spek", rationale: "lean verify" });
      const spekToken = flow.workerTokens.get("box-l-spek") ?? "";
      chrono(b, ["verify-record", "--module", "MOD-0002", "--verdict", "PASS", "--reviewer", "spekkio",
        "--wp", "WP-0001", "--as", "spekkio", "--session-token", spekToken]);
      chrono(b, ["review-complete", "--review", vassigned["reviewId"] as string, "--as", "spekkio", "--session-token", spekToken]);
      chrono(b, ["scope-advance", "--module", "MOD-0002", "--wp", "WP-0001", "--event", "SpekkioPassed",
        "--as", "spekkio", "--session-token", spekToken]);
      expect(wpStatus(b, keys, "WP-0001")).toBe("COMPLETE");
      chrono(b, ["dispatch-release", "--dispatch", spek, "--as", "spekkio", "--session-token", spekToken]);
      // Batching: with WP-0001 done, WP-0002 readiness is reported.
      const next = nextAction(b, keys, { module: "MOD-0002" });
      expect(next["targetId"]).toBe("WP-0002");
      // Escalation is automatic and sticky, driven by content: a fresh
      // project whose spec handles secrets escalates to critical
      // regardless of the calibrated lean profile.
      const keys2 = setupProject("Rotates the database password vault.");
      const leanTimestamp2 = new Date().toISOString();
      const leanSignature2 = signApprovalPayload(
        buildPolicyPayload({ profile: "lean", rationale: "local prototype", timestamp: leanTimestamp2 }),
        keys2.signingKey
      );
      const set2 = chrono(b, ["policy-set", "--profile", "lean", "--rationale", "local prototype",
        "--signature", leanSignature2, "--timestamp", leanTimestamp2,
        "--as", "PO", "--session-token", keys2.poToken]);
      expect(set2["profile"]).toBe("lean");
      const raised = chrono(b, ["dispatch-request", "--module", "MOD-0002", "--wp", "WP-0001",
        "--rationale", "rotate the vault", "--as", "gaspar", "--session-token", keys2.gasparToken,
        "--adapter", "fixture", "--opencode-session", "gaspar-box"]);
      expect(raised["effectiveProfile"]).toBe("critical");
      expect(raised["riskTriggers"]).toContain("secrets");
      // Neither Gaspar nor a worker can lower a recorded policy: raise
      // to critical, then prove the silent downgrade back denies while
      // the PO-signed path still works.
      const up = chrono(b, ["policy-set", "--profile", "critical", "--rationale", "raise for secrets",
        "--as", "gaspar", "--session-token", keys2.gasparToken]);
      expect(up["profile"]).toBe("critical");
      chronoDenies(b, ["policy-set", "--profile", "lean", "--rationale", "downgrade attempt",
        "--as", "gaspar", "--session-token", keys2.gasparToken], ["EXECUTION_DENIED"]);
      const downTimestamp = new Date().toISOString();
      const downSignature = signApprovalPayload(
        buildPolicyPayload({ profile: "lean", rationale: "accepted residual risk", timestamp: downTimestamp }),
        keys2.signingKey
      );
      const down = chrono(b, ["policy-set", "--profile", "lean", "--rationale", "accepted residual risk",
        "--signature", downSignature, "--timestamp", downTimestamp,
        "--as", "PO", "--session-token", keys2.poToken]);
      expect(down["profile"]).toBe("lean");
      expect(down["downgraded"]).toBe(true);
      const deep = chrono(b, ["deep-check", "--as", "gaspar", "--session-token", keys2.gasparToken]);
      expect(deep["blockerCount"]).toBe(0);
    }, BOX_TIMEOUT);

    it("critical profile: explicit reviews, no batching, depth of evidence", () => {
      const b = requireBox();
      const keys = setupProject("Production payment rotation helper.");
      const flow: Flow = { keys, workerTokens: new Map() };
      const set = chrono(b, ["policy-set", "--profile", "critical", "--rationale", "production infrastructure",
        "--as", "gaspar", "--session-token", keys.gasparToken]);
      expect(set["profile"]).toBe("critical");
      const impl = dispatchRoundTrip(b, keys, flow, { wp: "WP-0001", agent: "belthazar", workerKey: "box-c-impl", rationale: "critical implement" });
      const implToken = flow.workerTokens.get("box-c-impl") ?? "";
      const rev = wpRevision(b, keys, "WP-0001");
      recordEvidence(b, "belthazar", implToken, rev, "unit-impl");
      const test = dispatchRoundTrip(b, keys, flow, { wp: "WP-0001", kind: "test", agent: "lucca", workerKey: "box-c-test", rationale: "critical test" });
      recordEvidence(b, "lucca", flow.workerTokens.get("box-c-test") ?? "", rev, "unit");
      chrono(b, ["dispatch-release", "--dispatch", test, "--as", "lucca", "--session-token", flow.workerTokens.get("box-c-test") ?? ""]);
      chrono(b, ["scope-advance", "--module", "MOD-0002", "--wp", "WP-0001", "--event", "ImplementationDone",
        "--as", "belthazar", "--session-token", implToken]);
      chrono(b, ["scope-advance", "--module", "MOD-0002", "--wp", "WP-0001", "--event", "VerificationReady",
        "--as", "belthazar", "--session-token", implToken]);
      chrono(b, ["dispatch-release", "--dispatch", impl, "--as", "belthazar", "--session-token", implToken]);
      // Critical mandates the explicit Glenn review assignment.
      const assigned = chrono(b, ["review-assign", "--kind", "security-review", "--module", "MOD-0002", "--wp", "WP-0001",
        "--as", "gaspar", "--session-token", keys.gasparToken]);
      const glenn = dispatchRoundTrip(b, keys, flow, { wp: "WP-0001", kind: "security-review", agent: "glenn", workerKey: "box-c-glenn", rationale: "critical review" });
      const glennToken = flow.workerTokens.get("box-c-glenn") ?? "";
      recordEvidence(b, "glenn", glennToken, rev, "review");
      chrono(b, ["review-complete", "--review", assigned["reviewId"] as string, "--as", "glenn", "--session-token", glennToken]);
      chrono(b, ["dispatch-release", "--dispatch", glenn, "--as", "glenn", "--session-token", glennToken]);
      // Critical mandates Implementation Security Acceptance for the
      // package revision: the PO risk decision, embodied with a
      // genuine signature.
      poApprove(b, keys, "implementation-security", "WP-0001", rev);
      const vassigned = chrono(b, ["review-assign", "--kind", "verification", "--module", "MOD-0002", "--wp", "WP-0001",
        "--as", "gaspar", "--session-token", keys.gasparToken]);
      const spek = dispatchRoundTrip(b, keys, flow, { wp: "WP-0001", kind: "verification", agent: "spekkio", workerKey: "box-c-spek", rationale: "critical verify" });
      const spekToken = flow.workerTokens.get("box-c-spek") ?? "";
      chrono(b, ["verify-record", "--module", "MOD-0002", "--verdict", "PASS", "--reviewer", "spekkio",
        "--wp", "WP-0001", "--as", "spekkio", "--session-token", spekToken]);
      chrono(b, ["review-complete", "--review", vassigned["reviewId"] as string, "--as", "spekkio", "--session-token", spekToken]);
      chrono(b, ["scope-advance", "--module", "MOD-0002", "--wp", "WP-0001", "--event", "SpekkioPassed",
        "--as", "spekkio", "--session-token", spekToken]);
      expect(wpStatus(b, keys, "WP-0001")).toBe("COMPLETE");
      chrono(b, ["dispatch-release", "--dispatch", spek, "--as", "spekkio", "--session-token", spekToken]);
      // No batching under critical: ready siblings never ride along.
      const next = nextAction(b, keys, { module: "MOD-0002" });
      expect(next["targetId"]).toBe("WP-0002");
      expect(next).not.toHaveProperty("alsoReady");
      // Aggregate completion waits: WP-0002 is still open, and the
      // denial names it instead of waving the module through.
      const denied = chronoDenies(b, ["complete-module", "--module", "MOD-0002",
        "--as", "gaspar", "--session-token", keys.gasparToken], ["COMPLETION_DENIED"]);
      expect(denied).toContain("WP-0002");
    }, BOX_TIMEOUT);

    it("negatives: every bypass denies with its exact reason", () => {
      const b = requireBox();
      const keys = setupProject("Implements the contracted widget behavior.");
      const gasparArgs = ["--as", "gaspar", "--session-token", keys.gasparToken];
      // Wrong role for the kind: spekkio cannot take implementation work.
      const req = chrono(b, ["dispatch-request", "--module", "MOD-0002", "--wp", "WP-0001", "--rationale", "negative probe",
        ...gasparArgs, "--adapter", "fixture", "--opencode-session", "gaspar-box"]);
      const dispatchId = req["dispatchId"] as string;
      chronoDenies(b, ["dispatch-task-check", "--session", "gaspar-box", "--agent", "spekkio"], ["TASK_DENIED"]);
      // Wrong work package scope for the delegation.
      chronoDenies(b, ["dispatch-request", "--module", "MOD-0002", "--wp", "WP-9999", "--rationale", "ghost",
        ...gasparArgs, "--adapter", "fixture", "--opencode-session", "gaspar-box"], ["REFERENCE_UNRESOLVABLE", "ENTITY_NOT_FOUND"]);
      // Claim without delegation: guessing dispatch ids denies.
      chronoDenies(b, ["dispatch-claim", "--dispatch", dispatchId, "--agent", "belthazar", "--worker-session", "box-n-guess"], ["EXECUTION_DENIED"]);
      // Replay: delegate once, claim twice.
      chrono(b, ["dispatch-task-check", "--session", "gaspar-box", "--agent", "belthazar"]);
      chrono(b, ["dispatch-claim", "--dispatch", dispatchId, "--agent", "belthazar", "--worker-session", "box-n-w1"]);
      chronoDenies(b, ["dispatch-claim", "--dispatch", dispatchId, "--agent", "belthazar", "--worker-session", "box-n-w2"], ["EXECUTION_DENIED"]);
      // Cross-session claim into the requester session denies.
      chronoDenies(b, ["dispatch-claim", "--dispatch", dispatchId, "--agent", "belthazar", "--worker-session", "gaspar-box"], ["EXECUTION_DENIED", "VALIDATION_ERROR"]);
      // Gate skipping: mutation without any binding denies, and mints no grant.
      const gate = sh(b.chronoBin, ["gate", "execution", "--module", "MOD-0002", "--wp", "WP-0001",
        "--as", "belthazar", "--role", "belthazar", "--session-token", keys.gasparToken,
        "--path", b.project, "--json"], { cwd: b.project, env: childEnv(b) });
      expect(gate.exit).toBe(1);
      expect(gate.stdout).not.toContain("GRANT-");
      // Corrupted projection: a mangled ledger line reads as absent
      // while a live intent still delegates exactly once. Runs while
      // the scope is positioned (RUNNING): the original dispatch is
      // ENACTED, so exactly one PENDING intent exists.
      const fresh = chrono(b, ["dispatch-request", "--module", "MOD-0002", "--wp", "WP-0001", "--rationale", "post-corruption probe",
        ...gasparArgs, "--adapter", "fixture", "--opencode-session", "gaspar-box"]);
      const ledger = join(b.project, ".chrono", "opencode-dispatch.jsonl");
      writeFileSync(ledger, "NOT-JSON{{{\n", { flag: "a" });
      const stillLive = chrono(b, ["dispatch-task-check", "--session", "gaspar-box", "--agent", "melchior"]);
      expect(stillLive["ok"]).toBe(true);
      expect(stillLive["dispatchId"]).toBe(fresh["dispatchId"]);
      // Reviewer impersonation: belthazar cannot complete a Glenn
      // review. CF-12 reviewability precedes persistence, so the work
      // positions first (confirm, evidence, advance to IMPLEMENTED),
      // then the assignment succeeds and the impersonation denies.
      chrono(b, ["dispatch-confirm", "--dispatch", dispatchId, ...gasparArgs]);
      const negRev = wpRevision(b, keys, "WP-0001");
      const negToken = tokenFor(b, "box-n-w1");
      recordEvidence(b, "belthazar", negToken, negRev, "neg-impl");
      chrono(b, ["scope-advance", "--module", "MOD-0002", "--wp", "WP-0001", "--event", "ImplementationDone",
        "--as", "belthazar", "--session-token", negToken]);
      const assigned = chrono(b, ["review-assign", "--kind", "security-review", "--module", "MOD-0002", "--wp", "WP-0001", ...gasparArgs]);
      chronoDenies(b, ["review-complete", "--review", assigned["reviewId"] as string, "--as", "belthazar",
        "--session-token", keys.gasparToken], ["EXECUTION_DENIED"]);
      // Revocation ends the binding: the worker credential dies with it.
      chrono(b, ["dispatch-revoke", "--dispatch", dispatchId, "--reason", "negative probe", ...gasparArgs]);
      const after = sh(b.chronoBin, ["gate", "execution", "--module", "MOD-0002", "--wp", "WP-0001",
        "--as", "belthazar", "--role", "belthazar", "--session-token", tokenFor(b, "box-n-w1"),
        "--path", b.project, "--json"], { cwd: b.project, env: childEnv(b) });
      expect(after.exit).toBe(1);
    }, BOX_TIMEOUT);

    it("migrated state (CF-12): approvals without activation resolve through module-activate, then the full walk", () => {
      const b = requireBox();
      const keys = setupProject("Implements the contracted widget behavior.", "migrated");
      const flow: Flow = { keys, workerTokens: new Map() };
      const gasparArgs = ["--as", "gaspar", "--session-token", keys.gasparToken];

      // 1. The migrated contradiction is visible, never silent:
      // deep-check flags approval-without-activation, and no
      // premature review row exists (assignment below denies
      // before persistence).
      const deepBefore = chrono(b, ["deep-check", ...gasparArgs]);
      expect(Number(deepBefore["blockerCount"])).toBeGreaterThan(0);
      const findings = deepBefore["findings"] as Array<{ severity: string; check: string; detail: string }>;
      expect(findings.some((f) => f.check === "approval-without-activation" && f.detail.includes("MOD-0002"))).toBe(true);
      expect(findings.some((f) => f.check === "premature-review")).toBe(false);

      // 2. Activation is the only executable step, at both scopes.
      expect(nextAction(b, keys, { module: "MOD-0002" })["action"]).toBe("activate-module");
      expect(nextAction(b, keys, { wp: "WP-0001" })["action"]).toBe("activate-module");

      // 3. Everything downstream denies while DRAFT: dispatch,
      // package authorization, and premature review assignment.
      chronoDenies(b, ["dispatch-request", "--module", "MOD-0002", "--wp", "WP-0001", "--rationale", "migrated probe",
        ...gasparArgs, "--adapter", "fixture", "--opencode-session", "gaspar-box"], ["EXECUTION_DENIED"]);
      chronoDenies(b, ["wp-authorize", "--wp", "WP-0001", ...gasparArgs], ["EXECUTION_DENIED"]);
      chronoDenies(b, ["review-assign", "--kind", "verification", "--module", "MOD-0002", "--wp", "WP-0001", ...gasparArgs],
        ["EXECUTION_DENIED"]);

      // 4. The migrated approvals are already current: replaying the
      // identical payload denies as a duplicate.
      const modRev = chrono(b, ["execution-status", "--module", "MOD-0002", ...gasparArgs])["moduleRevision"] as string;
      expect(typeof modRev).toBe("string");
      poApproveDenied(b, keys, "module-approval", "MOD-0002", modRev);

      // 5. Canonical activation through the binary: DRAFT →
      // AWAITING_APPROVAL → APPROVED exactly once, replay idempotent.
      const activated = chrono(b, ["module-activate", "--module", "MOD-0002", ...gasparArgs]);
      expect(activated["ok"]).toBe(true);
      expect(activated["state"]).toBe("APPROVED");
      const replay = chrono(b, ["module-activate", "--module", "MOD-0002", ...gasparArgs]);
      expect(replay["ok"]).toBe(true);
      expect(replay["state"]).toBe("APPROVED");

      // 6. The contradiction clears: deep-check clean, the package authorizes.
      const deepAfter = chrono(b, ["deep-check", ...gasparArgs]);
      expect(deepAfter["blockerCount"]).toBe(0);
      expect(nextAction(b, keys, { wp: "WP-0001" })["action"]).toBe("authorize-wp");
      const wpauth = chrono(b, ["wp-authorize", "--wp", "WP-0001", ...gasparArgs]);
      expect(wpauth["ok"]).toBe(true);

      // 7. Full walk to COMPLETE through the binary (standard fast
      // path: implementation + test evidence, verification PASS,
      // aggregate completion).
      expect(nextAction(b, keys, { wp: "WP-0001" })["action"]).toBe("request-dispatch");
      const impl = dispatchRoundTrip(b, keys, flow, { wp: "WP-0001", agent: "belthazar", workerKey: "box-m-impl", rationale: "migrated implement" });
      const implToken = flow.workerTokens.get("box-m-impl") ?? "";
      const rev = wpRevision(b, keys, "WP-0001");
      recordEvidence(b, "belthazar", implToken, rev, "unit-impl");
      const test = dispatchRoundTrip(b, keys, flow, { wp: "WP-0001", kind: "test", agent: "lucca", workerKey: "box-m-test", rationale: "migrated test" });
      const testToken = flow.workerTokens.get("box-m-test") ?? "";
      recordEvidence(b, "lucca", testToken, rev, "unit");
      chrono(b, ["dispatch-release", "--dispatch", test, "--as", "lucca", "--session-token", testToken]);
      chrono(b, ["scope-advance", "--module", "MOD-0002", "--wp", "WP-0001", "--event", "ImplementationDone",
        "--as", "belthazar", "--session-token", implToken]);
      chrono(b, ["scope-advance", "--module", "MOD-0002", "--wp", "WP-0001", "--event", "VerificationReady",
        "--as", "belthazar", "--session-token", implToken]);
      chrono(b, ["dispatch-release", "--dispatch", impl, "--as", "belthazar", "--session-token", implToken]);
      expect(nextAction(b, keys, { wp: "WP-0001" })["action"]).toBe("assign-review");
      const vassigned = chrono(b, ["review-assign", "--kind", "verification", "--module", "MOD-0002", "--wp", "WP-0001", ...gasparArgs]);
      const spek = dispatchRoundTrip(b, keys, flow, { wp: "WP-0001", kind: "verification", agent: "spekkio", workerKey: "box-m-spek", rationale: "migrated verify" });
      const spekToken = flow.workerTokens.get("box-m-spek") ?? "";
      chrono(b, ["verify-record", "--module", "MOD-0002", "--verdict", "PASS", "--reviewer", "spekkio",
        "--wp", "WP-0001", "--as", "spekkio", "--session-token", spekToken]);
      chrono(b, ["review-complete", "--review", vassigned["reviewId"] as string, "--as", "spekkio", "--session-token", spekToken]);
      chrono(b, ["scope-advance", "--module", "MOD-0002", "--wp", "WP-0001", "--event", "SpekkioPassed",
        "--as", "spekkio", "--session-token", spekToken]);
      expect(wpStatus(b, keys, "WP-0001")).toBe("COMPLETE");
      chrono(b, ["dispatch-release", "--dispatch", spek, "--as", "spekkio", "--session-token", spekToken]);

      // 8. Aggregate completion, terminal confirmation, restart boundary.
      expect(nextAction(b, keys, { module: "MOD-0002" })["action"]).toBe("complete-module");
      const modExec = chrono(b, ["execution-status", "--module", "MOD-0002", ...gasparArgs]);
      poApprove(b, keys, "implementation-security", "MOD-0002", modExec["moduleRevision"] as string);
      const done = chrono(b, ["complete-module", "--module", "MOD-0002", ...gasparArgs]);
      expect(done["state"]).toBe("COMPLETE");
      expect(nextAction(b, keys, { module: "MOD-0002" })["action"]).toBe("done");
      const deepFinal = chrono(b, ["deep-check", ...gasparArgs]);
      expect(deepFinal["blockerCount"]).toBe(0);
      expect(deepFinal["warningCount"]).toBe(0);
      const rec = chrono(b, ["dispatch-reconcile", ...gasparArgs]);
      expect(rec["expired"]).toEqual([]);
      expect(rec["revoked"]).toEqual([]);
      expect(chrono(b, ["status"])["ok"]).toBe(true);
      expect((chrono(b, ["validate"]) as { valid?: boolean })["valid"]).toBe(true);
    }, BOX_TIMEOUT);
  });
}
