/**
 * OC-P11 native planning tools end to end (C4–C6 correction).
 *
 * Executes the EXACT generated bytes (`.opencode/tools/chrono.ts`)
 * for real: fixture node_modules resolve the pinned
 * `@opencode-ai/plugin` + zod, a node shim fronts the REAL built CLI,
 * and a REAL Core project backs every call. Fixtures cover only the
 * model (tool arguments), the human (ask allow/deny), the OS keychain
 * (key helper), and the entry token file — the plugin/tool/CLI/Core/
 * filesystem boundary is the same one OpenCode uses.
 *
 * Covered: registration + schemas, inline-body propose/revise with
 * real canonical `.md` creation and Core persistence, separate-process
 * status visibility, session/project/role binding, no token/key
 * leakage, arbitrary-path and product-code denial, generic
 * shell/write/edit denial before dispatch, real ticket creation,
 * native ask confirmation, signed approval + continuation, and denial
 * of chat-only/auto/replay/stale/expired/forged/cancelled/
 * cross-session/cross-project approval.
 */
import { describe, it, expect, beforeEach, afterEach } from "vitest";
import {
  chmodSync,
  existsSync,
  mkdtempSync,
  mkdirSync,
  readFileSync,
  realpathSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { createHash, randomBytes } from "node:crypto";
import { pathToFileURL } from "node:url";
import {
  RTK_UPSTREAM,
  SKILL_RELEASE,
  SKILL_RUNTIME_PATHS,
  SKILL_UPSTREAM,
  buildApprovalPayload,
  buildEnrollmentChallenge,
  buildEnrollmentPayload,
  buildSessionAuthorizationPayload,
  convertSkillSource,
  fingerprintPublicKey,
  generateApprovalKeyPair,
  hashSkillSource,
  signApprovalPayload,
  skillGeneratedHashes,
  skillVendorPath,
} from "@chrono/domain";
import { ChronoCore } from "@chrono/core";
import {
  CHRONO_NATIVE_TOOLS,
  OPENCODE_PLUGIN_DEP,
  OPENCODE_PLUGIN_PIN,
  OPENCODE_TOOLS_FILE_RELATIVE,
  OPENCODE_TOOLS_PACKAGE_RELATIVE,
  buildPlanningToolsFile,
  buildPlanningToolsPackage,
  checkPlanningToolsFile,
} from "./opencode-planning-tools.js";
import { installPlanningToolsPackage } from "./index.js";

const REPO_ROOT = realpathSync(join(__dirname, "..", "..", ".."));
const SETUP_FIXED_TIME = "2026-06-01T00:00:00.000Z";

// Byte-exact canonical skill source at the pinned commit (same frozen
// fixture the setup suites use: hash matches SKILL_RELEASE.sourceHash).
const FIXTURE_SKILL_MD = `---
name: karpathy-guidelines
description: Behavioral guidelines to reduce common LLM coding mistakes. Use when writing, reviewing, or refactoring code to avoid overcomplication, make surgical changes, surface assumptions, and define verifiable success criteria.
license: MIT
---

# Karpathy Guidelines

Behavioral guidelines to reduce common LLM coding mistakes, derived from [Andrej Karpathy's observations](https://x.com/karpathy/status/2015883857489522876) on LLM coding pitfalls.

**Tradeoff:** These guidelines bias toward caution over speed. For trivial tasks, use judgment.

## 1. Think Before Coding

**Don't assume. Don't hide confusion. Surface tradeoffs.**

Before implementing:
- State your assumptions explicitly. If uncertain, ask.
- If multiple interpretations exist, present them - don't pick silently.
- If a simpler approach exists, say so. Push back when warranted.
- If something is unclear, stop. Name what's confusing. Ask.

## 2. Simplicity First

**Minimum code that solves the problem. Nothing speculative.**

- No features beyond what was asked.
- No abstractions for single-use code.
- No "flexibility" or "configurability" that wasn't requested.
- No error handling for impossible scenarios.
- If you write 200 lines and it could be 50, rewrite it.

Ask yourself: "Would a senior engineer say this is overcomplicated?" If yes, simplify.

## 3. Surgical Changes

**Touch only what you must. Clean up only your own mess.**

When editing existing code:
- Don't "improve" adjacent code, comments, or formatting.
- Don't refactor things that aren't broken.
- Match existing style, even if you'd do it differently.
- If you notice unrelated dead code, mention it - don't delete it.

When your changes create orphans:
- Remove imports/variables/functions that YOUR changes made unused.
- Don't remove pre-existing dead code unless asked.

The test: Every changed line should trace directly to the user's request.

## 4. Goal-Driven Execution

**Define success criteria. Loop until verified.**

Transform tasks into verifiable goals:
- "Add validation" → "Write tests for invalid inputs, then make them pass"
- "Fix the bug" → "Write a test that reproduces it, then make it pass"
- "Refactor X" → "Ensure tests pass before and after"

For multi-step tasks, state a brief plan:
\`\`\`
1. [Step] → verify: [check]
2. [Step] → verify: [check]
3. [Step] → verify: [check]
\`\`\`

Strong success criteria let you loop independently. Weak criteria ("make it work") require constant clarification.
`;

function fakeTty(): () => void {
  const stdinDesc = Object.getOwnPropertyDescriptor(process.stdin, "isTTY");
  const stdoutDesc = Object.getOwnPropertyDescriptor(process.stdout, "isTTY");
  Object.defineProperty(process.stdin, "isTTY", { value: true, configurable: true });
  Object.defineProperty(process.stdout, "isTTY", { value: true, configurable: true });
  return () => {
    if (stdinDesc !== undefined) Object.defineProperty(process.stdin, "isTTY", stdinDesc);
    else delete (process.stdin as { isTTY?: boolean }).isTTY;
    if (stdoutDesc !== undefined) Object.defineProperty(process.stdout, "isTTY", stdoutDesc);
    else delete (process.stdout as { isTTY?: boolean }).isTTY;
  };
}

interface AskFixture {
  readonly calls: Array<{ permission: string; patterns: string[]; metadata: Record<string, unknown> }>;
  mode: "allow" | "deny";
}

function makeAsk(fixture: AskFixture) {
  return async (input: { permission: string; patterns: string[]; always: string[]; metadata: Record<string, unknown> }) => {
    fixture.calls.push({ permission: input.permission, patterns: input.patterns, metadata: input.metadata });
    if (fixture.mode === "deny") {
      throw new Error("human declined");
    }
  };
}

describe("OC-P11 native planning tools", () => {
  let tempDir: string;
  let root: string;
  let core: ChronoCore;
  let signingKey = "";
  let gasparSession = { id: "", token: "" };
  let restoreTty: () => void;
  let savedEnv: Record<string, string | undefined>;
  const openSessionId = "native-e2e-1";
  let tools: Record<string, any>;
  let askFixture: AskFixture;

  function tokenPath(): string {
    return join(
      tmpdir(),
      `chrono-gaspar-host-${createHash("sha256").update(`${root}|${openSessionId}`, "utf8").digest("hex").slice(0, 16)}.token`
    );
  }

  function toolContext(overrides: Record<string, unknown> = {}): Record<string, unknown> {
    return {
      sessionID: openSessionId,
      messageID: "m1",
      agent: "gaspar",
      directory: root,
      worktree: root,
      abort: new AbortController().signal,
      metadata: () => undefined,
      ask: makeAsk(askFixture),
      ...overrides,
    };
  }

  beforeEach(async () => {
    tempDir = mkdtempSync(join(tmpdir(), "chrono-native-tools-"));
    root = realpathSync(tempDir);
    // Fixture node resolution for the generated tool module: the pinned
    // registry packages, symlinked (never copied, never vendored).
    const fixtureModules = join(root, "node_modules");
    mkdirSync(join(fixtureModules, "@opencode-ai"), { recursive: true });
    symlinkSync(join(REPO_ROOT, "node_modules", "@opencode-ai", "plugin"), join(fixtureModules, "@opencode-ai", "plugin"), "dir");
    symlinkSync(join(REPO_ROOT, "node_modules", "zod"), join(fixtureModules, "zod"), "dir");
    // Exact generated bytes, imported for real.
    mkdirSync(join(root, ".opencode", "tools"), { recursive: true });
    writeFileSync(join(root, OPENCODE_TOOLS_FILE_RELATIVE), buildPlanningToolsFile(), "utf8");
    writeFileSync(join(root, OPENCODE_TOOLS_PACKAGE_RELATIVE), buildPlanningToolsPackage(), "utf8");
    tools = (await import(pathToFileURL(join(root, OPENCODE_TOOLS_FILE_RELATIVE)).href)) as Record<string, unknown>;
    savedEnv = { ...process.env };
    for (const key of ["CHRONO_BIN", "CHRONO_KEY_HELPER", "CHRONO_SESSION_TOKEN"]) {
      delete process.env[key];
    }
    // Real CLI shape behind a node shim (same boundary OpenCode uses).
    const shim = join(root, "chrono-shim.sh");
    writeFileSync(shim, `#!/bin/sh\nexec node ${join(REPO_ROOT, "packages", "cli", "dist", "bin.js")} "$@"\n`, "utf8");
    chmodSync(shim, 0o755);
    process.env["CHRONO_BIN"] = shim;
    // Real Core project with enrolled PO key and Gaspar session.
    core = new ChronoCore({ projectPath: root, runtime: "opencode" });
    expect(core.init().ok).toBe(true);
    const pair = generateApprovalKeyPair();
    restoreTty = fakeTty();
    const nonce = randomBytes(16).toString("hex");
    const fingerprint = fingerprintPublicKey(pair.publicKeyPem);
    const confirmation = buildEnrollmentChallenge("default", fingerprint, nonce);
    const timestamp = new Date().toISOString();
    const signature = signApprovalPayload(
      buildEnrollmentPayload({ projectId: "default", fingerprint, timestamp, nonce, authority: "PO", rationale: "test", confirmation }),
      pair.privateKeyPem
    );
    expect(core.enrollPo({ publicKeyPem: pair.publicKeyPem, nonce, timestamp, rationale: "test", confirmation, signature }).ok).toBe(true);
    signingKey = pair.privateKeyPem;
    const keyFile = join(root, "po-key.pem");
    writeFileSync(keyFile, signingKey, { mode: 0o600 });
    const helper = join(root, "key-helper.sh");
    writeFileSync(helper, `#!/bin/sh\ncat "${keyFile}"\n`, "utf8");
    chmodSync(helper, 0o755);
    process.env["CHRONO_KEY_HELPER"] = helper;
    const sessionNonce = randomBytes(16).toString("hex");
    const sessionTimestamp = "2026-09-11T00:00:00.000Z";
    const sessionSig = signApprovalPayload(
      buildSessionAuthorizationPayload({
        sessionRole: "gaspar", adapter: "test-adapter", runtime: "opencode",
        scopeModule: null, scopeWp: null, ttlSeconds: 3600, nonce: sessionNonce,
        authority: "PO", rationale: "test", timestamp: sessionTimestamp,
      }),
      signingKey
    );
    const opened = core.openSession(
      { role: "gaspar", adapter: "test-adapter", runtime: "opencode", ttlSeconds: 3600 },
      { poAuthorization: { nonce: sessionNonce, authority: "PO", rationale: "test", timestamp: sessionTimestamp, signature: sessionSig } }
    );
    expect(opened.ok).toBe(true);
    gasparSession = { id: opened.value!.id, token: opened.value!.token };
    // What a real entry confines for this exact OpenCode session.
    writeFileSync(tokenPath(), `${gasparSession.id}/${gasparSession.token}`, { mode: 0o600 });
    askFixture = { calls: [], mode: "allow" };
    void gasparSession;
  });

  afterEach(() => {
    for (const key of Object.keys(savedEnv)) {
      if (savedEnv[key] === undefined) delete process.env[key];
      else process.env[key] = savedEnv[key];
    }
    for (const key of ["CHRONO_BIN", "CHRONO_KEY_HELPER", "CHRONO_SESSION_TOKEN"]) {
      if (!(key in savedEnv)) delete process.env[key];
    }
    try {
      rmSync(tokenPath(), { force: true });
    } catch {
      // best-effort
    }
    restoreTty();
    core.close();
    rmSync(tempDir, { recursive: true, force: true });
  });

  it("registers exactly the six governed tools with stable schemas", () => {
    // OpenCode resolves tool names as <filename>_<export>; the module
    // file is `chrono`, so these exports become chrono_artifact_* and
    // chrono_approval_* in the runtime.
    const exports = ["artifact_status", "artifact_propose", "artifact_revise", "approval_request", "approval_status", "approval_confirm"];
    expect(Object.keys(tools).sort()).toEqual(exports.sort());
    expect(exports.map((e) => `chrono_${e}`).sort()).toEqual([...CHRONO_NATIVE_TOOLS].sort());
    for (const name of exports) {
      const def = tools[name] as { description: string; args: unknown; execute: unknown };
      expect(typeof def.description).toBe("string");
      expect(def.description.length).toBeGreaterThan(20);
      expect(typeof def.execute).toBe("function");
    }
    // No product-code, shell, hook, or credential surface exists here.
    for (const name of Object.keys(tools)) {
      expect(name).not.toMatch(/write|edit|bash|shell|hook|token|key|secret|db/i);
    }
    // Schemas carry the contract Gaspar programs against.
    const propose = tools["artifact_propose"] as { args: Record<string, { parse: (v: unknown) => unknown }> };
    expect(() => propose.args["body"]?.parse("inline markdown")).not.toThrow();
    expect(() => propose.args["body"]?.parse(42)).toThrow();
    expect(() => propose.args["kind"]?.parse("spec")).not.toThrow();
  });

  it("proposes with an inline body: real .md plus Core persistence, no temp file", async () => {
    const out = (await tools["artifact_propose"].execute(
      { kind: "spec", id: "SP-0001", title: "Tasks", body: "Task contract inline.", references: [] },
      toolContext()
    )) as string;
    const parsed = JSON.parse(out) as { ok: boolean; id: string; revision: string };
    expect(parsed.ok).toBe(true);
    expect(parsed.id).toBe("SP-0001");
    const mdPath = join(root, ".chrono", "specs", "SP-0001.md");
    expect(existsSync(mdPath)).toBe(true);
    expect(readFileSync(mdPath, "utf8")).toContain("Task contract inline.");
    expect(core.getArtifact("SP-0001").status).toBe("DRAFT");
    // Inline body: no draft temp file was needed or left behind.
    expect(existsSync(join(root, "draft-SP-0001.md"))).toBe(false);
    // Separate-process visibility through the real CLI.
    const status = (await tools["artifact_status"].execute({}, toolContext())) as string;
    expect(JSON.parse(status) as { ok: boolean }).toMatchObject({ ok: true });
    expect(status).toContain("SP-0001");
  });

  it("revises drafts and denies unknown, malformed, secret, and oversized bodies", async () => {
    await tools["artifact_propose"].execute(
      { kind: "requirement", id: "REQ-0001", title: "R", body: "First." },
      toolContext()
    );
    const revised = JSON.parse((await tools["artifact_revise"].execute(
      { id: "REQ-0001", title: "R2", body: "Changed inline." },
      toolContext()
    )) as string) as { revision: string };
    expect(readFileSync(join(root, ".chrono", "context", "requirements", "REQ-0001.md"), "utf8")).toContain(revised.revision);
    await expect(
      tools["artifact_revise"].execute({ id: "REQ-9999", title: "T", body: "B" }, toolContext())
    ).rejects.toThrow(/ENTITY_NOT_FOUND/);
    await expect(
      tools["artifact_propose"].execute({ kind: "nope", title: "T", body: "B" }, toolContext())
    ).rejects.toThrow();
    await expect(
      tools["artifact_propose"].execute({ kind: "requirement", id: "REQ-0002", title: "R", body: "-----BEGIN PRIVATE KEY-----\nx" }, toolContext())
    ).rejects.toThrow(/SECRET_DETECTED/);
    await expect(
      tools["artifact_propose"].execute({ kind: "requirement", id: "REQ-0003", title: "R", body: "x".repeat(70000) }, toolContext())
    ).rejects.toThrow();
  });

  it("denies arbitrary paths and product-code writes: destinations are Core-derived", async () => {
    await expect(
      tools["artifact_propose"].execute({ kind: "spec", id: "../../evil", title: "T", body: "B" }, toolContext())
    ).rejects.toThrow();
    // The tool surface has no destination parameter at all.
    expect(Object.keys(tools).join(" ")).not.toMatch(/path|destination|write|edit|bash|shell/);
    expect(existsSync(join(root, "evil"))).toBe(false);
    expect(existsSync(join(root, "src"))).toBe(false);
  });

  it("binds session, project, and role: cross-session and cross-project deny", async () => {
    await tools["artifact_propose"].execute(
      { kind: "spec", id: "SP-0001", title: "S", body: "Body." },
      toolContext()
    );
    // Another OpenCode session has no entry token file: denied.
    await expect(
      tools["artifact_status"].execute({}, toolContext({ sessionID: "other-session" }))
    ).rejects.toThrow(/entry session/);
    // Another project directory: no entry, no database binding.
    const other = join(root, "sibling");
    mkdirSync(other, { recursive: true });
    await expect(tools["artifact_status"].execute({}, toolContext({ directory: other, worktree: other }))).rejects.toThrow();
  });

  it("leaks no token or key material through results", async () => {
    const proposed = (await tools["artifact_propose"].execute(
      { kind: "spec", id: "SP-0001", title: "S", body: "Body." },
      toolContext()
    )) as string;
    const status = (await tools["artifact_status"].execute({}, toolContext())) as string;
    const haystack = proposed + "\n" + status;
    expect(haystack).not.toContain(gasparSession.token);
    expect(haystack).not.toContain(signingKey.slice(0, 24));
    expect(haystack).not.toContain("PRIVATE KEY");
  });

  it("full ceremony through native tools: request, ask, signed approval, continuation", async () => {
    await tools["artifact_propose"].execute(
      { kind: "spec", id: "SP-0001", title: "Tasks", body: "Contract." },
      toolContext()
    );
    const specRev = core.getArtifact("SP-0001").revision;
    const requested = JSON.parse((await tools["approval_request"].execute(
      { action: "planning-approval", scope: "SP-0001", revision: specRev, rationale: "accept", securityImplications: "none" },
      toolContext()
    )) as string) as { ticketId: string; challenge: string };
    expect(requested.ticketId).toMatch(/^TICKET-[0-9]{4}$/);
    // Gaspar shows the canonical line in the native question; the human
    // answers in the OpenCode UI; the confirm tool owns the ask boundary.
    const receipt = JSON.parse((await tools["approval_confirm"].execute({ ticket: requested.ticketId }, toolContext())) as string) as {
      ok: boolean;
      approvalId: string;
    };
    expect(receipt.ok).toBe(true);
    expect(receipt.approvalId).toMatch(/^APR-[0-9]{4}$/);
    // The ask boundary saw the exact ticket scope exactly once.
    expect(askFixture.calls).toHaveLength(1);
    expect(askFixture.calls[0]).toMatchObject({ permission: "chrono.approval", patterns: [requested.ticketId] });
    expect(askFixture.calls[0]?.metadata).toMatchObject({ scope: "SP-0001", revision: specRev });
    expect(core.hasValidApproval("SP-0001", specRev, "planning-approval")).toBe(true);
    // Conversation continues without restart: status reflects approval.
    const status = JSON.parse((await tools["artifact_status"].execute({}, toolContext())) as string) as {
      items: Array<{ id: string; approval: string }>;
    };
    expect(status.items.find((i) => i.id === "SP-0001")?.approval).toBe("approved");
    // Same governed path continues to Module and Work Package plans.
    const mod = JSON.parse((await tools["artifact_propose"].execute(
      { kind: "module", id: "MOD-0001", title: "M", body: "Plan.", references: ["SP-0001"] },
      toolContext()
    )) as string) as { ok: boolean };
    expect(mod.ok).toBe(true);
    const wp = JSON.parse((await tools["artifact_propose"].execute(
      { kind: "workpackage", id: "WP-0001", title: "W", body: "Plan.", references: ["MOD-0001"] },
      toolContext()
    )) as string) as { ok: boolean };
    expect(wp.ok).toBe(true);
  });

  it("denies cancelled, replayed, stale, forged, auto, and ticketless confirmation", async () => {
    await tools["artifact_propose"].execute(
      { kind: "spec", id: "SP-0001", title: "S", body: "Body." },
      toolContext()
    );
    const specRev = core.getArtifact("SP-0001").revision;
    // Cancelled human answer: no state changes, ticket survives.
    const cancelled = JSON.parse((await tools["approval_request"].execute(
      { action: "planning-approval", scope: "SP-0001", revision: specRev, rationale: "r", securityImplications: "s" },
      toolContext()
    )) as string) as { ticketId: string };
    askFixture.mode = "deny";
    await expect(tools["approval_confirm"].execute({ ticket: cancelled.ticketId }, toolContext())).rejects.toThrow(/declined or cancelled/);
    expect(core.hasValidApproval("SP-0001", specRev, "planning-approval")).toBe(false);
    askFixture.mode = "allow";
    // Genuine confirmation, then replay denies.
    await tools["approval_confirm"].execute({ ticket: cancelled.ticketId }, toolContext());
    expect(core.hasValidApproval("SP-0001", specRev, "planning-approval")).toBe(true);
    await expect(tools["approval_confirm"].execute({ ticket: cancelled.ticketId }, toolContext())).rejects.toThrow();
    // Forged ticket id denies.
    await expect(tools["approval_confirm"].execute({ ticket: "TICKET-9999" }, toolContext())).rejects.toThrow();
    // Malformed ticket id denies before any Core contact.
    await expect(tools["approval_confirm"].execute({ ticket: "nope" }, toolContext())).rejects.toThrow(/malformed/);
    // Stale: revise after requesting, then confirm the old ticket.
    // (SP-0001 is already approved above, so the stale case uses a
    // fresh draft scope; re-requesting an approved revision correctly
    // refuses with DUPLICATE_IDENTITY.)
    const req3 = await tools["artifact_propose"].execute(
      { kind: "requirement", id: "REQ-0001", title: "R", body: "One." },
      toolContext()
    );
    // File-only kinds (requirement/ADR/discovery) track revisions in
    // runtime config, not artifact rows: read the revision from the
    // propose receipt, exactly as Gaspar would from the tool result.
    const req3Rev = (JSON.parse(req3) as { revision: string }).revision;
    const t3 = JSON.parse((await tools["approval_request"].execute(
      { action: "planning-approval", scope: "REQ-0001", revision: req3Rev, rationale: "r", securityImplications: "s" },
      toolContext()
    )) as string) as { ticketId: string };
    // Revise through the native tool (same governed operation Gaspar uses).
    const revised = JSON.parse((await tools["artifact_revise"].execute(
      { id: "REQ-0001", title: "R2", body: "Changed inline body." },
      toolContext()
    )) as string) as { revision: string };
    await expect(tools["approval_confirm"].execute({ ticket: t3.ticketId }, toolContext())).rejects.toThrow();
    expect(core.hasValidApproval("REQ-0001", revised.revision, "planning-approval")).toBe(false);
  });

  it("refuses the ceremony under --auto without touching state", async () => {
    await tools["artifact_propose"].execute(
      { kind: "spec", id: "SP-0001", title: "S", body: "Body." },
      toolContext()
    );
    const specRev = core.getArtifact("SP-0001").revision;
    const requested = JSON.parse((await tools["approval_request"].execute(
      { action: "planning-approval", scope: "SP-0001", revision: specRev, rationale: "r", securityImplications: "s" },
      toolContext()
    )) as string) as { ticketId: string };
    process.argv.push("--auto");
    try {
      await expect(tools["approval_confirm"].execute({ ticket: requested.ticketId }, toolContext())).rejects.toThrow(/auto-approve/);
    } finally {
      process.argv.pop();
    }
    expect(core.hasValidApproval("SP-0001", specRev, "planning-approval")).toBe(false);
    expect(askFixture.calls).toHaveLength(0);
  });

  it("fails loudly when the native ask boundary is missing", async () => {
    await tools["artifact_propose"].execute(
      { kind: "spec", id: "SP-0001", title: "S", body: "Body." },
      toolContext()
    );
    const specRev = core.getArtifact("SP-0001").revision;
    const requested = JSON.parse((await tools["approval_request"].execute(
      { action: "planning-approval", scope: "SP-0001", revision: specRev, rationale: "r", securityImplications: "s" },
      toolContext()
    )) as string) as { ticketId: string };
    const { ask: _ask, ...withoutAsk } = toolContext();
    void _ask;
    await expect(tools["approval_confirm"].execute({ ticket: requested.ticketId }, withoutAsk)).rejects.toThrow(/ask boundary is unavailable/);
    expect(core.hasValidApproval("SP-0001", specRev, "planning-approval")).toBe(false);
  });
});

describe("OC-P11 setup repair for native tools", () => {
  let tempDir: string;
  let restoreTty: () => void;
  let rtkBinary: string;

  function shellScript(path: string, body: string): string {
    writeFileSync(path, `#!/bin/sh\n${body}\n`, "utf8");
    chmodSync(path, 0o755);
    return path;
  }

  beforeEach(() => {
    tempDir = mkdtempSync(join(tmpdir(), "chrono-tools-setup-"));
    const core = new ChronoCore({ projectPath: tempDir, runtime: "test-runtime" });
    try {
      expect(core.init().ok).toBe(true);
      const pair = generateApprovalKeyPair();
      restoreTty = fakeTty();
      const nonce = randomBytes(16).toString("hex");
      const fingerprint = fingerprintPublicKey(pair.publicKeyPem);
      const confirmation = buildEnrollmentChallenge("default", fingerprint, nonce);
      const timestamp = new Date().toISOString();
      const signature = signApprovalPayload(
        buildEnrollmentPayload({ projectId: "default", fingerprint, timestamp, nonce, authority: "PO", rationale: "test", confirmation }),
        pair.privateKeyPem
      );
      expect(core.enrollPo({ publicKeyPem: pair.publicKeyPem, nonce, timestamp, rationale: "test", confirmation, signature }).ok).toBe(true);
      const openPrivileged = (role: "gaspar" | "PO") => {
        const sessionNonce = randomBytes(16).toString("hex");
        const sessionTimestamp = "2026-09-11T00:00:00.000Z";
        const sessionSig = signApprovalPayload(
          buildSessionAuthorizationPayload({
            sessionRole: role, adapter: "test-adapter", runtime: "test-runtime",
            scopeModule: null, scopeWp: null, ttlSeconds: 3600, nonce: sessionNonce,
            authority: "PO", rationale: "test", timestamp: sessionTimestamp,
          }),
          pair.privateKeyPem
        );
        const opened = core.openSession(
          { role, adapter: "test-adapter", runtime: "test-runtime", ttlSeconds: 3600 },
          { poAuthorization: { nonce: sessionNonce, authority: "PO", rationale: "test", timestamp: sessionTimestamp, signature: sessionSig } }
        );
        expect(opened.ok).toBe(true);
        return { actor: role, session: { id: opened.value!.id, token: opened.value!.token } };
      };
      const gaspar = openPrivileged("gaspar");
      const po = openPrivileged("PO");
      const entrypoint = shellScript(join(tempDir, "fixture-runtime.sh"), "echo 'fixture-runtime 1.0.0'");
      rtkBinary = shellScript(
        join(tempDir, "fixture-rtk.sh"),
        "if [ \"$1\" = \"gain\" ]; then echo 'Token Killer savings dashboard'; else echo 'rtk 0.44.0'; fi"
      );
      const proofBinary = shellScript(join(tempDir, "fixture-proof.sh"), "echo proven");
      expect(core.recordRtkAttestation(gaspar, {
        binaryPath: rtkBinary, binaryIdentity: "rtk-test", version: "1.0.0-test",
        provenance: RTK_UPSTREAM, integrationMode: "test", routingTestPassed: true,
        routingTestLog: "fixture", gained: true, savingsEvidence: null, ttlSeconds: 86400,
      }).ok).toBe(true);
      expect(core.recordSkillAttestation(gaspar, {
        upstream: SKILL_UPSTREAM, pinnedCommit: SKILL_RELEASE.pinnedCommit, sourceHash: SKILL_RELEASE.sourceHash,
        generatedHashes: skillGeneratedHashes(convertSkillSource(FIXTURE_SKILL_MD)),
        converterVersion: SKILL_RELEASE.converterVersion, licenseStatus: "MIT", attribution: "MIT",
        runtimeIdentity: "test", agentIdentity: "test", discoveryResult: "found",
        permissionResult: "granted", activationTestPassed: true, ttlSeconds: 86400,
      }).ok).toBe(true);
      expect(hashSkillSource(FIXTURE_SKILL_MD)).toBe(SKILL_RELEASE.sourceHash);
      const vendorTarget = join(tempDir, skillVendorPath(SKILL_RELEASE.pinnedCommit));
      mkdirSync(dirname(vendorTarget), { recursive: true });
      writeFileSync(vendorTarget, FIXTURE_SKILL_MD, "utf8");
      for (const runtime of ["claude", "opencode", "kiro"] as const) {
        const target = join(tempDir, SKILL_RUNTIME_PATHS[runtime]);
        mkdirSync(dirname(target), { recursive: true });
        writeFileSync(target, FIXTURE_SKILL_MD, "utf8");
      }
      expect(core.registerAdapter(
        { id: "fixture", name: "Fixture", entrypoint, conformanceProof: [`${proofBinary} --check`] }, po
      ).ok).toBe(true);
      const revision = core.adapterRegistrationHash("fixture");
      const approvalSig = signApprovalPayload(
        buildApprovalPayload({
          action: "adapter-registration", scopeArtifactId: "fixture", scopeRevision: revision,
          authority: "PO", rationale: "trust", timestamp: SETUP_FIXED_TIME,
        }),
        pair.privateKeyPem
      );
      const recorded = core.recordApproval({
        action: "adapter-registration", scopeArtifactId: "fixture", scopeRevision: revision,
        authority: "PO", rationale: "trust", timestamp: SETUP_FIXED_TIME, signature: approvalSig,
      });
      expect(recorded.ok).toBe(true);
      expect(core.approveAdapter("fixture", recorded.value!.id, po).ok).toBe(true);
    } finally {
      core.close();
    }
  });

  afterEach(() => {
    restoreTty();
    rmSync(tempDir, { recursive: true, force: true });
  });

  it("setup installs byte-identical native tools and heals drift on repair", async () => {
    const { runSetup } = await import("./index.js");
    expect(runSetup(tempDir, { adapter: "fixture", rtkBinary, json: true }).exitCode).toBe(0);
    expect(readFileSync(join(tempDir, OPENCODE_TOOLS_FILE_RELATIVE), "utf8")).toBe(buildPlanningToolsFile());
    expect(JSON.parse(readFileSync(join(tempDir, OPENCODE_TOOLS_PACKAGE_RELATIVE), "utf8"))).toMatchObject({
      dependencies: { [OPENCODE_PLUGIN_DEP]: OPENCODE_PLUGIN_PIN },
    });
    // Drift the tool module: repair regenerates byte-identical content.
    writeFileSync(join(tempDir, OPENCODE_TOOLS_FILE_RELATIVE), "// hand-edited drift\n", "utf8");
    expect(runSetup(tempDir, { adapter: "fixture", rtkBinary, json: true }).exitCode).toBe(0);
    expect(readFileSync(join(tempDir, OPENCODE_TOOLS_FILE_RELATIVE), "utf8")).toBe(buildPlanningToolsFile());
  });
});

describe("OC-P11 planning tool packaging", () => {
  it("generates deterministic bytes and a pinned runtime manifest", () => {
    expect(buildPlanningToolsFile()).toBe(buildPlanningToolsFile());
    expect(buildPlanningToolsPackage()).toBe(buildPlanningToolsPackage());
    const manifest = JSON.parse(buildPlanningToolsPackage()) as { dependencies: Record<string, string> };
    expect(manifest.dependencies[OPENCODE_PLUGIN_DEP]).toBe(OPENCODE_PLUGIN_PIN);
    // Every native tool is registered exactly once in the module.
    for (const name of CHRONO_NATIVE_TOOLS) {
      const suffix = name.replace(/^chrono_/, "");
      expect(buildPlanningToolsFile()).toContain(`export const ${suffix} = tool(`);
    }
    // No shell, product-write, or credential surface in tool names.
    expect(CHRONO_NATIVE_TOOLS.join(" ")).not.toMatch(/bash|shell|write|edit|token|key|secret/i);
  });

  it("detects missing and drifted tool installations", () => {
    expect(checkPlanningToolsFile(null).state).toBe("missing");
    expect(checkPlanningToolsFile(buildPlanningToolsFile()).state).toBe("ok");
    expect(checkPlanningToolsFile(buildPlanningToolsFile() + "\n// hand edit").state).toBe("drifted");
  });

  it("installs and refuses conflicting runtime manifests", () => {
    const dir = mkdtempSync(join(tmpdir(), "chrono-tools-pkg-"));
    try {
      installPlanningToolsPackage(dir);
      expect(JSON.parse(readFileSync(join(dir, OPENCODE_TOOLS_PACKAGE_RELATIVE), "utf8"))).toMatchObject({
        dependencies: { [OPENCODE_PLUGIN_DEP]: OPENCODE_PLUGIN_PIN },
      });
      // Idempotent re-run preserves user-owned entries.
      const pkgPath = join(dir, OPENCODE_TOOLS_PACKAGE_RELATIVE);
      const withUser = JSON.parse(readFileSync(pkgPath, "utf8")) as { dependencies: Record<string, string> };
      withUser.dependencies["user-tool"] = "1.0.0";
      writeFileSync(pkgPath, JSON.stringify(withUser, null, 2), "utf8");
      installPlanningToolsPackage(dir);
      const merged = JSON.parse(readFileSync(pkgPath, "utf8")) as { dependencies: Record<string, string> };
      expect(merged.dependencies["user-tool"]).toBe("1.0.0");
      expect(merged.dependencies[OPENCODE_PLUGIN_DEP]).toBe(OPENCODE_PLUGIN_PIN);
      // Conflicting pin refuses instead of guessing.
      withUser.dependencies[OPENCODE_PLUGIN_DEP] = "0.0.0";
      writeFileSync(pkgPath, JSON.stringify(withUser, null, 2), "utf8");
      expect(() => installPlanningToolsPackage(dir)).toThrow(/requires/);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});
