/**
 * OpenCode pre-tool enforcement plugin, generated deterministically
 * (Slice 8–9, [RUNTIME §5]). `chrono setup` writes these exact bytes to
 * `<project>/.opencode/plugins/chrono-gate.js`; the content never embeds
 * machine-specific paths, so identical inputs always produce identical
 * bytes. Implements the native `tool.execute.before` hook contract from
 * https://opencode.ai/docs/plugins/: throwing blocks the tool.
 *
 * Slice 9 §9.4: every OpenCode tool capable of filesystem, process,
 * network, package, Git, credential, deployment, destructive, or
 * production-impacting effects is gated through `chrono gate execution`.
 * Read-only tools pass without dispatch scope. Unknown tools — including
 * future built-ins, `mcp_*`, and custom tools — are denied until
 * classified in a reviewed Core policy release (deny-by-default).
 *
 * The plugin uses only `node:child_process` / `node:fs` / `node:path`
 * (available in Bun and Node), so the generated file is directly
 * importable in tests: enforcement logic runs for real, with only the
 * gate binary substituted by a fixture.
 *
 * Tool policy version: TOOL_POLICY_VERSION=1 (see @chrono/domain
 * OPENCODE_TOOL_POLICY). The lists below are generated from that policy;
 * the Core remains the authority — the plugin only shapes the intake.
 */

const READ_TOOLS = ["glob", "grep", "lsp", "question", "read", "skill", "todowrite"];
const MUTATE_TOOLS = [
  "apply_patch",
  "bash",
  "edit",
  "webfetch",
  "websearch",
  "write",
];

export function buildOpencodePlugin(): string {
  return `/**
 * CHRONO pre-tool enforcement for OpenCode. GENERATED by
 * \`chrono setup --adapter <id>\` — do not hand-edit.
 *
 * Enforcement contract (explicit environment, never invented identity):
 * - Outside a CHRONO project (no .chrono/chrono.db under the session
 *   directory): pass, plain OpenCode use is unaffected.
  * - Inside a CHRONO project: read-only tools pass without dispatch
  *   scope; every mutable tool requires CHRONO_GATE_MODULE (+ optional
  *   CHRONO_GATE_WP), CHRONO_GATE_AS, CHRONO_GATE_ROLE, and
  *   CHRONO_SESSION_TOKEN and a live \`chrono gate execution\` AUTHORIZED
  *   verdict. Unknown tools are denied until classified (deny-by-default).
  *   Anything missing or DENIED throws (fail-closed).
  *
  * Automatic Gaspar entry (best effort, never a bypass): on
  * \`session.created\` inside a CHRONO project the plugin runs the
  * managed entry script, which redeems a broker session over a local
  * channel and prints the safe Core projection. The projection is
  * injected once into the session system prompt; the session token
  * stays in plugin memory (never in model context). When entry is
  * unavailable the session proceeds ungoverned and pre-tool gates keep
  * enforcing fail-closed.
  */
import { execFileSync, spawnSync } from "node:child_process";
import { existsSync } from "node:fs";
import { join } from "node:path";

const READ_TOOLS = new Set(${JSON.stringify(READ_TOOLS)});
const MUTATE_TOOLS = new Set(${JSON.stringify(MUTATE_TOOLS)});

function readEnv(name) {
  const value = process.env[name];
  return value === undefined || value === "" ? null : value;
}

function gateFor(tool) {
  if (READ_TOOLS.has(tool)) {
    return "read";
  }
  if (MUTATE_TOOLS.has(tool)) {
    return "mutate";
  }
  return "unknown";
}

export const ChronoGatePlugin = async (ctx) => {
  // Entry projections stashed per OpenCode session id (process memory
  // only). Session tokens never enter this map or model context: the
  // entry script confines the token to a 0600 file and only the safe
  // projection travels on stdout.
  const entryProjections = new Map();
  const runEntryProjection = (root, sessionId) => {
    if (entryProjections.has(sessionId)) {
      return;
    }
    try {
      const script = join(root, ".chrono", "hooks", "chrono-entry-session.sh");
      if (!existsSync(script)) {
        return;
      }
      const adapter = readEnv("CHRONO_ENTRY_ADAPTER") ?? "opencode";
      const chronoBin = readEnv("CHRONO_BIN") ?? "chrono";
      const ran = spawnSync("sh", [script, adapter], {
        encoding: "utf8",
        timeout: 30000,
        env: { ...process.env, CHRONO_BIN: chronoBin },
      });
      const out = typeof ran.stdout === "string" ? ran.stdout.trim() : "";
      if (ran.status === 0 && out.length > 0) {
        entryProjections.set(sessionId, out.slice(0, 8000));
      }
    } catch {
      // Entry is best effort: degraded sessions proceed ungoverned and
      // pre-tool gates keep enforcing fail-closed.
    }
  };
  return {
    event: async ({ event }) => {
      if (!event || event.type !== "session.created") {
        return;
      }
      const root = (ctx && ctx.directory) || process.cwd();
      if (!existsSync(join(root, ".chrono", "chrono.db"))) {
        return;
      }
      const sessionId =
        (event.properties && (event.properties.sessionID || event.properties.session_id)) ||
        event.sessionID ||
        event.session_id ||
        "default";
      runEntryProjection(root, String(sessionId));
    },
    "experimental.chat.system.transform": async (input, output) => {
      try {
        const sessionId =
          (input && (input.sessionID || input.session_id)) || "default";
        const projection = entryProjections.get(String(sessionId));
        if (projection !== undefined && output && Array.isArray(output.system)) {
          output.system.push(
            "<chrono-entry>Gaspar entry projection from the project-pinned Core. " +
              "Derive your opening strictly from it, never from chat history:\\n" +
              projection +
              "</chrono-entry>"
          );
          entryProjections.delete(String(sessionId));
        }
      } catch {
        // Context injection is best effort; enforcement never depends on it.
      }
    },
    "tool.execute.before": async (input) => {
      const tool = input && typeof input.tool === "string" ? input.tool : "";
      const root = (ctx && ctx.directory) || process.cwd();
      if (!existsSync(join(root, ".chrono", "chrono.db"))) {
        return;
      }
      const kind = gateFor(tool);
      if (kind === "read") {
        return;
      }
      if (kind === "unknown") {
        throw new Error(
          \`[chrono] TOOL_DENIED: tool '\${tool}' is not classified by CHRONO tool policy v1: deny-by-default until reviewed.\`
        );
      }
      const module = readEnv("CHRONO_GATE_MODULE");
      if (module === null) {
        throw new Error(
          "[chrono] CHRONO project without dispatch context: export CHRONO_GATE_MODULE (and CHRONO_GATE_WP when scoped) or dispatch via 'chrono run'."
        );
      }
      const token = readEnv("CHRONO_SESSION_TOKEN");
      if (token === null) {
        throw new Error(
          "[chrono] Dispatch context without a session: export CHRONO_SESSION_TOKEN from an authorized session."
        );
      }
      const as = readEnv("CHRONO_GATE_AS");
      const role = readEnv("CHRONO_GATE_ROLE");
      if (as === null || role === null) {
        throw new Error("[chrono] Export CHRONO_GATE_AS and CHRONO_GATE_ROLE for the dispatch.");
      }
      const chronoBin = readEnv("CHRONO_BIN") ?? "chrono";
      const args = [
        "gate",
        "execution",
        "--module",
        module,
        "--as",
        as,
        "--role",
        role,
        "--session-token",
        token,
        "--requester-token",
        readEnv("CHRONO_REQUESTER_TOKEN") ?? token,
        "--path",
        root,
        "--json",
      ];
      const wp = readEnv("CHRONO_GATE_WP");
      if (wp !== null) {
        args.push("--wp", wp);
      }
      let raw;
      try {
        raw = execFileSync(chronoBin, args, { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
      } catch (e) {
        raw = e && e.stdout ? String(e.stdout) : null;
        if (raw === null) {
          throw new Error(
            \`[chrono] gate unreachable: \${e instanceof Error ? e.message : String(e)}\`
          );
        }
      }
      let verdict;
      try {
        verdict = JSON.parse(raw);
      } catch {
        throw new Error("[chrono] gate returned non-JSON output: denying.");
      }
      if (verdict && verdict.result === "AUTHORIZED") {
        return;
      }
      const code = verdict && typeof verdict.code === "string" ? verdict.code : "DENIED";
      const reason = verdict && typeof verdict.reason === "string" ? verdict.reason : "denied";
      throw new Error(\`[chrono] \${code}: \${reason}\`);
    },
  };
};
`;
}
