/**
 * OpenCode pre-tool enforcement plugin, generated deterministically
 * (Slice 8, [RUNTIME §5]). `chrono setup` writes these exact bytes to
 * `<project>/.opencode/plugins/chrono-gate.js`; the content never embeds
 * machine-specific paths, so identical inputs always produce identical
 * bytes. Implements the native `tool.execute.before` hook contract from
 * https://opencode.ai/docs/plugins/: throwing blocks the tool.
 *
 * The plugin uses only `node:child_process` / `node:fs` / `node:path`
 * (available in Bun and Node), so the generated file is directly
 * importable in tests: enforcement logic runs for real, with only the
 * gate binary substituted by a fixture.
 */

export function buildOpencodePlugin(): string {
  return `/**
 * CHRONO pre-tool enforcement for OpenCode. GENERATED by
 * \`chrono setup --adapter <id>\` — do not hand-edit.
 *
 * Enforcement contract (explicit environment, never invented identity):
 * - Outside a CHRONO project (no .chrono/chrono.db under the session
 *   directory): pass, plain OpenCode use is unaffected.
 * - Inside a CHRONO project: require CHRONO_GATE_MODULE (+ optional
 *   CHRONO_GATE_WP), CHRONO_GATE_AS, CHRONO_GATE_ROLE, and
 *   CHRONO_SESSION_TOKEN; call \`chrono gate execution\` and obey it.
 *   Anything missing or DENIED throws (fail-closed).
 * - Only the \`bash\` tool is gated in this version; broader tool mapping
 *   is runtime-specific adapter work.
 */
import { execFileSync } from "node:child_process";
import { existsSync } from "node:fs";
import { join } from "node:path";

function readEnv(name) {
  const value = process.env[name];
  return value === undefined || value === "" ? null : value;
}

export const ChronoGatePlugin = async (ctx) => {
  return {
    "tool.execute.before": async (input) => {
      if (!input || input.tool !== "bash") {
        return;
      }
      const root = (ctx && ctx.directory) || process.cwd();
      if (!existsSync(join(root, ".chrono", "chrono.db"))) {
        return;
      }
      const module = readEnv("CHRONO_GATE_MODULE");
      if (module === null) {
        throw new Error(
          "[chrono] CHRONO project without dispatch context: export CHRONO_GATE_MODULE (and CHRONO_GATE_WP when scoped) or dispatch via 'chrono run'."
        );
      }
      const token = readEnv("CHRONO_SESSION_TOKEN");
      if (token === null) {
        throw new Error(
          "[chrono] Dispatch context without a session: export CHRONO_SESSION_TOKEN from an authorized session."
        );
      }
      const as = readEnv("CHRONO_GATE_AS");
      const role = readEnv("CHRONO_GATE_ROLE");
      if (as === null || role === null) {
        throw new Error("[chrono] Export CHRONO_GATE_AS and CHRONO_GATE_ROLE for the dispatch.");
      }
      const chronoBin = readEnv("CHRONO_BIN") ?? "chrono";
      const args = [
        "gate",
        "execution",
        "--module",
        module,
        "--as",
        as,
        "--role",
        role,
        "--session-token",
        token,
        "--requester-token",
        readEnv("CHRONO_REQUESTER_TOKEN") ?? token,
        "--path",
        root,
        "--json",
      ];
      const wp = readEnv("CHRONO_GATE_WP");
      if (wp !== null) {
        args.push("--wp", wp);
      }
      let raw;
      try {
        raw = execFileSync(chronoBin, args, { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
      } catch (e) {
        raw = e && e.stdout ? String(e.stdout) : null;
        if (raw === null) {
          throw new Error(
            \`[chrono] gate unreachable: \${e instanceof Error ? e.message : String(e)}\`
          );
        }
      }
      let verdict;
      try {
        verdict = JSON.parse(raw);
      } catch {
        throw new Error("[chrono] gate returned non-JSON output: denying.");
      }
      if (verdict && verdict.result === "AUTHORIZED") {
        return;
      }
      const code = verdict && typeof verdict.code === "string" ? verdict.code : "DENIED";
      const reason = verdict && typeof verdict.reason === "string" ? verdict.reason : "denied";
      throw new Error(\`[chrono] \${code}: \${reason}\`);
    },
  };
};
`;
}
