/**
 * Native OpenCode planning tools (OC-P11 correction, C4–C6).
 *
 * The generated Gaspar agent cannot reach Core-governed planning
 * through generic shell (blocked pre-dispatch) or temp files (cannot
 * create them). This module generates real, model-callable tools under
 * `.opencode/tools/chrono.ts` (one file, eight named exports) using the
 * documented OpenCode 1.18.30 custom-tool contract
 * (`import { tool } from "@opencode-ai/plugin"`, Zod schemas, and a
 * `ToolContext` with session/agent/directory/worktree plus `ask()`).
 * The emitted module is plain JavaScript (no TypeScript syntax) so it
 * loads identically under OpenCode/bun and under Node in tests.
 *
 * Every tool executes in the plugin host (never in model context):
 * project from `ToolContext.directory`, session from the host-only
 * entry token bound to the exact OpenCode session, CLI/Core through
 * argument arrays with stdin bodies (no shell, no temp files), and
 * only safe structured results back. Approval confirmation additionally
 * requires the native `ask()` human boundary inside `execute`.
 *
 * Deterministic bytes: identical inputs always produce identical
 * files. Managed like every other generated asset (drift-checked,
 * proof-bound, repaired by `chrono init --runtime opencode`).
 */

export const OPENCODE_TOOLS_FILE_RELATIVE = ".opencode/tools/chrono.ts";
export const OPENCODE_TOOLS_PACKAGE_RELATIVE = ".opencode/package.json";

/** Pinned custom-tool runtime (deterministic bytes + provenance). */
export const OPENCODE_PLUGIN_DEP = "@opencode-ai/plugin";
export const OPENCODE_PLUGIN_PIN = "1.18.30";

/**
 * Native tool names exposed to the model (file `chrono`, export suffix).
 * There is deliberately NO approval-confirm tool: signing follows only
 * an explicit human answer observed by the plugin host, never model
 * tool invocation (fail-open fix). Lifecycle tools (CORE_FIX vertical)
 * are narrow, capability-gated state operations; the Core validates
 * every call against the caller role, session scope, and binding.
 */
export const CHRONO_NATIVE_TOOLS = [
  "chrono_artifact_status",
  "chrono_artifact_propose",
  "chrono_artifact_revise",
  "chrono_artifact_supersede",
  "chrono_approval_request",
  "chrono_approval_status",
  "chrono_dispatch",
  "chrono_dispatch_claim",
  "chrono_next",
  "chrono_execution_status",
  "chrono_evidence_record",
  "chrono_evidence_status",
  "chrono_complete_request",
  "chrono_review_request",
  "chrono_review_complete",
  "chrono_defect_record",
  "chrono_verify_record",
  "chrono_correction_open",
  "chrono_correction_complete",
  "chrono_module_complete",
  "chrono_wp_authorize",
  "chrono_deep_check",
  "chrono_policy_set",
  "chrono_policy_status",
  "chrono_dispatch_confirm",
  "chrono_dispatch_release",
  "chrono_dispatch_revoke",
  "chrono_dispatch_reconcile",
  "chrono_scope_advance",
  "chrono_defect_resolve",
  "chrono_module_activate",
  "chrono_review_reconcile",
] as const;

export type ChronoNativeTool = (typeof CHRONO_NATIVE_TOOLS)[number];

/**
 * `.opencode/package.json` for the tool runtime dependency. Minimal
 * and pinned: OpenCode runs `bun install` at startup per its plugin
 * contract; without it the tools directory stays inert (fail-closed,
 * never silently ungoverned).
 */
export function buildPlanningToolsPackage(): string {
  return JSON.stringify({ dependencies: { [OPENCODE_PLUGIN_DEP]: OPENCODE_PLUGIN_PIN } }, null, 2) + "\n";
}

/**
 * Drift state of the managed tool runtime against these bytes.
 * `marker` entries tolerate user-owned content; the tool file itself
 * is byte-exact.
 */
export type PlanningToolsState =
  | { readonly state: "ok" }
  | { readonly state: "missing"; readonly reason: string }
  | { readonly state: "drifted"; readonly reason: string };

export function checkPlanningToolsFile(existing: string | null): PlanningToolsState {
  if (existing === null) {
    return { state: "missing", reason: "project planning tools are missing: run chrono init --runtime opencode to install the governed native tools" };
  }
  if (existing !== buildPlanningToolsFile()) {
    return { state: "drifted", reason: "project planning tools differ from the managed bytes: re-run chrono init --runtime opencode to reconcile (hand edits are drift, not input)" };
  }
  return { state: "ok" };
}

/**
  * Generated `.opencode/tools/chrono.ts`. Single file, thirty-two
  * named exports (`chrono_<export>` tool names). Self-contained except
  * the pinned `@opencode-ai/plugin` import and node builtins.
  */
export function buildPlanningToolsFile(): string {
  return `/**
 * CHRONO governed planning tools for OpenCode. GENERATED by
 * \`chrono setup --adapter <id>\` / \`chrono init --runtime opencode\`
 * — do not hand-edit (drift fails closed; repair regenerates).
 *
  * Thirty-two model-callable tools (OpenCode names: chrono_<export>).
  * Planning (Gaspar entry):
  * - artifact_status: Core-backed planning status projection (safe).
  * - artifact_propose: materialize one planning draft (inline body).
  * - artifact_revise: revise one planning draft (inline body).
  * - artifact_supersede: retire one draft by its replacement.
  * - approval_request: open a single-use approval ticket.
  * - approval_status: safe ticket projection (live/consumed/stale).
  * - dispatch: validate every dispatch gate and record a native
  *   dispatch intent (Gaspar only; module/WP ids, kind, rationale).
  * - dispatch_claim: bind one worker subagent session to a dispatch
  *   intent (first call a worker makes; host-held credentials only).
  * Lifecycle (CORE_FIX vertical; caller role from the session agent,
  * Core-enforced capabilities and scope on every call):
  * - next: highest-precedence next action for a scope.
  * - execution_status: own binding, scope states, revision currency.
  * - evidence_record: bind passing proof to an exact revision.
  * - evidence_status: current evidence rows for a revision.
  * - complete_request: request module completion (runs authorization).
  * - review_request: assign a Glenn/Spekkio review (Gaspar only).
  * - review_complete: submit the assigned review (reviewer only).
  * - defect_record: record a defect (Spekkio only).
  * - defect_resolve: resolve a defect after re-verification (owner).
  * - verify_record: record a Spekkio verdict (Spekkio only).
  * - correction_open: open a bounded correction loop for a defect.
  * - correction_complete: complete a loop with evidenced fix (owner).
  * - module_complete: terminal module completion (runs authorization).
  * - module_activate: activate a planned module to APPROVED after both
  *   current approvals (Gaspar only; idempotent replay).
  * - review_reconcile: reconcile a premature review as invalid history
  *   (Gaspar only; append-only, never blocking).
  * - wp_authorize: authorize one Work Package (Gaspar only).
  * - deep_check: cross-record integrity before completion (Gaspar).
  * - policy_set: calibrate rigor (downgrades need a PO signature and
  *   always deny here: the PO signs at a terminal, never via a tool).
  * - policy_status: calibrated rigor profile (public).
  * - dispatch_confirm: confirm credential confinement (claimant side).
  * - dispatch_release: release an evidenced binding to COMPLETED.
  * - dispatch_revoke: compensating revocation (Gaspar only).
  * - dispatch_reconcile: crash-safety sweep (Gaspar only).
  * - scope_advance: one legal forward step for the bound scope.
  * There is deliberately NO approval-confirm tool: signing follows
  * only an explicit human answer observed by the plugin host, never
  * model tool invocation (fail-open fix).
 *
 * Trust boundary (ADR-007):
 * - Everything here runs in the plugin host, never in model context.
 * - The Gaspar entry session token is read from a host-only 0600 file
 *   bound to the exact OpenCode session; it never enters arguments,
 *   results, logs, or prompts.
 * - Bodies travel on stdin to the CLI (argument arrays, no shell).
 * - Results carry ids, revisions, receipts, and denials only.
 */
import { tool } from "@opencode-ai/plugin";
import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, realpathSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createHash } from "node:crypto";

const TOKEN_PREFIX = "chrono-gaspar-host-";
const TOKEN_SUFFIX = ".token";

function sha16(text) {
  return createHash("sha256").update(text, "utf8").digest("hex").slice(0, 16);
}

function fail(message) {
  throw new Error("[chrono] " + message);
}

function projectRoot(directory) {
  let canonical;
  try {
    canonical = realpathSync(directory);
  } catch {
    fail("cannot resolve project directory: " + directory);
  }
  try {
    if (!existsSync(join(canonical, ".chrono", "chrono.db"))) {
      fail("no CHRONO project at " + canonical + ": run chrono init first");
    }
  } catch {
    fail("cannot inspect project directory: " + canonical);
  }
  return canonical;
}

function hostToken(root, sessionID) {
  // Host-only Gaspar entry credential for this exact OpenCode
  // session. Written by the entry flow (CHRONO_TOKEN_OUT); read here
  // for Core calls. Never returned, never logged.
  const path = join(tmpdir(), TOKEN_PREFIX + sha16(root + "|" + sessionID) + TOKEN_SUFFIX);
  let raw = "";
  try {
    raw = readFileSync(path, "utf8").trim();
  } catch {
    fail("no Gaspar entry session for this OpenCode session: reopen OpenCode so entry redeems (never export tokens yourself)");
  }
  if (raw.indexOf("/") <= 0) {
    fail("entry session credential is malformed: reopen OpenCode so entry redeems");
  }
  return raw;
}

function chronoBin() {
  const fromEnv = process.env["CHRONO_BIN"];
  return fromEnv === undefined || fromEnv === "" ? "chrono" : fromEnv;
}

function runChrono(argv, stdinText) {
  const ran = spawnSync(chronoBin(), argv, {
    input: stdinText,
    encoding: "utf8",
    timeout: 120000,
    stdio: ["pipe", "pipe", "pipe"],
  });
  const stdout = typeof ran.stdout === "string" ? ran.stdout : "";
  try {
    return { exit: ran.status ?? 1, json: JSON.parse(stdout) };
  } catch {
    return { exit: 1, json: { ok: false, error: { code: "GATE_UNREACHABLE", message: "chrono returned non-JSON output" } } };
  }
}

function deny(result, fallback) {
  const code = result?.error?.code;
  const reason = result?.error?.message;
  fail(typeof code === "string" && typeof reason === "string" ? code + ": " + reason : fallback);
}

const commonArgs = (root, token) => ["--as", "gaspar", "--session-token", token, "--path", root, "--json"];

// Lifecycle tools run as the calling session's own agent (Gaspar,
// worker, or reviewer): the host-held credential selects the Core
// session and the Core enforces role capabilities and scope per
// call. Unknown agent names fail closed at the Core.
const callerAgent = (context) => (context !== null && typeof context === "object" && typeof context.agent === "string" && context.agent.length > 0 ? context.agent : "gaspar");
const agentArgs = (root, token, agent) => ["--as", agent, "--session-token", token, "--path", root, "--json"];

export const artifact_status = tool({
  description: "CHRONO planning status: safe projection of drafts (proposed, awaiting PO signature, approved, rejected, stale). No secrets.",
  args: {},
  async execute(_args, context) {
    const root = projectRoot(context.directory);
    const token = hostToken(root, context.sessionID);
    const res = runChrono(["artifact", "status", ...commonArgs(root, token)]);
    if (res.exit !== 0 || res.json?.ok !== true) {
      deny(res.json, "planning status denied");
    }
    return JSON.stringify(res.json);
  },
});

export const artifact_propose = tool({
  description: "CHRONO: materialize one governed planning draft (discovery, requirement, architecture, adr, spec, harness-draft, security-profile, roadmap, module, workpackage). Body is inline Markdown; the Core derives the canonical destination. Untrusted DRAFT until PO-signed approval.",
  args: {
    kind: tool.schema.string().describe("planning kind"),
    id: tool.schema.string().optional().describe("canonical identifier (allocated by the Core when omitted)"),
    title: tool.schema.string().describe("draft title"),
    body: tool.schema.string().describe("inline Markdown body"),
    references: tool.schema.array(tool.schema.string()).optional().describe("existing artifact or draft references"),
  },
  async execute(args, context) {
    const root = projectRoot(context.directory);
    const token = hostToken(root, context.sessionID);
    const argv = ["artifact", "propose", "--kind", args.kind, "--title", args.title, "--body-stdin", ...commonArgs(root, token)];
    if (args.id !== undefined && args.id.length > 0) {
      argv.push("--id", args.id);
    }
    for (const ref of args.references ?? []) {
      argv.push("--ref", ref);
    }
    const res = runChrono(argv, args.body);
    if (res.exit !== 0 || res.json?.ok !== true) {
      deny(res.json, "planning propose denied");
    }
    return JSON.stringify(res.json);
  },
});

export const artifact_revise = tool({
  description: "CHRONO: revise one planning draft to a new revision (prior approvals go stale). Body is inline Markdown. A missing file with identical content heals in place.",
  args: {
    id: tool.schema.string().describe("planning artifact identifier"),
    title: tool.schema.string().describe("revised title"),
    body: tool.schema.string().describe("inline Markdown body"),
  },
  async execute(args, context) {
    const root = projectRoot(context.directory);
    const token = hostToken(root, context.sessionID);
    const res = runChrono(["artifact", "revise", "--id", args.id, "--title", args.title, "--body-stdin", ...commonArgs(root, token)], args.body);
    if (res.exit !== 0 || !res.json || res.json.ok !== true) {
      deny(res.json, "planning revise denied");
    }
    return JSON.stringify(res.json);
  },
});

export const artifact_supersede = tool({
  description: "CHRONO: retire one planning draft by its replacement (file keeps a banner; history preserved; status points at the replacement).",
  args: {
    id: tool.schema.string().describe("planning artifact identifier to retire"),
    supersededBy: tool.schema.string().describe("replacing draft identifier (must resolve)"),
  },
  async execute(args, context) {
    const root = projectRoot(context.directory);
    const token = hostToken(root, context.sessionID);
    const res = runChrono(["artifact", "supersede", "--id", args.id, "--by", args.supersededBy, ...commonArgs(root, token)]);
    if (res.exit !== 0 || !res.json || res.json.ok !== true) {
      deny(res.json, "planning supersede denied");
    }
    return JSON.stringify(res.json);
  },
});

export const approval_request = tool({
  description: "CHRONO: open a single-use approval ticket binding action, scope, exact revision, rationale, and security implications. The ticket alone authorizes nothing; human confirmation follows.",
  args: {
    action: tool.schema.string().describe("approval action"),
    scope: tool.schema.string().describe("artifact scope identifier"),
    revision: tool.schema.string().describe("exact scope revision hash"),
    rationale: tool.schema.string().describe("decision rationale"),
    securityImplications: tool.schema.string().describe("explicit security implications"),
  },
  async execute(args, context) {
    const root = projectRoot(context.directory);
    const token = hostToken(root, context.sessionID);
    const res = runChrono([
      "approval-request", "--action", args.action, "--scope", args.scope, "--revision", args.revision,
      "--rationale", args.rationale, "--security-implications", args.securityImplications,
      "--require-question", ...commonArgs(root, token),
    ]);
    if (res.exit !== 0 || !res.json || res.json.ok !== true) {
      deny(res.json, "approval request denied");
    }
    return JSON.stringify(res.json);
  },
});

export const approval_status = tool({
  description: "CHRONO: safe approval-ticket projection (live, consumed, stale). No secrets; tickets carry none.",
  args: {
    ticket: tool.schema.string().describe("approval ticket id"),
  },
  async execute(args, context) {
    const root = projectRoot(context.directory);
    const token = hostToken(root, context.sessionID);
    const res = runChrono(["approval-ticket", "--ticket", args.ticket, ...commonArgs(root, token)]);
    if (res.exit !== 0 || res.json?.ok !== true) {
      deny(res.json, "approval status denied");
    }
    return JSON.stringify(res.json);
  },
});

export const dispatch = tool({
  description: "CHRONO: validate every dispatch gate for a module/work package and record a native dispatch intent (Gaspar only). Then delegate with the task tool to exactly one fitting role; the worker claims the intent. Never ask the PO to run shell commands.",
  args: {
    module: tool.schema.string().describe("module identifier (must be approved/current)"),
    wp: tool.schema.string().optional().describe("work-package identifier (required when the module has Work Packages)"),
    kind: tool.schema.string().optional().describe("dispatch kind: implementation, test, security-review, verification, correction (default implementation)"),
    proposedProfile: tool.schema.string().optional().describe("proposed rigor profile: lean, standard, critical (can only raise, never lower)"),
    rationale: tool.schema.string().describe("why this dispatch starts now (1-500 chars)"),
  },
  async execute(args, context) {
    const root = projectRoot(context.directory);
    const token = hostToken(root, context.sessionID);
    const argv = [
      "dispatch-request", "--module", args.module, "--rationale", args.rationale,
      "--opencode-session", context.sessionID, ...commonArgs(root, token),
    ];
    if (args.wp !== undefined && args.wp.length > 0) {
      argv.push("--wp", args.wp);
    }
    if (args.kind !== undefined && args.kind.length > 0) {
      argv.push("--kind", args.kind);
    }
    if (args.proposedProfile !== undefined && args.proposedProfile.length > 0) {
      argv.push("--proposed-profile", args.proposedProfile);
    }
    const res = runChrono(argv);
    if (res.exit !== 0 || !res.json || res.json.ok !== true) {
      deny(res.json, "dispatch request denied");
    }
    return JSON.stringify(res.json);
  },
});

export const dispatch_claim = tool({
  description: "CHRONO: bind this worker subagent session to a dispatch intent. Call exactly once before any other work, passing the dispatch id from the dispatch prompt. The host confines credentials; nothing secret is returned.",
  args: {
    dispatch: tool.schema.string().describe("dispatch intent id from the dispatch prompt"),
  },
  async execute(args, context) {
    const root = projectRoot(context.directory);
    const agent = context !== null && typeof context === "object" && typeof context.agent === "string" ? context.agent : "";
    const res = runChrono([
      "dispatch-claim", "--dispatch", args.dispatch, "--agent", agent,
      "--worker-session", context.sessionID, "--path", root, "--json",
    ]);
    if (res.exit !== 0 || !res.json || res.json.ok !== true) {
      deny(res.json, "dispatch claim denied");
    }
    return JSON.stringify(res.json);
  },
});

export const next = tool({
  description: "CHRONO: highest-precedence next action for a module or work package, derived from Core records (open loops, stale dispatches, open reviews, readiness). Workers see their own scope.",
  args: {
    module: tool.schema.string().optional().describe("module identifier"),
    wp: tool.schema.string().optional().describe("work-package identifier (takes precedence over module)"),
  },
  async execute(args, context) {
    const root = projectRoot(context.directory);
    const token = hostToken(root, context.sessionID);
    const argv = ["next-action", ...agentArgs(root, token, callerAgent(context))];
    if (args.module !== undefined && args.module.length > 0) {
      argv.push("--module", args.module);
    }
    if (args.wp !== undefined && args.wp.length > 0) {
      argv.push("--wp", args.wp);
    }
    const res = runChrono(argv);
    if (res.exit !== 0 || !res.json || res.json.ok !== true) {
      deny(res.json, "next action denied");
    }
    return JSON.stringify(res.json);
  },
});

export const execution_status = tool({
  description: "CHRONO: worker execution projection — own binding, scope states, revision currency. No secrets cross, ever.",
  args: {
    module: tool.schema.string().optional().describe("module identifier"),
    wp: tool.schema.string().optional().describe("work-package identifier (takes precedence over module)"),
  },
  async execute(args, context) {
    const root = projectRoot(context.directory);
    const token = hostToken(root, context.sessionID);
    const argv = ["execution-status", ...agentArgs(root, token, callerAgent(context))];
    if (args.module !== undefined && args.module.length > 0) {
      argv.push("--module", args.module);
    }
    if (args.wp !== undefined && args.wp.length > 0) {
      argv.push("--wp", args.wp);
    }
    const res = runChrono(argv);
    if (res.exit !== 0 || !res.json || res.json.ok !== true) {
      deny(res.json, "execution status denied");
    }
    return JSON.stringify(res.json);
  },
});

export const evidence_record = tool({
  description: "CHRONO: record passing proof bound to an exact content revision (the claimed scope revision). The producer is the calling session role; evidence binds hash, never prose.",
  args: {
    revision: tool.schema.string().describe("exact content revision hash the proof binds"),
    check: tool.schema.string().describe("check name (what was run)"),
    result: tool.schema.string().describe("check result (pass)"),
    diagnostics: tool.schema.string().optional().describe("short output excerpt (scanned for secrets)"),
  },
  async execute(args, context) {
    const root = projectRoot(context.directory);
    const token = hostToken(root, context.sessionID);
    const argv = [
      "evidence-record", "--revision", args.revision, "--check", args.check, "--result", args.result,
      ...agentArgs(root, token, callerAgent(context)),
    ];
    if (args.diagnostics !== undefined && args.diagnostics.length > 0) {
      argv.push("--diagnostics", args.diagnostics);
    }
    const res = runChrono(argv);
    if (res.exit !== 0 || !res.json || res.json.ok !== true) {
      deny(res.json, "evidence record denied");
    }
    return JSON.stringify(res.json);
  },
});

export const evidence_status = tool({
  description: "CHRONO: current evidence rows for one content revision (ids producers cite in verdicts). No diagnostics cross.",
  args: {
    revision: tool.schema.string().describe("content revision hash to project"),
  },
  async execute(args, context) {
    const root = projectRoot(context.directory);
    const token = hostToken(root, context.sessionID);
    const res = runChrono(["evidence-status", "--revision", args.revision, ...agentArgs(root, token, callerAgent(context))]);
    if (res.exit !== 0 || !res.json || res.json.ok !== true) {
      deny(res.json, "evidence status denied");
    }
    return JSON.stringify(res.json);
  },
});

export const complete_request = tool({
  description: "CHRONO: request module completion. Runs the full completion authorization (verdicts, evidence per profile, approvals, defects, blockers); the terminal transition fires only when every gate holds.",
  args: {
    module: tool.schema.string().describe("module identifier"),
  },
  async execute(args, context) {
    const root = projectRoot(context.directory);
    const token = hostToken(root, context.sessionID);
    const res = runChrono(["complete-module", "--module", args.module, ...agentArgs(root, token, callerAgent(context))]);
    if (res.exit !== 0 || !res.json || res.json.ok !== true) {
      deny(res.json, "completion request denied");
    }
    return JSON.stringify(res.json);
  },
});

export const review_request = tool({
  description: "CHRONO: assign a Glenn security review or Spekkio verification for a scope at its current revision (Gaspar only; the Core binds reviewer independence).",
  args: {
    kind: tool.schema.string().describe("review kind: security-review or verification"),
    module: tool.schema.string().describe("module identifier"),
    wp: tool.schema.string().optional().describe("work-package identifier"),
  },
  async execute(args, context) {
    const root = projectRoot(context.directory);
    const token = hostToken(root, context.sessionID);
    const argv = ["review-assign", "--kind", args.kind, "--module", args.module, ...agentArgs(root, token, callerAgent(context))];
    if (args.wp !== undefined && args.wp.length > 0) {
      argv.push("--wp", args.wp);
    }
    const res = runChrono(argv);
    if (res.exit !== 0 || !res.json || res.json.ok !== true) {
      deny(res.json, "review assign denied");
    }
    return JSON.stringify(res.json);
  },
});

export const review_complete = tool({
  description: "CHRONO: submit the assigned review from the reviewer session (Glenn evidence or Spekkio verdict bound first). Independence from the implementer session is enforced.",
  args: {
    review: tool.schema.string().describe("review assignment id"),
  },
  async execute(args, context) {
    const root = projectRoot(context.directory);
    const token = hostToken(root, context.sessionID);
    const res = runChrono(["review-complete", "--review", args.review, ...agentArgs(root, token, callerAgent(context))]);
    if (res.exit !== 0 || !res.json || res.json.ok !== true) {
      deny(res.json, "review complete denied");
    }
    return JSON.stringify(res.json);
  },
});

export const defect_record = tool({
  description: "CHRONO: record a defect against concrete artifacts (Spekkio only; routes to the responsible owner and blocks completion).",
  args: {
    classification: tool.schema.string().describe("defect classification"),
    severity: tool.schema.string().describe("defect severity"),
    artifact: tool.schema.string().optional().describe("comma-separated affected artifact ids"),
    blockingScope: tool.schema.string().optional().describe("scope the defect blocks"),
    repro: tool.schema.string().optional().describe("reproduction info"),
  },
  async execute(args, context) {
    const root = projectRoot(context.directory);
    const token = hostToken(root, context.sessionID);
    const argv = [
      "defect-record", "--classification", args.classification, "--severity", args.severity,
      ...agentArgs(root, token, callerAgent(context)),
    ];
    if (args.artifact !== undefined && args.artifact.length > 0) {
      argv.push("--artifact", args.artifact);
    }
    if (args.blockingScope !== undefined && args.blockingScope.length > 0) {
      argv.push("--blocking-scope", args.blockingScope);
    }
    if (args.repro !== undefined && args.repro.length > 0) {
      argv.push("--repro", args.repro);
    }
    const res = runChrono(argv);
    if (res.exit !== 0 || !res.json || res.json.ok !== true) {
      deny(res.json, "defect record denied");
    }
    return JSON.stringify(res.json);
  },
});

export const verify_record = tool({
  description: "CHRONO: record a Spekkio verification verdict for a scope revision (Spekkio only; FAILED opens bounded correction loops, PASS closes them).",
  args: {
    module: tool.schema.string().describe("module identifier"),
    verdict: tool.schema.string().describe("PASS, FAILED, or WAIVED"),
    reviewer: tool.schema.string().describe("reviewing role (spekkio)"),
    defects: tool.schema.string().optional().describe("comma-separated defect ids (FAILED)"),
    evidence: tool.schema.string().optional().describe("comma-separated evidence ids reviewed"),
    wp: tool.schema.string().optional().describe("work-package identifier"),
  },
  async execute(args, context) {
    const root = projectRoot(context.directory);
    const token = hostToken(root, context.sessionID);
    const argv = [
      "verify-record", "--module", args.module, "--verdict", args.verdict, "--reviewer", args.reviewer,
      ...agentArgs(root, token, callerAgent(context)),
    ];
    if (args.defects !== undefined && args.defects.length > 0) {
      argv.push("--defects", args.defects);
    }
    if (args.evidence !== undefined && args.evidence.length > 0) {
      argv.push("--evidence", args.evidence);
    }
    if (args.wp !== undefined && args.wp.length > 0) {
      argv.push("--wp", args.wp);
    }
    const res = runChrono(argv);
    if (res.exit !== 0 || !res.json || res.json.ok !== true) {
      deny(res.json, "verify record denied");
    }
    return JSON.stringify(res.json);
  },
});

export const correction_open = tool({
  description: "CHRONO: open a bounded correction loop for a defect (one open loop per defect; attempts capped by the effective profile).",
  args: {
    defect: tool.schema.string().describe("defect identifier"),
  },
  async execute(args, context) {
    const root = projectRoot(context.directory);
    const token = hostToken(root, context.sessionID);
    const res = runChrono(["correction-open", "--defect", args.defect, ...agentArgs(root, token, callerAgent(context))]);
    if (res.exit !== 0 || !res.json || res.json.ok !== true) {
      deny(res.json, "correction open denied");
    }
    return JSON.stringify(res.json);
  },
});

export const correction_complete = tool({
  description: "CHRONO: complete a correction loop with the evidenced fix (owning role; pre-correction proof goes stale, re-verification follows).",
  args: {
    loop: tool.schema.string().describe("correction loop id"),
  },
  async execute(args, context) {
    const root = projectRoot(context.directory);
    const token = hostToken(root, context.sessionID);
    const res = runChrono(["correction-complete", "--loop", args.loop, ...agentArgs(root, token, callerAgent(context))]);
    if (res.exit !== 0 || !res.json || res.json.ok !== true) {
      deny(res.json, "correction complete denied");
    }
    return JSON.stringify(res.json);
  },
});

export const module_complete = tool({
  description: "CHRONO: terminal module completion through its authorization (idempotent; gaspar, spekkio, or PO session).",
  args: {
    module: tool.schema.string().describe("module identifier"),
  },
  async execute(args, context) {
    const root = projectRoot(context.directory);
    const token = hostToken(root, context.sessionID);
    const res = runChrono(["complete-module", "--module", args.module, ...agentArgs(root, token, callerAgent(context))]);
    if (res.exit !== 0 || !res.json || res.json.ok !== true) {
      deny(res.json, "module complete denied");
    }
    return JSON.stringify(res.json);
  },
});

export const wp_authorize = tool({
  description: "CHRONO: authorize one Work Package for execution (Gaspar only; the package enters AUTHORIZED).",
  args: {
    wp: tool.schema.string().describe("work-package identifier"),
  },
  async execute(args, context) {
    const root = projectRoot(context.directory);
    const token = hostToken(root, context.sessionID);
    const res = runChrono(["wp-authorize", "--wp", args.wp, ...agentArgs(root, token, callerAgent(context))]);
    if (res.exit !== 0 || !res.json || res.json.ok !== true) {
      deny(res.json, "work-package authorize denied");
    }
    return JSON.stringify(res.json);
  },
});

export const deep_check = tool({
  description: "CHRONO: cross-record integrity before completion — policy/schema versions, dispatch backlog, stale evidence citations, loop bounds (Gaspar only). Findings are advisory; repair stays explicit.",
  args: {},
  async execute(_args, context) {
    const root = projectRoot(context.directory);
    const token = hostToken(root, context.sessionID);
    const res = runChrono(["deep-check", ...agentArgs(root, token, callerAgent(context))]);
    if (res.exit !== 0 || !res.json || res.json.ok !== true) {
      deny(res.json, "deep check denied");
    }
    return JSON.stringify(res.json);
  },
});

export const policy_set = tool({
  description: "CHRONO: calibrate the project rigor profile (Gaspar proposes; raising applies, lowering always denies here — downgrades need a PO signature made at a terminal, never via a tool).",
  args: {
    profile: tool.schema.string().describe("rigor profile: lean, standard, critical"),
    rationale: tool.schema.string().describe("why this profile fits (1-500 chars)"),
  },
  async execute(args, context) {
    const root = projectRoot(context.directory);
    const token = hostToken(root, context.sessionID);
    const res = runChrono([
      "policy-set", "--profile", args.profile, "--rationale", args.rationale,
      ...agentArgs(root, token, callerAgent(context)),
    ]);
    if (res.exit !== 0 || !res.json || res.json.ok !== true) {
      deny(res.json, "policy set denied");
    }
    return JSON.stringify(res.json);
  },
});

export const policy_status = tool({
  description: "CHRONO: calibrated rigor profile (public projection).",
  args: {},
  async execute(_args, context) {
    const root = projectRoot(context.directory);
    const res = runChrono(["policy-status", "--path", root, "--json"]);
    if (res.exit !== 0 || !res.json || res.json.ok !== true) {
      deny(res.json, "policy status denied");
    }
    return JSON.stringify(res.json);
  },
});

export const dispatch_confirm = tool({
  description: "CHRONO: confirm credential confinement for an enacted dispatch (call after the host confines the worker credential; requester or worker session).",
  args: {
    dispatch: tool.schema.string().describe("dispatch id"),
  },
  async execute(args, context) {
    const root = projectRoot(context.directory);
    const token = hostToken(root, context.sessionID);
    const res = runChrono(["dispatch-confirm", "--dispatch", args.dispatch, ...agentArgs(root, token, callerAgent(context))]);
    if (res.exit !== 0 || !res.json || res.json.ok !== true) {
      deny(res.json, "dispatch confirm denied");
    }
    return JSON.stringify(res.json);
  },
});

export const dispatch_release = tool({
  description: "CHRONO: release an evidenced binding to COMPLETED (bound worker after recording proof; Gaspar oversight otherwise).",
  args: {
    dispatch: tool.schema.string().describe("dispatch id"),
  },
  async execute(args, context) {
    const root = projectRoot(context.directory);
    const token = hostToken(root, context.sessionID);
    const res = runChrono(["dispatch-release", "--dispatch", args.dispatch, ...agentArgs(root, token, callerAgent(context))]);
    if (res.exit !== 0 || !res.json || res.json.ok !== true) {
      deny(res.json, "dispatch release denied");
    }
    return JSON.stringify(res.json);
  },
});

export const dispatch_revoke = tool({
  description: "CHRONO: compensating revocation for a failed or abandoned claim (Gaspar only).",
  args: {
    dispatch: tool.schema.string().describe("dispatch id"),
    reason: tool.schema.string().optional().describe("why the binding is revoked"),
  },
  async execute(args, context) {
    const root = projectRoot(context.directory);
    const token = hostToken(root, context.sessionID);
    const argv = ["dispatch-revoke", "--dispatch", args.dispatch, ...agentArgs(root, token, callerAgent(context))];
    if (args.reason !== undefined && args.reason.length > 0) {
      argv.push("--reason", args.reason);
    }
    const res = runChrono(argv);
    if (res.exit !== 0 || !res.json || res.json.ok !== true) {
      deny(res.json, "dispatch revoke denied");
    }
    return JSON.stringify(res.json);
  },
});

export const dispatch_reconcile = tool({
  description: "CHRONO: crash-safety sweep — expire stale intents, revoke stale enactments (Gaspar only; run after restarts).",
  args: {},
  async execute(_args, context) {
    const root = projectRoot(context.directory);
    const token = hostToken(root, context.sessionID);
    const res = runChrono(["dispatch-reconcile", ...agentArgs(root, token, callerAgent(context))]);
    if (res.exit !== 0 || !res.json || res.json.ok !== true) {
      deny(res.json, "dispatch reconcile denied");
    }
    return JSON.stringify(res.json);
  },
});

export const defect_resolve = tool({
  description: "CHRONO: resolve a defect after its correction loop closed on re-verification (owning role).",
  args: {
    defect: tool.schema.string().describe("defect identifier"),
  },
  async execute(args, context) {
    const root = projectRoot(context.directory);
    const token = hostToken(root, context.sessionID);
    const res = runChrono(["defect-resolve", "--defect", args.defect, ...agentArgs(root, token, callerAgent(context))]);
    if (res.exit !== 0 || !res.json || res.json.ok !== true) {
      deny(res.json, "defect resolve denied");
    }
    return JSON.stringify(res.json);
  },
});

export const scope_advance = tool({
  description: "CHRONO: advance the bound scope one legal forward step (bound worker only; the event must fit the dispatch kind — implementation/test/correction advance work, verification advances verdicts).",
  args: {
    module: tool.schema.string().describe("module identifier"),
    wp: tool.schema.string().optional().describe("work-package identifier"),
    event: tool.schema.string().describe("forward event: ImplementationDone, VerificationReady, SpekkioPassed, SpekkioFailed, CorrectionComplete (modules: ImplementationComplete instead of Done)"),
  },
  async execute(args, context) {
    const root = projectRoot(context.directory);
    const token = hostToken(root, context.sessionID);
    const argv = ["scope-advance", "--module", args.module, "--event", args.event, ...agentArgs(root, token, callerAgent(context))];
    if (args.wp !== undefined && args.wp.length > 0) {
      argv.push("--wp", args.wp);
    }
    const res = runChrono(argv);
    if (res.exit !== 0 || !res.json || res.json.ok !== true) {
      deny(res.json, "scope advance denied");
    }
    return JSON.stringify(res.json);
  },
});

export const module_activate = tool({
  description: "CHRONO: activate a planned module to APPROVED after its current planning and module approvals (Gaspar only; idempotent replay, resumable across restarts).",
  args: {
    module: tool.schema.string().describe("module identifier"),
  },
  async execute(args, context) {
    const root = projectRoot(context.directory);
    const token = hostToken(root, context.sessionID);
    const res = runChrono(["module-activate", "--module", args.module, ...agentArgs(root, token, callerAgent(context))]);
    if (res.exit !== 0 || !res.json || res.json.ok !== true) {
      deny(res.json, "module activate denied");
    }
    return JSON.stringify(res.json);
  },
});

export const review_reconcile = tool({
  description: "CHRONO: reconcile a premature review assignment as invalid history (Gaspar only; append-only, never blocking).",
  args: {
    review: tool.schema.string().describe("review assignment id"),
  },
  async execute(args, context) {
    const root = projectRoot(context.directory);
    const token = hostToken(root, context.sessionID);
    const res = runChrono(["review-reconcile", "--review", args.review, ...agentArgs(root, token, callerAgent(context))]);
    if (res.exit !== 0 || !res.json || res.json.ok !== true) {
      deny(res.json, "review reconcile denied");
    }
    return JSON.stringify(res.json);
  },
});

`;
}
