/**
 * Native OpenCode planning tools (OC-P11 correction, C4–C6).
 *
 * The generated Gaspar agent cannot reach Core-governed planning
 * through generic shell (blocked pre-dispatch) or temp files (cannot
 * create them). This module generates real, model-callable tools under
 * `.opencode/tools/chrono.ts` (one file, six named exports) using the
 * documented OpenCode 1.18.30 custom-tool contract
 * (`import { tool } from "@opencode-ai/plugin"`, Zod schemas, and a
 * `ToolContext` with session/agent/directory/worktree plus `ask()`).
 * The emitted module is plain JavaScript (no TypeScript syntax) so it
 * loads identically under OpenCode/bun and under Node in tests.
 *
 * Every tool executes in the plugin host (never in model context):
 * project from `ToolContext.directory`, session from the host-only
 * entry token bound to the exact OpenCode session, CLI/Core through
 * argument arrays with stdin bodies (no shell, no temp files), and
 * only safe structured results back. Approval confirmation additionally
 * requires the native `ask()` human boundary inside `execute`.
 *
 * Deterministic bytes: identical inputs always produce identical
 * files. Managed like every other generated asset (drift-checked,
 * proof-bound, repaired by `chrono init --runtime opencode`).
 */

export const OPENCODE_TOOLS_FILE_RELATIVE = ".opencode/tools/chrono.ts";
export const OPENCODE_TOOLS_PACKAGE_RELATIVE = ".opencode/package.json";

/** Pinned custom-tool runtime (deterministic bytes + provenance). */
export const OPENCODE_PLUGIN_DEP = "@opencode-ai/plugin";
export const OPENCODE_PLUGIN_PIN = "1.18.30";

/**
 * Native tool names exposed to the model (file `chrono`, export suffix).
 * There is deliberately NO approval-confirm tool: signing follows only
 * an explicit human answer observed by the plugin host, never model
 * tool invocation (fail-open fix).
 */
export const CHRONO_NATIVE_TOOLS = [
  "chrono_artifact_status",
  "chrono_artifact_propose",
  "chrono_artifact_revise",
  "chrono_artifact_supersede",
  "chrono_approval_request",
  "chrono_approval_status",
] as const;

export type ChronoNativeTool = (typeof CHRONO_NATIVE_TOOLS)[number];

/**
 * `.opencode/package.json` for the tool runtime dependency. Minimal
 * and pinned: OpenCode runs `bun install` at startup per its plugin
 * contract; without it the tools directory stays inert (fail-closed,
 * never silently ungoverned).
 */
export function buildPlanningToolsPackage(): string {
  return JSON.stringify({ dependencies: { [OPENCODE_PLUGIN_DEP]: OPENCODE_PLUGIN_PIN } }, null, 2) + "\n";
}

/**
 * Drift state of the managed tool runtime against these bytes.
 * `marker` entries tolerate user-owned content; the tool file itself
 * is byte-exact.
 */
export type PlanningToolsState =
  | { readonly state: "ok" }
  | { readonly state: "missing"; readonly reason: string }
  | { readonly state: "drifted"; readonly reason: string };

export function checkPlanningToolsFile(existing: string | null): PlanningToolsState {
  if (existing === null) {
    return { state: "missing", reason: "project planning tools are missing: run chrono init --runtime opencode to install the governed native tools" };
  }
  if (existing !== buildPlanningToolsFile()) {
    return { state: "drifted", reason: "project planning tools differ from the managed bytes: re-run chrono init --runtime opencode to reconcile (hand edits are drift, not input)" };
  }
  return { state: "ok" };
}

/**
 * Generated `.opencode/tools/chrono.ts`. Single file, six named
 * exports (`chrono_<export>` tool names). Self-contained except the
 * pinned `@opencode-ai/plugin` import and node builtins.
 */
export function buildPlanningToolsFile(): string {
  return `/**
 * CHRONO governed planning tools for OpenCode. GENERATED by
 * \`chrono setup --adapter <id>\` / \`chrono init --runtime opencode\`
 * — do not hand-edit (drift fails closed; repair regenerates).
 *
 * Five model-callable tools (OpenCode names: chrono_<export>):
 * - artifact_status: Core-backed planning status projection (safe).
 * - artifact_propose: materialize one planning draft (inline body).
 * - artifact_revise: revise one planning draft (inline body).
 * - artifact_supersede: retire one draft by its replacement.
 * - approval_request: open a single-use approval ticket.
 * - approval_status: safe ticket projection (live/consumed/stale).
 * There is deliberately NO approval-confirm tool: signing follows
 * only an explicit human answer observed by the plugin host, never
 * model tool invocation (fail-open fix).
 *
 * Trust boundary (ADR-007):
 * - Everything here runs in the plugin host, never in model context.
 * - The Gaspar entry session token is read from a host-only 0600 file
 *   bound to the exact OpenCode session; it never enters arguments,
 *   results, logs, or prompts.
 * - Bodies travel on stdin to the CLI (argument arrays, no shell).
 * - Results carry ids, revisions, receipts, and denials only.
 */
import { tool } from "@opencode-ai/plugin";
import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, realpathSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createHash } from "node:crypto";

const TOKEN_PREFIX = "chrono-gaspar-host-";
const TOKEN_SUFFIX = ".token";

function sha16(text) {
  return createHash("sha256").update(text, "utf8").digest("hex").slice(0, 16);
}

function fail(message) {
  throw new Error("[chrono] " + message);
}

function projectRoot(directory) {
  let canonical;
  try {
    canonical = realpathSync(directory);
  } catch {
    fail("cannot resolve project directory: " + directory);
  }
  try {
    if (!existsSync(join(canonical, ".chrono", "chrono.db"))) {
      fail("no CHRONO project at " + canonical + ": run chrono init first");
    }
  } catch {
    fail("cannot inspect project directory: " + canonical);
  }
  return canonical;
}

function hostToken(root, sessionID) {
  // Host-only Gaspar entry credential for this exact OpenCode
  // session. Written by the entry flow (CHRONO_TOKEN_OUT); read here
  // for Core calls. Never returned, never logged.
  const path = join(tmpdir(), TOKEN_PREFIX + sha16(root + "|" + sessionID) + TOKEN_SUFFIX);
  let raw = "";
  try {
    raw = readFileSync(path, "utf8").trim();
  } catch {
    fail("no Gaspar entry session for this OpenCode session: reopen OpenCode so entry redeems (never export tokens yourself)");
  }
  if (raw.indexOf("/") <= 0) {
    fail("entry session credential is malformed: reopen OpenCode so entry redeems");
  }
  return raw;
}

function chronoBin() {
  const fromEnv = process.env["CHRONO_BIN"];
  return fromEnv === undefined || fromEnv === "" ? "chrono" : fromEnv;
}

function runChrono(argv, stdinText) {
  const ran = spawnSync(chronoBin(), argv, {
    input: stdinText,
    encoding: "utf8",
    timeout: 120000,
    stdio: ["pipe", "pipe", "pipe"],
  });
  const stdout = typeof ran.stdout === "string" ? ran.stdout : "";
  try {
    return { exit: ran.status ?? 1, json: JSON.parse(stdout) };
  } catch {
    return { exit: 1, json: { ok: false, error: { code: "GATE_UNREACHABLE", message: "chrono returned non-JSON output" } } };
  }
}

function deny(result, fallback) {
  const code = result?.error?.code;
  const reason = result?.error?.message;
  fail(typeof code === "string" && typeof reason === "string" ? code + ": " + reason : fallback);
}

const commonArgs = (root, token) => ["--as", "gaspar", "--session-token", token, "--path", root, "--json"];

export const artifact_status = tool({
  description: "CHRONO planning status: safe projection of drafts (proposed, awaiting PO signature, approved, rejected, stale). No secrets.",
  args: {},
  async execute(_args, context) {
    const root = projectRoot(context.directory);
    const token = hostToken(root, context.sessionID);
    const res = runChrono(["artifact", "status", ...commonArgs(root, token)]);
    if (res.exit !== 0 || res.json?.ok !== true) {
      deny(res.json, "planning status denied");
    }
    return JSON.stringify(res.json);
  },
});

export const artifact_propose = tool({
  description: "CHRONO: materialize one governed planning draft (discovery, requirement, architecture, adr, spec, harness-draft, security-profile, roadmap, module, workpackage). Body is inline Markdown; the Core derives the canonical destination. Untrusted DRAFT until PO-signed approval.",
  args: {
    kind: tool.schema.string().describe("planning kind"),
    id: tool.schema.string().optional().describe("canonical identifier (allocated by the Core when omitted)"),
    title: tool.schema.string().describe("draft title"),
    body: tool.schema.string().describe("inline Markdown body"),
    references: tool.schema.array(tool.schema.string()).optional().describe("existing artifact or draft references"),
  },
  async execute(args, context) {
    const root = projectRoot(context.directory);
    const token = hostToken(root, context.sessionID);
    const argv = ["artifact", "propose", "--kind", args.kind, "--title", args.title, "--body-stdin", ...commonArgs(root, token)];
    if (args.id !== undefined && args.id.length > 0) {
      argv.push("--id", args.id);
    }
    for (const ref of args.references ?? []) {
      argv.push("--ref", ref);
    }
    const res = runChrono(argv, args.body);
    if (res.exit !== 0 || res.json?.ok !== true) {
      deny(res.json, "planning propose denied");
    }
    return JSON.stringify(res.json);
  },
});

export const artifact_revise = tool({
  description: "CHRONO: revise one planning draft to a new revision (prior approvals go stale). Body is inline Markdown. A missing file with identical content heals in place.",
  args: {
    id: tool.schema.string().describe("planning artifact identifier"),
    title: tool.schema.string().describe("revised title"),
    body: tool.schema.string().describe("inline Markdown body"),
  },
  async execute(args, context) {
    const root = projectRoot(context.directory);
    const token = hostToken(root, context.sessionID);
    const res = runChrono(["artifact", "revise", "--id", args.id, "--title", args.title, "--body-stdin", ...commonArgs(root, token)], args.body);
    if (res.exit !== 0 || !res.json || res.json.ok !== true) {
      deny(res.json, "planning revise denied");
    }
    return JSON.stringify(res.json);
  },
});

export const artifact_supersede = tool({
  description: "CHRONO: retire one planning draft by its replacement (file keeps a banner; history preserved; status points at the replacement).",
  args: {
    id: tool.schema.string().describe("planning artifact identifier to retire"),
    supersededBy: tool.schema.string().describe("replacing draft identifier (must resolve)"),
  },
  async execute(args, context) {
    const root = projectRoot(context.directory);
    const token = hostToken(root, context.sessionID);
    const res = runChrono(["artifact", "supersede", "--id", args.id, "--by", args.supersededBy, ...commonArgs(root, token)]);
    if (res.exit !== 0 || !res.json || res.json.ok !== true) {
      deny(res.json, "planning supersede denied");
    }
    return JSON.stringify(res.json);
  },
});

export const approval_request = tool({
  description: "CHRONO: open a single-use approval ticket binding action, scope, exact revision, rationale, and security implications. The ticket alone authorizes nothing; human confirmation follows.",
  args: {
    action: tool.schema.string().describe("approval action"),
    scope: tool.schema.string().describe("artifact scope identifier"),
    revision: tool.schema.string().describe("exact scope revision hash"),
    rationale: tool.schema.string().describe("decision rationale"),
    securityImplications: tool.schema.string().describe("explicit security implications"),
  },
  async execute(args, context) {
    const root = projectRoot(context.directory);
    const token = hostToken(root, context.sessionID);
    const res = runChrono([
      "approval-request", "--action", args.action, "--scope", args.scope, "--revision", args.revision,
      "--rationale", args.rationale, "--security-implications", args.securityImplications,
      ...commonArgs(root, token),
    ]);
    if (res.exit !== 0 || res.json?.ok !== true) {
      deny(res.json, "approval request denied");
    }
    return JSON.stringify(res.json);
  },
});

export const approval_status = tool({
  description: "CHRONO: safe approval-ticket projection (live, consumed, stale). No secrets; tickets carry none.",
  args: {
    ticket: tool.schema.string().describe("approval ticket id"),
  },
  async execute(args, context) {
    const root = projectRoot(context.directory);
    const token = hostToken(root, context.sessionID);
    const res = runChrono(["approval-ticket", "--ticket", args.ticket, ...commonArgs(root, token)]);
    if (res.exit !== 0 || res.json?.ok !== true) {
      deny(res.json, "approval status denied");
    }
    return JSON.stringify(res.json);
  },
});

`;
}
