/**
 * OC-P11 tool-distinction tests — governed planning artifact mutation vs
 * implementation mutation vs read-only vs forbidden internal access.
 *
 * The OpenCode adapter exposes narrow native handling for Core planning
 * operations instead of generic write/edit/bash: an exact planning
 * invocation passes with entry only (the planning CLI enforces the
 * Gaspar/PO session itself), while generic mutation still requires
 * Module dispatch and reads of internal/security state deny.
 */
import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { chmodSync, mkdtempSync, rmSync, writeFileSync, mkdirSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import { pathToFileURL } from "node:url";
import {
  TOOL_POLICY_VERSION,
  extractBashCommand,
  isPlanningBashCommand,
  referencesForbiddenState,
} from "@chrono/domain";
import { buildOpencodePlugin } from "./opencode-plugin.js";
import { buildClaudeHook } from "./claude-hook.js";
import { buildKiroHook } from "./kiro-hook.js";

function validPayload(sessionId = "SES-0001"): string {
  return JSON.stringify({
    ok: true,
    sessionId,
    projection: {
      projectState: "ANALYZING",
      nextAction: { key: "resume-discovery", summary: "Resume discovery" },
      requiredDecisions: [],
    },
    skill: { installed: true },
  });
}

describe("OC-P11 planning command classification (domain)", () => {
  it("accepts exact governed planning operations", () => {
    expect(isPlanningBashCommand("chrono artifact status --path . --json")).toBe(true);
    expect(isPlanningBashCommand("chrono artifact propose --kind spec --title T --body-file b.md")).toBe(true);
    expect(isPlanningBashCommand("chrono artifact revise --id SP-0001 --title T --body-file b.md")).toBe(true);
    expect(isPlanningBashCommand("chrono doctor --path .")).toBe(true);
    expect(isPlanningBashCommand("chrono status")).toBe(true);
    expect(isPlanningBashCommand("chrono validate --json")).toBe(true);
  });

  it("accepts the planning-runway operations (pilot repair: pre-activation has a governed path)", () => {
    expect(isPlanningBashCommand("chrono architecture-submit --json")).toBe(true);
    expect(isPlanningBashCommand("chrono architecture-approve --json")).toBe(true);
    expect(isPlanningBashCommand("chrono spec-submit --spec SP-0001 --json")).toBe(true);
    expect(isPlanningBashCommand("chrono spec-ready --spec SP-0001 --json")).toBe(true);
    expect(isPlanningBashCommand("chrono spec-needs-revision --spec SP-0001 --json")).toBe(true);
    expect(isPlanningBashCommand("chrono harness-record --revision sha256:a --content-hash sha256:b --content-stdin")).toBe(true);
    expect(isPlanningBashCommand("chrono spec-submit --spec SP-0001; echo escaped")).toBe(false);
  });

  it("rejects chaining, piping, substitution, and smuggled planning strings", () => {
    expect(isPlanningBashCommand("chrono artifact status; rm -rf /tmp/x")).toBe(false);
    expect(isPlanningBashCommand("chrono artifact status && echo pwned")).toBe(false);
    expect(isPlanningBashCommand("chrono artifact status | tee out")).toBe(false);
    expect(isPlanningBashCommand("echo chrono artifact status")).toBe(false);
    expect(isPlanningBashCommand("echo $(chrono artifact status)")).toBe(false);
    expect(isPlanningBashCommand("echo `chrono artifact status`")).toBe(false);
    expect(isPlanningBashCommand("chrono run --module MOD-0001 -- echo hi")).toBe(false);
    expect(isPlanningBashCommand("rm -rf .chrono")).toBe(false);
    expect(isPlanningBashCommand("")).toBe(false);
  });

  it("flags internal and security-state references", () => {
    expect(referencesForbiddenState("read .chrono/chrono.db")).toBe(true);
    expect(referencesForbiddenState("cat .chrono/broker-account")).toBe(true);
    expect(referencesForbiddenState("cat /tmp/chrono-gaspar-opencode-1.token")).toBe(true);
    expect(referencesForbiddenState("export CHRONO_SESSION_TOKEN=x")).toBe(true);
    expect(referencesForbiddenState("read .chrono/context/DISCOVERY.md")).toBe(false);
    expect(referencesForbiddenState("read src/index.ts")).toBe(false);
  });

  it("extracts shell commands from tool payload shapes", () => {
    expect(extractBashCommand({ command: "chrono status" })).toBe("chrono status");
    expect(extractBashCommand({ input: "chrono doctor" })).toBe("chrono doctor");
    expect(extractBashCommand("chrono validate")).toBe("chrono validate");
    expect(extractBashCommand({ tool: "bash" })).toBe(null);
    expect(extractBashCommand(null)).toBe(null);
  });
});

describe("OC-P11 OpenCode planning path (generated bytes)", () => {
  let tempDir: string;
  let pluginPath: string;
  let savedEnv: Record<string, string | undefined>;

  async function hooksFor(directory: string) {
    const module = (await import(pathToFileURL(pluginPath).href)) as {
      ChronoGatePlugin: (ctx: unknown) => Promise<{
        "tool.execute.before": (input: unknown, output?: unknown) => Promise<unknown>;
        "chat.message": (input: unknown) => Promise<unknown>;
      }>;
    };
    const hooks = await module.ChronoGatePlugin({ directory });
    return { before: hooks["tool.execute.before"], message: hooks["chat.message"] };
  }

  // Real OpenCode 1.18.30 payload shape (C1/C2): first argument carries
  // identity ({ tool, sessionID, callID }), the second carries tool
  // arguments ({ args }). Every call below uses exactly this shape.
  function bashCall(sessionID: string, command: string): [unknown, unknown] {
    return [{ tool: "bash", sessionID, callID: `call-${sessionID}` }, { args: { command } }];
  }

  function readCall(sessionID: string, filePath: string): [unknown, unknown] {
    return [{ tool: "read", sessionID, callID: `call-${sessionID}` }, { args: { filePath } }];
  }

  beforeEach(() => {
    tempDir = mkdtempSync(join(tmpdir(), "chrono-ocp11-"));
    mkdirSync(join(tempDir, ".chrono", "hooks"), { recursive: true });
    writeFileSync(join(tempDir, ".chrono", "chrono.db"), "", "utf8");
    pluginPath = join(tempDir, "chrono-gate.js");
    writeFileSync(pluginPath, buildOpencodePlugin(), "utf8");
    writeFileSync(join(tempDir, ".chrono", "hooks", "chrono-entry-session.sh"), `#!/bin/sh\necho '${validPayload()}'\n`, "utf8");
    chmodSync(join(tempDir, ".chrono", "hooks", "chrono-entry-session.sh"), 0o755);
    savedEnv = { ...process.env };
    for (const key of ["CHRONO_BIN", "CHRONO_GATE_MODULE", "CHRONO_GATE_WP", "CHRONO_SESSION_TOKEN", "CHRONO_GATE_AS", "CHRONO_GATE_ROLE", "CHRONO_REQUESTER_TOKEN", "CHRONO_ENTRY_TIMEOUT_MS"]) {
      delete process.env[key];
    }
  });

  afterEach(() => {
    for (const key of ["CHRONO_BIN", "CHRONO_GATE_MODULE", "CHRONO_GATE_WP", "CHRONO_SESSION_TOKEN", "CHRONO_GATE_AS", "CHRONO_GATE_ROLE", "CHRONO_REQUESTER_TOKEN", "CHRONO_ENTRY_TIMEOUT_MS"]) {
      if (savedEnv[key] === undefined) delete process.env[key];
      else process.env[key] = savedEnv[key];
    }
    rmSync(tempDir, { recursive: true, force: true });
  });

  it("planning bash passes with entry only; generic bash still needs dispatch", async () => {
    const hooks = await hooksFor(tempDir);
    await hooks.message({ sessionID: "plan-1" });
    await expect(hooks.before(...bashCall("plan-1", "chrono artifact status --path . --json"))).resolves.toBeUndefined();
    await expect(hooks.before(...bashCall("plan-1", "chrono approval-request --help"))).resolves.toBeUndefined();
    await expect(hooks.before(...bashCall("plan-1", "ls -la"))).rejects.toThrow(/dispatch|CHRONO_GATE_MODULE/);
    await expect(hooks.before(...bashCall("plan-1", "chrono artifact status; echo escaped"))).rejects.toThrow();
  });

  it("runway tools pass the gate with entry only (pilot TOOL_DENIED repair)", async () => {
    // The exact pilot symptom: classified runway tools must pass the
    // generated gate for a Gaspar session; anything unclassified
    // keeps deny-by-default. Pre-fix this rejects TOOL_DENIED.
    const hooks = await hooksFor(tempDir);
    await hooks.message({ sessionID: "plan-6" });
    for (const tool of [
      "chrono_architecture_submit",
      "chrono_architecture_approve",
      "chrono_spec_submit",
      "chrono_spec_ready",
      "chrono_spec_needs_revision",
      "chrono_harness_record",
    ]) {
      await expect(
        hooks.before({ tool, sessionID: "plan-6", callID: "call-plan-6" }, { args: {} })
      ).resolves.toBeUndefined();
    }
    // Bash compatibility matches the domain allowlist exactly.
    await expect(
      hooks.before(...bashCall("plan-6", "chrono spec-submit --spec SP-0001 --json"))
    ).resolves.toBeUndefined();
    await expect(
      hooks.before(...bashCall("plan-6", "chrono harness-record --revision x --content-hash y --content-stdin"))
    ).resolves.toBeUndefined();
  });

  it("generated bytes mirror the domain bash allowlist and the current tool policy version", async () => {
    const { PLANNING_BASH_PREFIXES } = await import("@chrono/domain");
    const bytes = buildOpencodePlugin();
    for (const prefix of PLANNING_BASH_PREFIXES) {
      expect(bytes, `generated gate omits bash prefix '${prefix}'`).toContain(`"${prefix}"`);
    }
    // No stale policy markers: denials and load evidence carry the
    // current version, interpolated from the constant.
    expect(bytes).toContain(`CHRONO tool policy v${TOOL_POLICY_VERSION}`);
    expect(bytes).not.toContain("tool policy v6");
    expect(bytes).not.toContain("tool policy v7");
    expect(bytes).not.toContain("tool policy v8");
    expect(bytes).not.toContain("tool policy v9");
  });

  it("native planning tools pass with entry only (C5); no signing tool exists", async () => {
    const hooks = await hooksFor(tempDir);
    await hooks.message({ sessionID: "plan-4" });
    for (const tool of [
      "chrono_artifact_status",
      "chrono_artifact_propose",
      "chrono_artifact_revise",
      "chrono_artifact_supersede",
      "chrono_approval_request",
      "chrono_approval_status",
    ]) {
      await expect(
        hooks.before({ tool, sessionID: "plan-4", callID: "call-plan-4" }, { args: {} })
      ).resolves.toBeUndefined();
    }
    // Fail-open fix: a signing tool must not exist even by accident.
    // An unknown chrono_approval_confirm is deny-by-default, not a
    // bypass: without dispatch context it cannot reach any gate.
    await expect(
      hooks.before({ tool: "chrono_approval_confirm", sessionID: "plan-4", callID: "call-plan-4" }, { args: {} })
    ).rejects.toThrow(/TOOL_DENIED/);
  });

  it("the old fictional single-argument shape alone authorizes nothing (C2 regression)", async () => {
    // Before the C1 correction, tests placed `command` in the first
    // argument — a shape the real runtime never sends. That shape must
    // NOT reach the planning path: without a second-argument command
    // the call is unclassifiable and stays dispatch-gated.
    const hooks = await hooksFor(tempDir);
    await hooks.message({ sessionID: "plan-5" });
    await expect(
      hooks.before({ tool: "bash", sessionID: "plan-5", command: "chrono artifact status --path . --json" } as unknown)
    ).rejects.toThrow(/dispatch|CHRONO_GATE_MODULE/);
  });

  it("generic write/edit stay blocked before dispatch", async () => {
    const hooks = await hooksFor(tempDir);
    await hooks.message({ sessionID: "plan-2" });
    const writeCall: [unknown, unknown] = [
      { tool: "write", sessionID: "plan-2", callID: "call-plan-2" },
      { args: { filePath: ".chrono/specs/SP-0001.md", content: "x" } },
    ];
    const editCall: [unknown, unknown] = [
      { tool: "edit", sessionID: "plan-2", callID: "call-plan-2" },
      { args: { filePath: "src/app.ts", oldText: "a", newText: "b" } },
    ];
    await expect(hooks.before(...writeCall)).rejects.toThrow(/dispatch|CHRONO_GATE_MODULE/);
    await expect(hooks.before(...editCall)).rejects.toThrow(/dispatch|CHRONO_GATE_MODULE/);
  });

  it("reads of internal and security state deny; ordinary reads pass", async () => {
    const hooks = await hooksFor(tempDir);
    await hooks.message({ sessionID: "plan-3" });
    await expect(hooks.before(...readCall("plan-3", ".chrono/chrono.db"))).rejects.toThrow(/SECRET_DETECTED/);
    await expect(hooks.before(...readCall("plan-3", ".chrono/broker-account"))).rejects.toThrow(/SECRET_DETECTED/);
    await expect(hooks.before(...readCall("plan-3", ".chrono/context/DISCOVERY.md"))).resolves.toBeUndefined();
    await expect(hooks.before(...readCall("plan-3", "src/app.ts"))).resolves.toBeUndefined();
  });
});

describe.each([
  { runtime: "claude", build: buildClaudeHook, filename: "chrono-claude-gate.js", shellTool: "Bash" },
  { runtime: "kiro", build: buildKiroHook, filename: "chrono-kiro-gate.js", shellTool: "shell" },
])("$runtime planning path ($filename)", ({ build, filename, shellTool }) => {
  let tempDir: string;
  let hookPath: string;

  function runHook(toolName: string, toolInput: unknown, env: Record<string, string> = {}) {
    const fullEnv: Record<string, string> = {};
    for (const [key, value] of Object.entries(process.env)) {
      if (value !== undefined) fullEnv[key] = value;
    }
    for (const [key, value] of Object.entries(env)) fullEnv[key] = value;
    const result = spawnSync("node", [hookPath], {
      cwd: tempDir,
      env: fullEnv,
      input: JSON.stringify({ tool_name: toolName, tool_input: toolInput }),
      encoding: "utf8",
    });
    return { status: result.status, stderr: String(result.stderr ?? "") };
  }

  beforeEach(() => {
    tempDir = mkdtempSync(join(tmpdir(), "chrono-hook-plan-"));
    mkdirSync(join(tempDir, ".chrono"), { recursive: true });
    writeFileSync(join(tempDir, ".chrono", "chrono.db"), "", "utf8");
    hookPath = join(tempDir, filename);
    writeFileSync(hookPath, build(), "utf8");
  });

  afterEach(() => {
    rmSync(tempDir, { recursive: true, force: true });
  });

  it("planning shell allows without dispatch; generic shell still denies", () => {
    const planning = runHook(shellTool, { command: "chrono artifact status --path . --json" }, {});
    expect(planning.status).toBe(0);
    const generic = runHook(shellTool, { command: "ls -la" }, {});
    expect(generic.status).toBe(2);
    expect(generic.stderr).toContain("dispatch");
    const chained = runHook(shellTool, { command: "chrono artifact status; echo escaped" }, {});
    expect(chained.status).toBe(2);
  });

  it("reads of internal state deny; ordinary reads pass", () => {
    const readTool = filename.includes("claude") ? "Read" : "read";
    const forbidden = runHook(readTool, { file_path: ".chrono/chrono.db" }, {});
    expect(forbidden.status).toBe(2);
    expect(forbidden.stderr).toContain("SECRET_DETECTED");
    const ordinary = runHook(readTool, { file_path: "src/app.ts" }, {});
    expect(ordinary.status).toBe(0);
  });
});
