/**
 * Exhaustive policy-surface parity (gate item 2): the canonical
 * domain policy (OPENCODE_TOOL_POLICY) is the one effective source
 * of truth for the native tool surface. This test enumerates every
 * CHRONO native tool emitted in `.opencode/tools/chrono.ts` and
 * proves, against the REAL generated plugin bytes (never a copy):
 *
 * - every emitted tool is classified by the canonical policy;
 * - every canonical chrono_* entry is emitted (no obsolete tool
 *   remains allowed);
 * - the generated gate sets equal the policy-derived sets exactly
 *   (planning, lifecycle, read, mutate — byte-parsed, order-free);
 * - the generated policy version equals TOOL_POLICY_VERSION;
 * - the six runway tools pass the real generated
 *   `tool.execute.before` hook in a Gaspar session;
 * - an unknown tool still fails closed.
 *
 * Adding a tool to the runtime surface without a policy entry fails
 * here by construction.
 */
import { describe, it, expect } from "vitest";
import { chmodSync, mkdtempSync, rmSync, writeFileSync, mkdirSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import {
  OPENCODE_TOOL_POLICY,
  TOOL_POLICY_VERSION,
  classifyOpencodeTool,
} from "@chrono/domain";
import { buildOpencodePlugin } from "./opencode-plugin.js";
import { CHRONO_NATIVE_TOOLS } from "./opencode-planning-tools.js";

function validPayload(sessionId = "SES-0001"): string {
  return JSON.stringify({
    ok: true,
    sessionId,
    projection: {
      projectState: "ANALYZING",
      nextAction: { key: "resume-discovery", summary: "Resume discovery" },
      requiredDecisions: [],
    },
    skill: { installed: true },
  });
}

/** Parse one `const NAME = new Set([...])` literal from generated bytes. */
function generatedSet(bytes: string, name: string): string[] {
  const match = new RegExp(`const ${name} = new Set\\(\\[([\\s\\S]*?)\\]\\)`).exec(bytes);
  if (match === null || match[1] === undefined) {
    throw new Error(`generated plugin omits the ${name} set literal`);
  }
  const found: string[] = [];
  for (const item of match[1].split(",")) {
    const literal = /"([^"]+)"/.exec(item);
    if (literal !== null && literal[1] !== undefined) {
      found.push(literal[1]);
    }
  }
  return found.sort();
}

function policyTools(kind: string): string[] {
  return Object.keys(OPENCODE_TOOL_POLICY).filter((t) => OPENCODE_TOOL_POLICY[t] === kind).sort();
}

describe("Policy-surface parity (canonical domain policy)", () => {
  it("classifies every emitted native tool and emits every canonical chrono_* entry", () => {
    const emitted = [...CHRONO_NATIVE_TOOLS];
    expect(emitted.length).toBeGreaterThan(0);
    for (const tool of emitted) {
      expect(classifyOpencodeTool(tool), `emitted tool '${tool}' has no canonical policy entry`).toBeTruthy();
    }
    const canonicalChrono = Object.keys(OPENCODE_TOOL_POLICY).filter((t) => t.startsWith("chrono_")).sort();
    expect([...emitted].sort()).toEqual(canonicalChrono);
  });

  it("generates gate sets identical to the canonical policy (planning, lifecycle, read, mutate)", () => {
    const bytes = buildOpencodePlugin();
    for (const kind of ["planning", "lifecycle", "read", "mutate"] as const) {
      const setName = `${kind.toUpperCase()}_TOOLS`;
      expect(generatedSet(bytes, setName)).toEqual(policyTools(kind));
    }
  });

  it("stamps the generated policy version from TOOL_POLICY_VERSION, never a copy", () => {
    const bytes = buildOpencodePlugin();
    // Interpolated at generation from the constant: a policy bump
    // changes every denial and load row without touching prose.
    expect(bytes).toContain(`CHRONO tool policy v${TOOL_POLICY_VERSION}`);
    expect(bytes).not.toContain("tool policy v6");
    expect(bytes).not.toContain("tool policy v7");
    expect(bytes).not.toContain("tool policy v8");
    expect(bytes).not.toContain('"v4"');
  });

  it("passes classified runway tools and fails unknown tools closed through the real hook", async () => {
    const tempDir = mkdtempSync(join(tmpdir(), "chrono-policy-parity-"));
    try {
      mkdirSync(join(tempDir, ".chrono", "hooks"), { recursive: true });
      writeFileSync(join(tempDir, ".chrono", "chrono.db"), "", "utf8");
      const pluginPath = join(tempDir, "chrono-gate.js");
      writeFileSync(pluginPath, buildOpencodePlugin(), "utf8");
      writeFileSync(join(tempDir, ".chrono", "hooks", "chrono-entry-session.sh"), `#!/bin/sh\necho '${validPayload()}'\n`, "utf8");
      chmodSync(join(tempDir, ".chrono", "hooks", "chrono-entry-session.sh"), 0o755);
      const module = (await import(pathToFileURL(pluginPath).href)) as {
        ChronoGatePlugin: (ctx: unknown) => Promise<{
          "tool.execute.before": (input: unknown, output?: unknown) => Promise<unknown>;
          "chat.message": (input: unknown) => Promise<unknown>;
        }>;
      };
      const hooks = await module.ChronoGatePlugin({ directory: tempDir });
      await hooks["chat.message"]({ sessionID: "parity-1" });
      for (const tool of [
        "chrono_architecture_submit",
        "chrono_architecture_approve",
        "chrono_spec_submit",
        "chrono_spec_ready",
        "chrono_spec_needs_revision",
        "chrono_harness_record",
      ]) {
        await expect(
          hooks["tool.execute.before"]({ tool, sessionID: "parity-1", callID: "call-parity" }, { args: {} })
        ).resolves.toBeUndefined();
      }
      await expect(
        hooks["tool.execute.before"]({ tool: "chrono_future_unclassified", sessionID: "parity-1", callID: "call-parity" }, { args: {} })
      ).rejects.toThrow(/TOOL_DENIED/);
    } finally {
      rmSync(tempDir, { recursive: true, force: true });
    }
  });
});
